### ISSUE TITLE
`Guide.manual_color_key` MethodError: no method matching parse_colorant(::Array{String,1})

### ISSUE THREAD

**Issue by xqrongm** [GiovineItalia/Gadfly.jl#1005]
Julia v0.5.2
Compose v0.5.1
Gadfly v0.6.2

`
Guide.manual_color_key("Legend", ["Points", "Line"], ["green", "deepskyblue"]) # copied directly from "http://gadflyjl.org/stable/lib/guides/guide_manual_color_key.html#Guide.manual_color_key-1"
`

resulted in:

`
ERROR: MethodError: no method matching parse_colorant(::Array{String,1})
Closest candidates are:
  parse_colorant(::ColorTypes.Colorant{T,N}) at E:\for_programs\julia_pkgs\v0.5\Compose\src\Compose.jl:64
  parse_colorant(::AbstractString) at E:\for_programs\julia_pkgs\v0.5\Compose\src\Compose.jl:65
 in Gadfly.Guide.ManualColorKey{C<:ColorTypes.Color}(::String, ::Array{String,1}, ::Array{String,1}) at E:\for_programs\
julia_pkgs\v0.5\Gadfly\src\guide.jl:488
`

**Comment by bjarthur** [comment]
try checking out master of Compose.  if that works, i'll tag a new release of it.

**Comment by xqrongm** [comment]
I did `Pkg.clone("https://github.com/GiovineItalia/Compose.jl.git")` and it worked. Thanks.

**Comment by bjarthur** [comment]
fixed by https://github.com/GiovineItalia/Gadfly.jl/commit/0f7c590340ade4c5a0ad79996afd9aafe8590d95
