### ISSUE TITLE
alter travis to *not* checkout Compose

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#1007]
the travis yml currently checks out master on Compose before testing Gadfly.  this has recently caused a couple of problems to be experienced by users that where not caught by the automated tests.  i'd suggest removing it, but am curious why it was put there in the first place.

**Comment by tlnagy** [comment]
I think it was adopted when Compose was split out of Gadfly. The two projects always moved in lockstep and as long as changes to Compose are tagged whenever changes in Gadfly are tagged it's okay. Basically, I think it was done for convenience.

**Comment by bjarthur** [comment]
the problem arose precisely when i didn't think to tag Compose when tagging Gadfly.

it seems to me that developers will have master checked out on both, and so will know when testing locally whether the master branches are compatible.  i'm hence inclined to think that travis should *not* checkout master on Compose, so that the automated testing makes sure it works for users who don't have master checked out.

i hesitate though because even that is not fool proof:  if Compose is tagged, there is no automated test to make sure that the tagged or even master branch of Gadfly works with it.  not sure what to do about that case other than to try and remember to test Gadfly locally when tagging Compose.

**Comment by aviks** [comment]
Given the relationship between Gadfly and Compose, this is the best possible situation right now. We just have to remember to tag Compose and Gadfly together, always. They should have the same version number always, that makes things easier to track and trace. 

Longer term, if and when the API of Compose stabilises, we can do something different. But right now, leaving things as is seems to be the path of least resistance.
