### ISSUE TITLE
labels argument in Scale.x_discrete gives error for Geom.histogram and Geom.bar

### ISSUE THREAD

**Issue by Wedg** [GiovineItalia/Gadfly.jl#1009]
The plot command

```julia
plot(x = 1:12, y = rand(12), Scale.x_discrete(labels = d -> Dates.monthname(d)), Geom.point)
```
produces this chart (as expected)
![image](https://cloud.githubusercontent.com/assets/8735697/26520446/002aaae0-42d3-11e7-9c99-80105304c4cd.png)

But changing to Geom.bar i.e.
```julia
plot(x = 1:12, y = rand(12), Scale.x_discrete(labels = d -> Dates.monthname(d)), Geom.bar)
```
returns this error:

```
BoundsError: attempt to access 12-element Array{Int64,1} at index [0]
```

The same error is given for Geom.histogram when attempting to use the `labels` argument in `Scale.x_discrete`.

I am running Julia version 0.5.0 on Windows and Gadfly version 0.6.1.

**Comment by bjarthur** [comment]
works for me on julia 0.6 on os x and gadfly master

**Comment by Wedg** [comment]
Thanks Ben.
Time for me to move to 0.6.

**Comment by bjarthur** [comment]
@Wedg if this issue is resolved for you could you please close it?  thx

**Comment by Wedg** [comment]
Sorry. Tested on 0.6 and working. Closing issue.
