### ISSUE TITLE
Discrete Plots - Feature Request

### ISSUE THREAD

**Issue by xave** [GiovineItalia/Gadfly.jl#1011]
Is there a way to add a Discrete Plot type? In essence, for all points, your plot consists of a point and a vertical line from the x-axis to that point.  Like [this image](http://148.204.81.206/matlab/ref/stem_6.png).

Here's some hacked together code: 

`x = collect(0:9)`
`y = x.^2`

`discreteplot(x,y) =` 
    `    plot(layer(x=x, y=y, Geom.point),`
         `        layer(x=x, y=0*y, xend=x, yend=y, Geom.segment))`

`discreteplot(x,y)`

**Comment by dcjones** [comment]
It's maybe not super elegant, but possible.

```julia
xs = 1:10
ys = [x^2 for x in xs]
plot(x=xs, xend=xs, y=ys, yend=zeros(length(ys)), Geom.point, Geom.segment)
```

![tmp](https://user-images.githubusercontent.com/210361/27301778-56178072-54e9-11e7-81f9-54f21f7c9bf0.png)

**Comment by xave** [comment]
The motivation for wanting it is that it's a nice digital signal processing visualization.

**Comment by bjarthur** [comment]
added by https://github.com/GiovineItalia/Gadfly.jl/pull/1076
