### ISSUE TITLE
Switch to attobot for releases?

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1016]
@bjarthur and @dcjones, what do you all think of using [attobot](https://github.com/attobot/attobot) for Gadfly/Compose releases? Seems to be what most projects are transitioning to and would be more convenient than the current setup.

**Comment by bjarthur** [comment]
is Pkg3 supposed to fix any of the problems with Pkg2 that motivated the development of attobot?  if so, we could just wait for it.  when is it supposed to be released?

**Comment by tlnagy** [comment]
I think that's a separate issue. My understanding is that attobot takes tagged version of a package (e.g. Gadfly) and submits them for release to METADATA.jl, avoiding the fragile `Pkg.publish` process. I expect that Pkg3 will change METADATA.jl and the downstream workflow on the user side. Regardless, many packages are using attobot now and I'm pretty certain that it will be updated for any major workflow changes.

**Comment by timholy** [comment]
Keep in mind that setting up attobot is ~15 seconds of work. Making your first release with it is ~1min. I suggest just giving it a try and seeing whether you like it; you can turn it off with the click of a button, so it's not an irrevocable decision.

**Comment by bjarthur** [comment]
thanks @timholy .   still wondering though, am i right in thinking that Pkg3 will nominally obviate attobot?

**Comment by timholy** [comment]
Perhaps. But even if Pkg3 makes it easier I might just keep using attobot.

**Comment by aviks** [comment]
When Pkg3 is released, attobot will be changed to support it. Most people like the attobot flow, and so it will remain. Separately, Pkg3 is not likely to be in widespread use for at least a few more months. 

Lets get attobot enabled on these repos.

**Comment by bjarthur** [comment]
gadfly and compose ideally need to be simultaneously tagged and published because of their tight coupling.  does attobot support this?

**Comment by Mattriks** [comment]
Closing this since attobot has been disabled (https://github.com/attobot/attobot),
