### ISSUE TITLE
Feature Request: Make Plot padding configurable

### ISSUE THREAD

**Issue by silvanheller** [GiovineItalia/Gadfly.jl#1018]
Issue #654 brought this up, but was closed without discussion / reason. 
Currently, you can only pad the whole plot in all directions equally using _plot_padding_ -> [documentation](http://gadflyjl.org/stable/man/themes.html). It would be nice to have _xtop_, _xbottom_, _ytop_ and _ybottom_ options for plot padding. This is especially the case when working with String labels which can be cut off if they are on the last tick.

**Comment by bjarthur** [comment]
i'd be happy to review a pull request.  at first glance it seems straightforward enough for someone new to Gadfly's internals to tackle.  would just need to add a few fields to `Theme` [here](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/theme.jl#L96), and then use them when rendering [here](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/Gadfly.jl#L758).

**Comment by bjarthur** [comment]
fixed with https://github.com/GiovineItalia/Gadfly.jl/pull/1081#issuecomment-355653730
