### ISSUE TITLE
Both Gadfly and Base export "cross"

### ISSUE THREAD

**Issue by YingboMa** [GiovineItalia/Gadfly.jl#1019]
```
julia> using Gadfly

julia> cross
WARNING: both Gadfly and Base export "cross"; uses of it in module Main must be qualified
ERROR: UndefVarError: cross not defined
```

Is it possible to rename `Gadfly.cross` function?

**Comment by bjarthur** [comment]
to what would you suggest?

**Comment by YingboMa** [comment]
I actually have no idea. :laughing: Could you come up with one?

**Comment by tlnagy** [comment]
Maybe call the Gadfly one `plussign`? The other option is to export all of Gadfly's shapes in a submodule so you'll have call Gadfly.Shape.Cross (like we do for Geoms or for Guides), which would prevent the conflict with Base.

**Comment by ehdiix** [comment]
Is this issue still open?

**Comment by bjarthur** [comment]
`plussign` is reasonable, but then should we rename `xcross` as well?

despite being more verbose, creating a `Shape` submodule is probably the right way to go.
