### ISSUE TITLE
All points removed when toggling off first series in an interactive plot

### ISSUE THREAD

**Issue by johnallison0** [GiovineItalia/Gadfly.jl#1022]
Creating a plot that opens in a web browser has interactively, where it is possible to toggle on/off the different series. However, when toggling off the first series listed all of the points are removed from all series. The lines will remain though. Toggling the other entries will remove their line but not the points.

The following code from the Gadfly tutorial can be used to reproduce the issue:
```julia
using Gadfly
using RDatasets

gasoline = dataset("Ecdat", "Gasoline")

plot(gasoline, x=:Year, y=:LGasPCar, color=:Country,
         Geom.point, Geom.line)
```
Here is the default image generated:
![all_series](https://user-images.githubusercontent.com/25298104/28416033-3c416ed2-6d4a-11e7-9b17-ed9b3a6ba148.png)

With the first series deselected:
![series_1_deselected](https://user-images.githubusercontent.com/25298104/28416043-45dd7ad0-6d4a-11e7-8108-fdc559167246.png)

With a different series deselected:
![other_series_deselected](https://user-images.githubusercontent.com/25298104/28416048-503b7a54-6d4a-11e7-952d-dbdba90a3e52.png)

I believe the behaviour should be that when a series is deselected its points and line are removed, but the other series' points and lines should remain.

**Comment by bjarthur** [comment]
cool!  i didn't know it was possible turn lines on/off interactively.  we should document that, and fix it.  do you happen to know javascript?  that's how it works.  javascript embedded in svg.

**Comment by johnallison0** [comment]
It seems that the interactivity like panning, zooming, toggling is powered by [Snap.svg](http://snapsvg.io/), which is a javascript library for SVG files. So either the way Gadfly calls this library or the library itself may be causing the issue.

I've tried a few more permutations of plots, and the issue only appears when there are points. The same figure produced without the `Geom.point` option allows for the toggling to work as expected.

**Comment by bjarthur** [comment]
since it works for lines and not points, could probably figure out what the problem is by comparing how the two relevant code sections deal with svg:

https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/line.jl#L125
https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/point.jl#L52

**Comment by bjarthur** [comment]
please try https://github.com/GiovineItalia/Gadfly.jl/pull/1028 and let me know if this fixes interactive keys for you.  one thing to note is that labels with periods in them don't work as that is a special symbol in snap-svg.  not sure what to do about it.
