### ISSUE TITLE
Warning Messages

### ISSUE THREAD

**Issue by jacksaarden** [GiovineItalia/Gadfly.jl#1029]
I used Gadfly today and recieved a number of warning messages.   So, I thought I would submit.  If these are already being addressed, forgive the duplication.

Thanks,  Like the package

Last login: Fri Aug  4 13:53:40 on ttys001
Aaron-Jacksons-iMac:~ Aaron$ exec '/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating Homebrew master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Gadfly
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.6/Compat.ji for module Compat.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.6/GZip.ji for module GZip.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.6/Gadfly.ji for module Gadfly.
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:339
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:339
WARNING: Compat.UTF8String is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:339
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:365
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:365
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:365
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:365
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/property.jl:365
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/svg.jl:141
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/svg.jl:141
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/svg.jl:141
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Users/Aaron/.julia/Compose/src/svg.jl:141

julia>

**Comment by bjarthur** [comment]
those are fixed by https://github.com/GiovineItalia/Compose.jl/commit/06c33bb7c8eb42374b4d45e392b2c803fa842e0a and https://github.com/GiovineItalia/Gadfly.jl/commit/9f1705ad1a242cdeec1e0d10d3aa5f6ceaa7d918.  should go away next time we tag and publish a release.  in the meantime you can checkout the master branch of Gadfly and Compose if they really bother you.  thanks for the feedback.
