### ISSUE TITLE
Problem of vline / hline

### ISSUE THREAD

**Issue by DJ-kim** [GiovineItalia/Gadfly.jl#1031]
There is a probelm for the vline and hline.

It seems working well, but when I plot with SVG.JS file, the position of Vline and Hline are changed as I zoom in or out the image. 

Please let me know if there is solution for this problem.
If not, this problem would be fixed.

**Comment by bjarthur** [comment]
fixed by https://github.com/GiovineItalia/Gadfly.jl/commit/9291f6c40682725617b628a51e8356b9adab00a6.  please checkout master and let me know if not.
