### ISSUE TITLE
Gadfly.jl broken on julia master, wants space before `for` in comprehensions

### ISSUE THREAD

**Issue by ViralBShah** [GiovineItalia/Gadfly.jl#1034]
This is the fix:
```
diff --git a/src/geom/polygon.jl b/src/geom/polygon.jl
index ac43928..18bc004 100644
--- a/src/geom/polygon.jl
+++ b/src/geom/polygon.jl
@@ -15,12 +15,12 @@ element_aesthetics(::PolygonGeometry) = [:x, :y, :color, :group]
 function polygon_points(xs, ys, preserve_order)
     T = (@compat Tuple{eltype(xs), eltype(ys)})
     if preserve_order
-        return T[(x, y)for (x, y) in zip(xs, ys)]
+        return T[(x, y) for (x, y) in zip(xs, ys)]
     else
         centroid_x, centroid_y = mean(xs), mean(ys)
         θ = atan2(xs - centroid_x, ys - centroid_y)
         perm = sortperm(θ)
-        return T[(x, y)for (x, y) in zip(xs[perm], ys[perm])]
+        return T[(x, y) for (x, y) in zip(xs[perm], ys[perm])]
     end
 end
```

**Comment by tlnagy** [comment]
You mean on julia master? Because Gadfly master seems to build fine on Julia 0.6

**Comment by bjarthur** [comment]
the space before comprehensions is not the only reason Gadfly won't compile on julia 0.7.  both Hiccup and Juno are dependencies and neither of them will precompile.  got to fix them first.

**Comment by ViralBShah** [comment]
@tlnagy Sorry I did mean julia master. 

@bjarthur I did file https://github.com/JunoLab/Hiccup.jl/issues/25
I think it went through after that fix and the one I reported here.

**Comment by bjarthur** [comment]
i've turned femtocleaner on for Gadfly and will let it fix this issue

**Comment by bjarthur** [comment]
closed by https://github.com/GiovineItalia/Gadfly.jl/pull/1036
