### ISSUE TITLE
Problem of compose

### ISSUE THREAD

**Issue by DJ-kim** [GiovineItalia/Gadfly.jl#1035]
I don't know why, compose doesn't work properly at julia 6. 

for example, compose(context(text(a,b," hi" )))  >> can't find function for text

but it works for ellipse but not for line, circle and so on.

also, Theme(point_shapes="")  this one not work.

I tired many time for Pkg.rm("Compose") and Pkg.add("Compose")

But the problem has not been solved. So stressful please answer for this problem.

julia> Pkg.status()
6 required packages:
 - Atom                          0.6.1
 - Cairo                         0.3.1
 - Compose                       0.5.3+             master
 - DataFrames                    0.10.1
 - FITSIO                        0.10.0
 - Gadfly                        0.6.3              11b9dc15 (dirty)

**Comment by bjarthur** [comment]
`compose(context(text(0,0," hi" )))` works for me.  what is your `a` and `b` set to?

 `Theme(point_shapes=[circle])` works for me.  did it ever work to set it to `""`?

why is your Gadfly dirty?  My Gadfly and Compose are both on master.

**Comment by DJ-kim** [comment]
a and b is just position. I think have a problem for julia version. If there is no problem from you, I will try to install whole things regarding it.

By the way, another porblem is that unfixed position of annotation.

Guide.annotation(compose(context(),ellipse(-ms+ms*1/5,-ms+ms*1/5,bx,by),fill("black"))),

After make ellipse, its size become larger when I zoom out and become smaller when I zoom in. Also, I wanna know wether I can fixed its position when I zoom in or out to see whenever.

Thank you.

**Comment by bjarthur** [comment]
> After make ellipse, its size become larger when I zoom out and become smaller when I zoom in.

this is a dup of https://github.com/GiovineItalia/Gadfly.jl/issues/816

please open separate issues for separate problems otherwise it is hard to keep track of them.
