### ISSUE TITLE
change the size of Geom.label

### ISSUE THREAD

**Issue by DJ-kim** [GiovineItalia/Gadfly.jl#1038]
http://gadflyjl.org/stable/lib/geoms/geom_label.html#Geom.label-1

Can I change the size of text in Geom.plot?

I used these this
 theme(major_label_font_size=15pt, minor_label_font_size=15pt)

But it only applied to label in x or y axis. not applied to the label in the text in plot ( besides points)

Is there any other method?

**Comment by bjarthur** [comment]
relevant code is [here](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/label.jl#L247).  try `Theme(point_label_font_size=...)`

**Comment by bjarthur** [comment]
if this works, could you please submit a PR updating the docs to mention [these three](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/theme.jl#L119) additional keyword arguments for `Theme`?  only [this file](https://github.com/GiovineItalia/Gadfly.jl/blob/master/docs/src/man/themes.md) would need to be changed.  thanks.
