### ISSUE TITLE
Trouble doing the tutorial

### ISSUE THREAD

**Issue by dijkstrah** [GiovineItalia/Gadfly.jl#1044]
Hi there,

I am on the following platform:

Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)

Doing this: 

plot(data::DataFrame, mapping::Dict, elements::Element...)

results in:

ERROR: TypeError: typeassert: expected DataFrames.DataFrame, got DataArrays.#data

**Comment by tlnagy** [comment]
```julia
plot(data::DataFrame, mapping::Dict, elements::Element...)
```

is the function definition in Julia and is not runnable. It tells you what order to provide variables in. Does the following code work for you? (Assuming you've already installed RDatasets):

```
using Gadfly
using RDatasets

iris = dataset("datasets", "iris")
p = plot(iris, x=:SepalLength, y=:SepalWidth, Geom.point);
```

**Comment by dijkstrah** [comment]
Ugh, newbie mistake here. I am just blindly copying all the monotype text from the web into my terminal. 

It works obviously. Case closed.

**Comment by tlnagy** [comment]
No worries. Glad to help.
