### ISSUE TITLE
Warning message and forever.

### ISSUE THREAD

**Issue by feierbach** [GiovineItalia/Gadfly.jl#1046]
Here is my Julia program. It works and I get the plot I want after a few minutes:
using Gadfly
u=[1.2,1.3,1.4]
v=[1.0,0.9,0.8]
plot(x=u,y=v,Geom.point)

but I also get zillions of these messages:
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /Applications/JuliaPro-0.6.0.1.app/Contents/MacOS/JuliaPro-Juno-0.6.0.1.app/Contents/Resources/julia_atom_0.6.0.1/packages/julia-client/script/boot.jl:303

Where's the ASCII string coming from, The plot labels x and y?

**Comment by feierbach** [comment]
Regarding the prior message, I'm teaching a course in Julia and wanted to show the simplest possible examples of using the features of the JuliaPro IDE

**Comment by feierbach** [comment]
Also, Gadfly would profit from specifying the types allowed for the plot arguments and the minimum required to form a DataFrame.

**Comment by feierbach** [comment]
Oops! Not all the messages were the same: The last one was followed by:
in render at /Applications/JuliaPro-0.6.0.1.app/Contents/Resources/pkgs-0.6.0.1/v0.6/Gadfly/src/geom/point.jl

**Comment by bjarthur** [comment]
no warnings for me using the non-Pro version of julia 0.6.0 and Gadfly master branch.  the Pro version presumably ships with the the latest stable version of Gadfly.

keep in mind that neither Julia nor Gadfly have reached 1.0 yet.  so warnings are inevitable when breaking changes are made.

i'm going to close this for now, but please re-open if you think there is still an issue.  you might contact the Pro support center and request they update their Gadfly version.

**Comment by feierbach** [comment]
Thanks @bjarthur,  Still would like to see gadfly.jl  docs specify args using Julia types, or range of types, where appropriate.
