### ISSUE TITLE
Interactively remove/add a category

### ISSUE THREAD

**Issue by matteosangiorgio** [GiovineItalia/Gadfly.jl#1049]
Code:
```
using Gadfly , DataFrames;
df = DataFrame( A = rand( 1:10 , 30 ) , B = rand( 1:10 , 30 ) , C = rand( ["P","Q"] , 30 ) , D = rand( ["X","Y","Z"] , 30 ) )
# Create a scatter plot using point geometry from the values in columns A and B, grouped by column C
plot( df , x = :A , y = :B , color = :C , Geom.point )
```

Result:
![image](https://user-images.githubusercontent.com/33374216/32406171-ccc446e6-c173-11e7-8535-0ae15633eaeb.png)
![image](https://user-images.githubusercontent.com/33374216/32406179-e050d9cc-c173-11e7-91a4-45787fd22750.png)
![image](https://user-images.githubusercontent.com/33374216/32406181-eb7a99c8-c173-11e7-93f5-30ed6f775038.png)
As you can see in the pictures, the red square adds/removes all the points (both red and yellow). The yellow square does not work.
I'm using Julia(0.6.0) and gadfly v"0.6.3"

**Comment by bjarthur** [comment]
please upgrade to 0.6.4 as this problem was fixed by https://github.com/GiovineItalia/Gadfly.jl/commit/bb8fa87c733e6de6b9792a2150c9892aceb8081b.
