### ISSUE TITLE
interactivity

### ISSUE THREAD

**Issue by jzicker** [GiovineItalia/Gadfly.jl#1055]
anyone know if there a way to click on a gadfly chart (point, bar, etc) and then react to that click.

**Comment by tlnagy** [comment]
Something like a mouse click event? AFAIK, all the interactivity is handled by snap.svg and there isn't any feedback to the Julia code. Maybe @bjarthur or @dcjones know?

**Comment by jzicker** [comment]
yes, mouse click event with some way of translating coordinates so I can know which part of chart was clicked on.

**Comment by bjarthur** [comment]
work in progress:  https://github.com/GiovineItalia/Gadfly.jl/pull/1037

**Comment by timholy** [comment]
Immerse.jl?

**Comment by jzicker** [comment]
Immerse.jl does everything i want and more.   You can close this one.  thanks Tim
