### ISSUE TITLE
Gadfly Test errors

### ISSUE THREAD

**Issue by sharabhs** [GiovineItalia/Gadfly.jl#1056]
I am on Win10 x86-64, and I successfully installed Gadfly but I am getting this error on Pkg.test. Git is already installed 

INFO: Testing Gadfly
ERROR: 
LoadError: 
could not spawn `git log -n 1`: no such file or directory (ENOENT)
Stacktrace:

 [1] 
_jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::Base.Filesystem.File, ::RawFD) at .\process.jl:360
 [2] #376 at .\process.jl:512 [inlined]
 [3] setup_stdio(::Base.##376#377{Cmd}, ::Tuple{RawFD,Base.FileRedirect,RawFD}) at .\process.jl:499
 [4] #spawn#375(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,Base.FileRedirect,RawFD}) at .\process.jl:511
 [5] 
(::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{RawFD,Base.FileRedirect,RawFD}) at .\<missing>:0
 [6] #spawn#372(::Nullable{Base.ProcessChain}, ::Function, ::Base.CmdRedirect, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:392
 [7] run(::Base.CmdRedirect) at .\process.jl:650
 [8] include_from_node1(::String) at .\loading.jl:576
 [9] include(::String) at .\sysimg.jl:14
 [10] process_options(::Base.JLOptions) at .\client.jl:305
 [11] _start() at .\client.jl:371
while loading C:\Users\shara\.julia\v0.6\Gadfly\test\runtests.jl, in expression starting on line 13
===============================[ ERROR: Gadfly ]================================

failed process: Process(`'C:\Users\shara\AppData\Local\Julia-0.6.1\bin\julia.exe' -Cx86-64 '-JC:\Users\shara\AppData\Local\Julia-0.6.1\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes 'C:\Users\shara\.julia\v0.6\Gadfly\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing CodecZlib v0.4.0
INFO: Removing Fontconfig v0.1.1
INFO: Removing RData v0.2.0
INFO: Removing RDatasets v0.2.0
INFO: Removing TranscodingStreams v0.4.0

**Comment by bjarthur** [comment]
dup of https://github.com/GiovineItalia/Gadfly.jl/issues/1039.  am working on a fix.  sorry i haven't had time to complete it.  for the time being, just comment out https://github.com/GiovineItalia/Gadfly.jl/blob/master/test/runtests.jl#L13

**Comment by sharabhs** [comment]
Sorry about that, I didn't notice that is already being worked on

**Comment by bjarthur** [comment]
can you please try https://github.com/GiovineItalia/Gadfly.jl/pull/1057 on your windows box?  the error you reported shouldn't be emitted anymore.  thanks.
