### ISSUE TITLE
Combining plots with differing number of points

### ISSUE THREAD

**Issue by crinders** [GiovineItalia/Gadfly.jl#1062]
I wanted to do something along the lines of 
`plot(layer(x=X[1:10],y=Y[1:10]), layer(x=X[IndexSet],y=Y[IndexSet]))`
where `length(IndexSet)` is less than 10. Gadfly dies with 
`MethodError: no method matching render(::Gadfly.Geom.Nil, ::Gadfly.Theme, ::Gadfly.Aesthetics)`
I experimented around and I find the same error anytime the layers have a differing numbers of points.

Is that intended behavior? I didn't see any mention of constraints of this nature in the documentation.

**Comment by bjarthur** [comment]
specifically adding `Geom.point` to each layer fixes this for me.  seemingly `plot` uses that as default, but not `layer`.

**Comment by crinders** [comment]
Thanks. That solved the problem for me. Am I the only one who thinks that is counterintuitive, though?

**Comment by tlnagy** [comment]
This is because `plot` creates a new layer with `Geom.point` as the default geometry if there are no layers present:

https://github.com/GiovineItalia/Gadfly.jl/blob/bd2a7145f3d7810f626e18a8cb788d34c357da47/src/Gadfly.jl#L391-L395

> Am I the only one who thinks that is counterintuitive, though?

I agree that we should be consistent here.
