### ISSUE TITLE
Dataframes v0.11 is out

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1065]
This is a pretty big change and we need make sure Gadfly works with it. I believe the main hangup right now is that RDatasets (which we use for tests) doesn't work with v0.11 until https://github.com/johnmyleswhite/RDatasets.jl/pull/48 merges.

Then we'll need to drop `DataArrays` from `REQUIRE` and peg the minimum version of `DataFrames` at v0.11 and fix any problems.

**Comment by va-andrew** [comment]
Plus one for this issue. We had to remove Gadfly from our workflow until it can coexist with the newer versions of `DataFrames` (it currently forces a downgrade when used with `Pkg`).

**Comment by tlnagy** [comment]
Looks like https://github.com/johnmyleswhite/RDatasets.jl/pull/48 is basically ready so we can bump our requirements once it's merged and a new release is tagged.

**Comment by tlnagy** [comment]
The work has moved to #1090

**Comment by andreasnoack** [comment]
I think this can be closed. Eventually, we might want to remove `DataArrays` as a dependency but it is not required.

**Comment by bjarthur** [comment]
happy to close this.  you've done great work @andreasnoack !  thanks for taking on this important issue.

re. `DataArrays`...  is it or is it not a dependency?  should be removed now from REQUIRE if not.

**Comment by andreasnoack** [comment]
There is still code left to handle `DataArrays` if passed to Gadfly but I don't think we use them for anything so I suspect that it can be removed. I might take a look at that later today.
