### ISSUE TITLE
What is purpose of format.jl?

### ISSUE THREAD

**Issue by djsegal** [GiovineItalia/Gadfly.jl#1070]
can't seem to find anything that latches onto it in the project:

+ https://github.com/GiovineItalia/Gadfly.jl/blob/10f90e4e356bff9b5c26cd4d4fe083578b652909/src/format.jl

----

it has a line that breaks in modern julia versions, i think:

+ https://github.com/GiovineItalia/Gadfly.jl/blob/10f90e4e356bff9b5c26cd4d4fe083578b652909/src/format.jl#L14

**Comment by tlnagy** [comment]
The code must've gotten orphaned during Gadfly's evolution. I removed the file in #1071 and we'll have to see whether the tests pass.
