### ISSUE TITLE
Feature Request: enable color mapping in Geom.violin

### ISSUE THREAD

**Issue by ferris-wufei** [GiovineItalia/Gadfly.jl#1072]
The color of `Geom.violin` is always lightblue regardless of the `color` option settings. It would be nice to enable color mapping. Thanks!!

**Comment by bjarthur** [comment]
use `Theme` thusly:

```
julia> using RDatasets

julia> plot(dataset("lattice", "singer"), x="VoicePart", y="Height", Geom.violin, Theme(default_color="red"))
```

**Comment by ferris-wufei** [comment]
@bjarthur Sorry, I didn't make it clear. Suppose I want to map `VoicePart` values to different colors.

```Julia
plot(dataset("lattice", "singer"), x="VoicePart", y="Height", color="VoicePart", Geom.violin)
```

Then I got this. The legend is working but plot shows the same color.

<img width="546" alt="2017-12-29 14 00 02" src="https://user-images.githubusercontent.com/15623440/34430500-bb84f6b6-eca0-11e7-83a8-28877442a842.png">
