### ISSUE TITLE
Feature Request: map `color` for Geom.violin

### ISSUE THREAD

**Issue by ferris-wufei** [GiovineItalia/Gadfly.jl#1074]
Sorry for duplicate but I cannot re-open the previous issue. https://github.com/GiovineItalia/Gadfly.jl/issues/1072

Suppose I want to map VoicePart values to different colors.

```Julia
using RDatasets
using DataFrames
using Gadfly

plot(dataset("lattice", "singer"), x="VoicePart", y="Height", color="VoicePart", Geom.violin)
```

Then I got this. The color for different x values should be different as in the legend.

<img width="546" alt="2017-12-29 14 00 02" src="https://user-images.githubusercontent.com/15623440/34430589-860fe634-eca1-11e7-8055-8c72e2648c1f.png">

**Comment by bjarthur** [comment]
see @dcjones [note](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/violin.jl#L14)

**Comment by bjarthur** [comment]
fixed with https://github.com/GiovineItalia/Gadfly.jl/pull/1081#issuecomment-355653730
