### ISSUE TITLE
Feature Request: Array argument for Scale.color_discrete_manual

### ISSUE THREAD

**Issue by ferris-wufei** [GiovineItalia/Gadfly.jl#1075]
Now to assign multiple colors I have to hard code like this:

```Julia
Scale.color_discrete_manual("#3C5488", "#00A087", "#E64B35", "#95A5A6", "#4DBBD5");
```

It should be easier to accept an array of color values. For example, when I generate much more colors using some rules, I have to hardcode every color again within `Scale.color_discrete_manual` for later use.

**Comment by Mattriks** [comment]
You can use the [...](https://docs.julialang.org/en/stable/manual/faq/#The-two-uses-of-the-...-operator:-slurping-and-splatting-1) operator:
```Julia
cs = ["red","purple","green"]
p = plot(x=1:12, y=rand(12), color=repeat(["a","b","c"], outer=4),
     Scale.color_discrete_manual(cs...))

```

**Comment by ferris-wufei** [comment]
@Mattriks Thanks.
