### ISSUE TITLE
fix order for Geom.violin

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1079]
I'm trying to create a violin plot from a DataFrame, with x=Col.index and y=Col.value. It works fine, except that the order of the columns is not preserved in the plot. Is there a way to fix the order? Thanks in advance!

**Comment by IgorDouven** [comment]
Adding Scale.x_discrete(levels=df.colindex.names) did the trick, where df is the name of the DataFrame I'm plotting. Might be good to have a bit more about this in the documentation.

**Comment by tlnagy** [comment]
We would be glad to merge a PR if you want to add an example to the docs!

**Comment by IgorDouven** [comment]
I'd be happy to do that, but I'm completely new to GitHub. Could someone else add the example below to the page http://gadflyjl.org/stable/lib/scales/scale_x_discrete.html#Scale.x_discrete-1?

`
# When plotting a `DataFrame`, preserve the order of the columns in the plot
using DataFrames
df = DataFrame(v1 = randn(10), v2 = randn(10), v3 = randn(10))
plot(df, x=Col.index, y=Col.value, Scale.x_discrete(levels=df.colindex.names))
`
