### ISSUE TITLE
error after upgrading to julia 0.6.2

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1082]
I upgraded Julia today and now Gadfly no longer loads. I'm getting the following error:

ERROR: InitError: error compiling __init__: could not load library "/Users/igor/.julia/v0.6/Homebrew/deps/usr/lib/libfontconfig.dylib"
dlopen(/Users/igor/.julia/v0.6/Homebrew/deps/usr/lib/libfontconfig.dylib, 1): image not found

Re-installing Gadfly (or Homebrew) did not help.

**Comment by IgorDouven** [comment]
After updating Cairo, the loading error disappeared, but I'm still not able to create plots. If I try to do that, I get this error:

ERROR: Fontconfig was unable to match font Fontconfig.Pattern("pt sans-12:familylang=en,en-us:stylelang=en,en-us:fullnamelang=en,en-us:slant=0:weight=80:width=100:pixelsize=12.5:hintstyle=3:hinting=True:verticallayout=False:autohint=False:globaladvance=True:dpi=75:scale=1:lang=en:fontversion=2147483647:embeddedbitmap=True:decorative=False:namelang=en:prgname=julia:symbol=False")

Re-installing Fontconfig did not help.

**Comment by tlnagy** [comment]
Are you still having this issue?

**Comment by IgorDouven** [comment]
No, sorry, got resolved after re-install and various package updates. I'm closing now.
