### ISSUE TITLE
Feature request: control over ordering of factors in stacked bar chart

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1091]
I have created a stacked bar chart and would like to reverse the order in which the factors appear in each bar. Is there an easy way to do this? If not, it would be nice to have an option like `Geom.bar(position=:stack, rev=true)`.

**Comment by bjarthur** [comment]
does it not work to reverse the order of the arguments to `plot` ?  `plot(y=reverse(ydata)...`

**Comment by IgorDouven** [comment]
That doesn't work in my case. I'm plotting a DataFrame, as follows `plot(df, x=:gen, y=:freq, color=:group, Geom.bar(position=:stack))`. I can't use `y=reverse(:Frequency)` -- that throws an error.

**Comment by Mattriks** [comment]
Like this?:
```Julia
using RDatasets
D = by(dataset("datasets","HairEyeColor"), [:Eye,:Sex], d->sum(d[:Freq]))
rename!(D, :x1, :Frequency)
palette = ["blue","brown","green","tan"] # Is there a hazel color?

pa= plot(D, x=:Sex, y=:Frequency, color=:Eye, Geom.bar(position=:stack),
    Scale.color_discrete_manual(palette...)
)
pb= plot(D, x=:Sex, y=:Frequency, color=:Eye, Geom.bar(position=:stack),
    Scale.color_discrete_manual(palette[4:-1:1]..., order=[4,3,2,1])
)
hstack(pa,pb)
```
![issue1091](https://user-images.githubusercontent.com/18226881/35493508-15908948-0508-11e8-93ab-e060f4bb8bc7.png)

**Comment by IgorDouven** [comment]
Wonderful! Thank you so much!

**Comment by Mattriks** [comment]
Note that `DataFrames` also has [Sorting](https://juliadata.github.io/DataFrames.jl/stable/man/sorting.html) features.

**Comment by bjarthur** [comment]
@Mattriks thanks for this!  i didn't know `color_discrete_manual` could be used it that way.  would be great to add this example to the manual if you have time.

@IgorDouven please close this issue if you need no further assistance.

**Comment by IgorDouven** [comment]
All very useful information -- thanks again. Agree with @Mattriks that it
would be good to have this in the manual. I'll close the issue when I'm
back home, later today.

2018-01-29 13:01 GMT+01:00 Ben Arthur <notifications@github.com>:

**Comment by IgorDouven** [comment]
A quick follow-up question: As can be seen in the plot produced by @Mattriks above, if one changes the order of the colors, the same happens with the key labels in the legend. Is there a way to independently control the two? I tried adding a legend manually, with `Guide.manual_color_key`, which does add the correct legend. Unfortunately, however, it appears alongside the 'wrong' legend. (So, if there is a way to make the automatically generated legend disappear, that would also be fine, but I couldn't find one; `key_position=:none` will leave neither legend in place.)

**Comment by bjarthur** [comment]
not sure, but... please leave this issue open until @Mattriks 's example is added to the docs.  i'll get to it eventually unless he or you beat me to it.

**Comment by tlnagy** [comment]
> Unfortunately, however, it appears alongside the 'wrong' legend. 

Yeah, this is known bug: https://github.com/GiovineItalia/Gadfly.jl/issues/940
