### ISSUE TITLE
Can't run tests locally without checking out Compose.jl to master

### ISSUE THREAD

**Issue by non-Jedi** [GiovineItalia/Gadfly.jl#1107]
https://github.com/GiovineItalia/Compose.jl/pull/278 hasn't made it into a
release yet, but
https://github.com/GiovineItalia/Gadfly.jl/blob/a5b01ff9eb472fd127ea5f352bf99daf111f229f/test/runtests.jl#L59
uses the `PGF` call without "optional" args.

This is probably fine, but it should be documented somewhere if it's expected
that you have master of Compose to do development on Gadfly.

**Comment by bjarthur** [comment]
definitely worth documenting that Compose master is needed when developing Gadfly.  we do already have a [development section](https://github.com/GiovineItalia/Gadfly.jl/tree/master/docs/src/dev) in the docs.  that would be the logical place.

**Comment by bjarthur** [comment]
fixed by #1116
