### ISSUE TITLE
fix colorkey example

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#1112]
the legend title is malformed [here](http://gadflyjl.org/latest/lib/guides/guide_colorkey.html#Examples-1).  it's supposed to be two lines but it's not.  i can't get multi-line text to work anywhere in SVG.  it that even possible?  if not, we should just change the example to use a single line.

**Comment by tlnagy** [comment]
Maybe @Mattriks knows?

**Comment by bjarthur** [comment]
fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/1124
