### ISSUE TITLE
make SVG interactivity work with Atom

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#1115]
anyone understand how the Juno interface works?

**Comment by Mattriks** [comment]
http://docs.junolab.org/latest/devdocs/communication.html ?

**Comment by bjarthur** [comment]
@pfitzseb has a nice [fix](https://github.com/JunoLab/Juno.jl/issues/125#issuecomment-378622805)

**Comment by bjarthur** [comment]
specifically, in src/Gadfly.js replace:

```
@render Juno.PlotPane p::Plot begin
    x, y = Juno.plotsize()
    set_default_plot_size(x*Gadfly.px, y*Gadfly.px)
    HTML(stringmime("text/html", p))
end
```

with:

```
function Juno.render(pp::Juno.PlotPane, p::Plot)
    x, y = Juno.plotsize()
    set_default_plot_size(x*Gadfly.px, (y-1)*Gadfly.px)
    w = Juno.Atom.blinkplot()
    Juno.Atom.Blink.body!(w, HTML(stringmime("text/html", p)))
end
```

**Comment by JianghuiDu** [comment]
My `Gadfly.js` doesn't have `@render` at all. Using `Julia 1.1.0`. Is there a fix?

**Comment by bjarthur** [comment]
sadly Gadfly still doesn't work with Juno.  see https://github.com/GiovineItalia/Gadfly.jl/issues/1256 for a possible solution.

**Comment by pfitzseb** [comment]
Should work once https://github.com/JunoLab/Atom.jl/pull/243 is merged. I was *sure* I'd tried that before and it didn't make a difference, but it does. Sorry for the false alarm in https://github.com/GiovineItalia/Gadfly.jl/issues/1256.

**Comment by bjarthur** [comment]
i can plot successfully, but the built-into-Gadfly interactivity still does not work.  specifically, while hovering in the plot plane one should be able to press "?" and get a help panel explaining that one can pan and zoom with various keys.

atom 1.43.0, julia 1.3, dev Gadfly

is there something that we need to add to Gadfly to make this work?

**Comment by bjarthur** [comment]
doh, it works as is with dev Atom.  thanks!
