### ISSUE TITLE
broken example in docs

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#1125]
@andreasnoack this [example](https://github.com/GiovineItalia/Gadfly.jl/blob/master/docs/src/lib/geoms/geom_ellipse.md) in the docs is broken, and the error messages are related to your dataframes PR.  could you please take a look?  thanks.

**Comment by bjarthur** [comment]
possibly related, [test/testscripts/labels.jl](https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/360991398) is throwing a MethodError regarding discretize_make_ia when run by travis but not locally.  any ideas?

**Comment by Mattriks** [comment]
& this example works in Gadfly 0.6.5, but is broken on master. Note that the species labels are in the expected order, but the plots don't match the labels (the top row is the default and is correct):
```Julia
iris = dataset("datasets", "iris")
sp = unique(iris[:Species])
Dhl = DataFrame(yint=[3.0, 4.0, 2.5, 3.5, 2.5, 4.0], Species=repeat(sp, inner=[2]) )

function plotxg(scalexg::Scale.DiscreteScale)
    plot(iris, xgroup=:Species,
        Geom.subplot_grid(
            layer( x=:SepalLength, y=:SepalWidth, Geom.point),
            layer(Dhl, xgroup=:Species, yintercept=:yint, Geom.hline(color="red", style=:dot) ),
            ),
    scalexg, 
    Theme(plot_padding=[0mm])
)
end

scales =    [Scale.xgroup(), Scale.xgroup(levels=["virginica","setosa","versicolor"]), Scale.xgroup(order=[3,1,2])]
plots = plotxg.(scales)

vstack(plots...)
```
![subplot](https://user-images.githubusercontent.com/18226881/38192518-a82e25ce-36b0-11e8-82ad-1dfe2bd27f35.png)

**Comment by andreasnoack** [comment]
Thanks for reporting these. I know what is going on in @bjarthur's two examples. I'll try to look into this tonight.

**Comment by Mattriks** [comment]
Also, same issue with `Scale.ygroup()`

**Comment by Mattriks** [comment]
Again, top row correct, but in the other 2 rows, the class labels get sorted correctly, but boxplots don't: 
```Julia
function plotsxd(scalexd::Scale.DiscreteScale)
    plot(mpg, x=:Class, y=:Hwy, Geom.boxplot, scalexd,
        Theme(plot_padding=[0mm]) )
end 

ux = sort(unique(mpg[:Class]))
scales = [Scale.x_discrete(), Scale.x_discrete(levels=ux), Scale.x_discrete(order=[4,1,2,5,6,7,3])]
plots = plotsxd.(scales)

 draw(PNG(6.6inch,7inch),vstack(plots...))
```
![boxps](https://user-images.githubusercontent.com/18226881/38197742-22bbef58-36cd-11e8-9806-0773609cd6ea.png)

**Comment by andreasnoack** [comment]
Okay. This is frustrating. At least part of the issue seems to be a dispatch but. So
```julia
julia> x = [2,1,3]
3-element Array{Int64,1}:
 2
 1
 3

julia> IndirectArrays.IndirectArray(x)
3-element IndirectArrays.IndirectArray{Int64,1,Array{Int64,1},Array{Int64,1}}:
 1
 2
 3
```
Wat! So which method is this?
```julia
julia> @which IndirectArrays.IndirectArray(x)
(::Type{IndirectArrays.IndirectArray})(A::AbstractArray) in IndirectArrays at /Users/andreasnoack/.julia/v0.6/IndirectArrays/src/IndirectArrays.jl:35
```
The methods is defined in https://github.com/JuliaArrays/IndirectArrays.jl/blob/3f9fc132eab83fe631ea36d19aa345bdb39ef573/src/IndirectArrays.jl#L35 so this should be
```julia
julia> IndirectArray{UInt8}(x, unique(x))
3-element IndirectArrays.IndirectArray{Int64,1,Array{UInt8,1},Array{Int64,1}}:
 2
 1
 3
```
It looks like https://github.com/JuliaArrays/IndirectArrays.jl/blob/3f9fc132eab83fe631ea36d19aa345bdb39ef573/src/IndirectArrays.jl#L31-L34 is getting called. If I split the method at line 35 into a one and two argument method then the issue goes away. @JeffBezanson is this a dispatch bug or am I missing something?

**Comment by andreasnoack** [comment]
I've tried to work around this issue in https://github.com/JuliaArrays/IndirectArrays.jl/pull/14 so part of the issue here should be fixed when we get a new release of `IndirectArrays`.

**Comment by andreasnoack** [comment]
I've figured out what is going on here. It is not a dispatch bug. There is a kind of ambiguity in the `IndirectArray` constructors that I'll need to resolve.

**Comment by andreasnoack** [comment]
The labels issue is because `RDatasets` now returns a `DataFrame` where the text column has element type `Union{String,Missing}` where it used to be just `String`. I'll have to add some methods to handle such unions.

**Comment by andreasnoack** [comment]
@Mattriks Is this ellipsis plot looking right
<img width="529" alt="skaermbillede 2018-04-04 kl 15 47 42" src="https://user-images.githubusercontent.com/505001/38311497-9e818f82-381f-11e8-81a3-65ada3959f20.png">

**Comment by Mattriks** [comment]
Great! - all the above errors have been fixed on master. Except for the [`Geom.bar` bottom plot](http://gadflyjl.org/latest/lib/geoms/geom_bar.html#Geom.bar-1) palette issue. The palette should be: `palette=["brown","blue","tan","green"]` now to match the eye color labels.
