### ISSUE TITLE
Add doc example of transparency with Geom.ribbon

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1126]
According to the documentation, it should be possible to make `Geom.ribbon` colors transparent by adding something like `Theme(lowlight_opacity=0.3)`. That does not appear to work however. This would be a great feature to have though.

**Comment by bjarthur** [comment]
indeed!  there is no mention of `lowlight_opacity` in src/geom/ribbon.jl.

this would be a *great* first-time contribution.  care to take a stab at fixing it?  all you would need to do is follow the model [here](https://github.com/GiovineItalia/Gadfly.jl/blob/78208d28f796789479a51cd6854ae45bbcb9ea9c/src/guide.jl#L54) of how to programmatically specify opacity, and apply it [here](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/ribbon.jl#L36) and [here](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/ribbon.jl#L64).

thanks for filing an issue.

**Comment by Mattriks** [comment]
From #611:
```Julia
Theme(lowlight_color=c->RGBA{Float32}(c.r, c.g, c.b, 0.2)) 
```

**Comment by IgorDouven** [comment]
@Mattriks Thanks, this worked! (Would be worth adding to the documentation, even if it's only a workaround.)

@bjarthur I'd love to contribute, but this kind of problem is really beyond me (though I'm hoping to get to the point where it wouldn't be).

**Comment by bjarthur** [comment]
let's leave this open until it's fixed.

**Comment by bjarthur** [comment]
thinking on this more...permitting the user to specify both `lowlight_opacity` and `lowlight_color` simultaneously would need some special consideration to handle the case where the latter included an alpha channel.  so the recommended course of action here i think is to just update the documentation to remove mention of the former and give an example of how to achieve the same effect with the latter.

**Comment by Mattriks** [comment]
I think `fillopacity()` will work for only svg e.g. compare
```Julia
# The plot panel uses fillopacity(Theme.panel_opacity)
p = plot(x=[-2,2], y=[2,-2], 
    Theme(panel_fill=colorant"orange", panel_opacity=0.5)
)
draw(PNG(3.3inch,3.3inch), p)
draw(SVG(3.3inch,3.3inch), p)
```
whereas the `lowlight_color` function will work for svg and png.
`lowlight_opacity` looks like code that someone thought about, but wasn't implemented.

**Comment by kleinschmidt** [comment]
As a general way of combining colors and alphas, why not use `Colors.coloralpha`? It just sets the alpha of whatever color you pass it, and promotes the type if necessary

```julia
julia> using Colors

julia> coloralpha(RGB(0.5, 0.5, 0.5))
RGBA{Float64}(0.5,0.5,0.5,1.0)

julia> coloralpha(RGB(0.5, 0.5, 0.5), 0.7)
RGBA{Float64}(0.5,0.5,0.5,0.7)

julia> coloralpha(RGBA(0.5, 0.5, 0.5, 1.0), 0.7)
RGBA{Float64}(0.5,0.5,0.5,0.7)

julia> c = Lab(RGB(0.2, 0.3, 0.4))
Lab{Float64}(31.579833005156537,-1.8639258539215886,-17.85083480738884)

julia> coloralpha(c, 0.7)
LabA{Float64}(31.579833005156537,-1.8639258539215886,-17.85083480738884,0.7)
```

That be a good basis for allowing an `alpha` aes, which I miss from ggplot...
