### ISSUE TITLE
tagging 0.7

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#1140]
would be good to tag a new release which fixes the dataframes problem.  are there any PRs we should merge before hand?

@Mattriks since https://github.com/GiovineItalia/Gadfly.jl/pull/1118 introduces a breaking change, would be good to do that now as otherwise we'd have to wait awhile.

@non-Jedi what is your time frame for https://github.com/GiovineItalia/Gadfly.jl/pull/1105 ?

i've been diligently working on https://github.com/GiovineItalia/Gadfly.jl/pull/1116, but that is something that could wait.

**Comment by non-Jedi** [comment]
backburner for me right now. Hope to get to it some time after May 10.

**Comment by tlnagy** [comment]
Lets leave this open for 24 hours and see if @Mattriks wants to get #1118 ready for this release. We should try and get these DataFrames fixes out ASAP.

**Comment by Mattriks** [comment]
There are two issues to do with IndirectArrays described in #1130, so those 2 things work in Gadfly 0.6.5 but not on master. Is there a plan to fix them?

Getting #1118 release-ready should be possible, I'll try to do it within a week.

**Comment by tlnagy** [comment]
I've been using master for the past couple weeks and it's performed well for me. I think that we need to tag and push it out because Gadfly is interfering with the rest of the dataframes ecosystem. We'll have to accept the regression on #1130 until @andreasnoack has a chance to look into it.

**Comment by bjarthur** [comment]
agreed.  specifically, see https://github.com/GiovineItalia/Gadfly.jl/issues/1144.

@andreasnoack please let us know your timeframe so we can decide whether to tag now or wait.  we appreciate all you work on the dataframes issue!

**Comment by bjarthur** [comment]
i'm inclined to tag this weekend unless someone convinces me it's a bad idea.

**Comment by aviks** [comment]
I would urge a tag, even with some regressions, as soon as possible. The dependence of Gadfly on old DataFrames has unfortunately caused a huge split, with many strange dependencies. 

Did you know for example, that if you install Gadfly, you cannot now install a new version of ZMQ? (The reasons are arcane, and honestly not the Gadfly developers problem, just an unfortunate side effect -- but still something that is very painful for many users).

**Comment by bjarthur** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/14746

**Comment by aviks** [comment]
Thanks!

**Comment by bjarthur** [comment]
close by https://github.com/JuliaLang/METADATA.jl/pull/14746
