### ISSUE TITLE
`run open` in `compare_examples.jl` should be `open_file`

### ISSUE THREAD

**Issue by ulysses4ever** [GiovineItalia/Gadfly.jl#1143]
Regarding the issue about `run open` in test suit [raised here](https://github.com/GiovineItalia/Gadfly.jl/pull/1142#issuecomment-385285067). `Gadfly.open_file` is nice, but Gadly is huge and so fast to load. Hence the question, do we want to do `using Gadfly` in test suit (`compare_examples.jl` specifically)? Or maybe we simply copy-paste the definition of `open_file` inside it?

**Comment by bjarthur** [comment]
how about splitting `open_file` out into src/open_file.jl and then in test/compare_examples.jl doing an `include(joinpath(@__DIR__,"..","src","open_file.jl"))` ?  a little kludgy, but better than duplicating code i think.  thoughts?  you'd need to add an include to Gadfly.jl as well.

**Comment by ulysses4ever** [comment]
I like your idea. Will do.

**Comment by bjarthur** [comment]
did you want to rename to `devel-output` and `master-output` as you [suggested](https://github.com/GiovineItalia/Gadfly.jl/pull/1142#issuecomment-385342892)?

**Comment by ulysses4ever** [comment]
Yeah, I can try that this week.
ср, 23 мая 2018 г. в 22:30, Ben Arthur <notifications@github.com>:

**Comment by ulysses4ever** [comment]
Here we go: #1154.
