### ISSUE TITLE
Use DocStringExtensions in Gadfly

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1161]
[`DocStringExtensions.jl`](https://github.com/JuliaDocs/DocStringExtensions.jl) is a really nice self-contained package that allows us to have much more flexible and dynamic docstrings. I'm very wary of adding more dependencies to Gadfly, but this package would add no subdependencies (it only depends on `Compat` and `Base`). A couple examples of where we can leverage it:

1) By using the automatically generated function signatures in the docstrings (so they don't get out sync) with the actual functions

2) By unrolling the fields in a type (see https://github.com/GiovineItalia/Gadfly.jl/pull/1157/files#diff-9ec506bf78232ae17d082c22c2e66449R507). Currently, all those docs are hidden when you do
`?Gadfly.Stat.density`, but could be unrolled with `DocStringExtension.jl`

Thoughts?

**Comment by bjarthur** [comment]
auto-gen'd sigs sounds great, but where besides #1157 are docs embedded in typedefs?

**Comment by bjarthur** [comment]
i can see the value in DocStringExtensions. https://github.com/GiovineItalia/Gadfly.jl/pull/1173 proposes to use it.

**Comment by tlnagy** [comment]
Since it seems like we're generally onboard with using it, I'll go ahead and close this
