### ISSUE TITLE
manual_color_key with non-unique colours throws unhelpful error

### ISSUE THREAD

**Issue by CiaranOMara** [GiovineItalia/Gadfly.jl#1170]
Using manual_color_key with non-unique colours throws the following unhelpful error.

```
BoundsError: attempt to access 1-element Array{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},1} at index [1:2]
macro expansion at dynamic.jl:67 [inlined]
(::Atom.##99#104)(::Dict{String,Any}) at eval.jl:74
handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N} where N) at comm.jl:163
(::Atom.##11#13)() at event.jl:73
```

It took me a while to establish that the cause of this error was effectively due to the following generated code.

```julia
Guide.manual_color_key(legend_title, ["h", "Smooth"], ["black", "black"]),
```

In this case, I think it would be useful if Gadfly contained a sanity check.

**Comment by tlnagy** [comment]
The key question is whether `Guide.manual_color_key` should always require uniqueness. It appears that we already assume that this is the case so I think making this a proper error wouldn't change anything. We can probably move the creation of the color=>label mapping dict from here: 
https://github.com/GiovineItalia/Gadfly.jl/blob/f922f4d137a84cc9ff38e3cbd3b01847ca5b0a7e/src/guide.jl#L528-L531
to the constructor:
https://github.com/GiovineItalia/Gadfly.jl/blob/f922f4d137a84cc9ff38e3cbd3b01847ca5b0a7e/src/guide.jl#L498-L499

**Comment by CiaranOMara** [comment]
@tlnagy, thank you.
