### ISSUE TITLE
Boxplot doesn't seem to work for defined upper_fence, etc

### ISSUE THREAD

**Issue by GantZA** [GiovineItalia/Gadfly.jl#1179]
I'm trying to plot some OHLC stock data using the boxplot and defining the upper_fence, upper_hinge myself. However, it just seems to plot a horizontal boxes along the y=x axis and the y-axis doesnt even show the correct numbers.

I then tried an example I found in a previous issue

```
x = collect(1:10)
a = x.*3+4
b = a-1
c = a-2
d = a-3
     
df = DataFrame(x = x,a=a,b=b,c=c,d=d,s = repmat(["A"],10))
p = plot(df,x="x",upper_fence="a",upper_hinge="b",lower_hinge="c",lower_fence="d", Geom.boxplot, color="s")
```

but I just get these small flat boxes along the y=x line

**Comment by Mattriks** [comment]
The trick here is to add `Stat.identity`
```julia
p = plot(df, 
    layer(x=:x, upper_fence=:a, upper_hinge=:b, lower_hinge=:c, lower_fence=:d, 
    Geom.boxplot, Stat.identity )
)
```
so here `Geom.boxplot` calls `Stat.identity` rather than `Stat.boxplot`.

@tlnagy, @bjarthur this should be easy to fix, using a constructor like `Geom.basicbox` which calls `Stat.identity`

**Comment by tlnagy** [comment]
> this should be easy to fix, using a constructor like `Geom.basicbox` which calls `Stat.identity`

Not sure this requires a whole new geom, but I think your example could be valuable in the docs. This is a great example of grammar of graphics style.

**Comment by GantZA** [comment]
Thanks for the help, the boxes are now plotting correctly, but not the best scale. My use case at the moment is to make a candlestick plot for OHLC data and I've been able to do it using the TimeSeries.jl and Plots.jl packages with argument `seriestype =:candlestick`. 

![candle1](https://user-images.githubusercontent.com/34217244/44275777-ea2c1200-a245-11e8-9f0e-63f52ecd2f09.PNG)


I'd like to get the same result using Gadfly as I still need to add extra points to the plots and I know how to this using layers in Gadfly, but I can't seem to do it as easily using the Plots.jl package. Below is the same data but using Gadfly and you can see how the scaling isn't correct, and I don't know how to change it.

![candle2](https://user-images.githubusercontent.com/34217244/44275869-2f504400-a246-11e8-8837-9d7b46c7510e.PNG)


```
plot(df_ten_min_bar_NPN,  Guide.yticks(ticks = collect(300000:10000:400000)),
    layer(x=:timestamp, upper_fence=:high, upper_hinge=:open, lower_hinge=:low, lower_fence=:close, 
    Geom.boxplot, Stat.identity))
```

**Comment by GantZA** [comment]
Thank you @Mattriks that works perfectly. 
![candle3](https://user-images.githubusercontent.com/34217244/44288204-ca114880-a26f-11e8-9f4b-fae454672178.jpg)

**Comment by bjarthur** [comment]
the problem with the code is that `Stat.boxplot` computes the hinges and fences if `y` is defined, and that Gadfly will automatically call `Stat.yenumerate` (before calling `Stat.boxplot`) to define `y` if it is missing.

this error was never caught because all of the boxplot tests provide `y` and not the hinges or fences.

an alternative to creating a basicbox geom would be to change the logic of `Stat.boxplot` to compute the hinges and fences if they are not defined instead of `y` being defined.


@GantZA could you please provide us with the raw data?  i'd like to look into why the scale was not set well.

**Comment by GantZA** [comment]
I've attached the OHLCV data I was using, heres the code:

```
ymin = minimum(df_ten_min_bar_NPN_vwp[5])*0.99
ymax = maximum(df_ten_min_bar_NPN_vwp[3])

plot(df_ten_min_bar_NPN_vwp, Coord.cartesian(ymin=ymin, ymax=ymax), Scale.y_continuous(format=:plain),
    layer(x=:timestamp, upper_fence=:high, upper_hinge=:open, lower_hinge=:close, lower_fence=:low,
    Geom.boxplot, Stat.identity, color = :colour))
```


[ohlcv_sample.zip](https://github.com/GiovineItalia/Gadfly.jl/files/2298837/ohlcv_sample.zip)
