### ISSUE TITLE
Failed to precompile Compose

### ISSUE THREAD

**Issue by hajsf** [GiovineItalia/Gadfly.jl#1195]
I got the below error while working with Julia 1.0:

> julia> using Gadfly
> [ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]
> ERROR: LoadError: syntax: try without catch or finally
> Stacktrace:
>  [1] include at ./boot.jl:317 [inlined]
>  [2] include_relative(::Module, ::String) at ./loading.jl:1038
>  [3] include(::Module, ::String) at ./sysimg.jl:29
>  [4] top-level scope at none:2
>  [5] eval at ./boot.jl:319 [inlined]
>  [6] eval(::Expr) at ./client.jl:389
>  [7] top-level scope at ./none:3
> in expression starting at /Users/hasan/.julia/packages/Compose/y7cU7/src/Compose.jl:207
> ERROR: LoadError: Failed to precompile Compose [a81c6b42-2e10-5240-aca2-a61377ecd94b] to /Users/hasan/.julia/compiled/v1.0/Compose/sbiEw.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] macro expansion at ./logging.jl:313 [inlined]
>  [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
>  [4] _require(::Base.PkgId) at ./logging.jl:311
>  [5] require(::Base.PkgId) at ./loading.jl:852
>  [6] macro expansion at ./logging.jl:311 [inlined]
>  [7] require(::Module, ::Symbol) at ./loading.jl:834
>  [8] include at ./boot.jl:317 [inlined]
>  [9] include_relative(::Module, ::String) at ./loading.jl:1038
>  [10] include(::Module, ::String) at ./sysimg.jl:29
>  [11] top-level scope at none:2
>  [12] eval at ./boot.jl:319 [inlined]
>  [13] eval(::Expr) at ./client.jl:389
>  [14] top-level scope at ./none:3
> in expression starting at /Users/hasan/.julia/packages/Gadfly/p8TXc/src/Gadfly.jl:7
> ERROR: Failed to precompile Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004] to /Users/hasan/.julia/compiled/v1.0/Gadfly/DvECm.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] macro expansion at ./logging.jl:313 [inlined]
>  [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
>  [4] macro expansion at ./logging.jl:311 [inlined]
>  [5] _require(::Base.PkgId) at ./loading.jl:941
>  [6] require(::Base.PkgId) at ./loading.jl:852
>  [7] macro expansion at ./logging.jl:311 [inlined]
>  [8] require(::Module, ::Symbol) at ./loading.jl:834

**Comment by tlnagy** [comment]
Please use Gadfly master on Julia 1.0:

```julia
julia> using Pkg
julia> pkg"add Compose#master"
julia> pkg"add Gadfly#master"
```

We're going to tag a stable release with Julia 1.0 support soon.

**Comment by tlnagy** [comment]
Please open a new issue if you run into any problems with Compose/Gadfly on Julia 1.0.
