### ISSUE TITLE
Precompiling Gadfly failed

### ISSUE THREAD

**Issue by joytrust0609** [GiovineItalia/Gadfly.jl#1196]
I guess the error is "missing catch or finally".
enviroment: julia v1.0.0
OS: win 10 Pro v1803 17134.285

![default](https://user-images.githubusercontent.com/20922321/45797259-5384c200-bcd7-11e8-8e3a-aa76b44e1207.png)

**Comment by tlnagy** [comment]
The latest tagged release don't support Julia 1.0, but the latest master does. Try running

```julia
julia> using Pkg
julia> pkg"add Compose#master"
julia> pkg"add Gadfly#master"
```

and try again.

**Comment by joytrust0609** [comment]
it works
thank u for replying soooo quick! thumb

**Comment by tlnagy** [comment]
Cool, enjoy! Open a new issue if you run into any bugs
