### ISSUE TITLE
diagonal line to work on log scale

### ISSUE THREAD

**Issue by SimonEnsemble** [GiovineItalia/Gadfly.jl#1200]
I'm a huge fan of the diagonal line functionality.

For a scatter plot on a log scale, it doesn't seem to function. No diagonal line shows up with the following code.

```julia
using Gadfly, RDatasets, Compose
set_default_plot_size(14cm, 8cm)
plot(dataset("ggplot2", "mpg"),
     x="Cty", y="Hwy", label="Model", Geom.point, Geom.label,
     Scale.x_log10, Scale.y_log10,
     intercept=[0.0], slope=[1], Geom.abline(color="red", style=:dash),
     Guide.annotation(compose(context(), text(6,4, "y=x", hleft, vtop), fill("red"))))
```

**Comment by bjarthur** [comment]
as documented:  "This geometry currently does not support non-linear Scale transformations." in http://gadflyjl.org/latest/lib/geometries.html#Gadfly.Geom.abline

would happily review a PR to fix this.

in general though, my experience is that there is not a single plotting package out there, for julia, python, or matlab, that handles scale transformations well.  for my work i have almost always simply taken the log of the data myself.

**Comment by Mattriks** [comment]
Here's another example, using a log-linear model:
```
Random.seed!(123)
 x = 15*rand(20)
 D = DataFrame(x=x, y= exp.(-0.2*x.+3.03) .+ 0.2*randn(length(x)))

abline = Geom.abline(color="red", style=:dash)

pa = plot(D, x=:x, y=:y,  Geom.point, Scale.y_continuous,
      intercept=[21], slope=[-0.2],  abline )
pb = plot(D, x=:x, y=:y,  Geom.point, Scale.y_log,    
     intercept=[21], slope=[-0.2], abline )

draw(PNG(3inch,3inch), pa)
# draw(PNG(3inch,3inch), pb) # fails 
```
![iss1200a](https://user-images.githubusercontent.com/18226881/46348636-f1429e80-c692-11e8-8ea8-4665624fc5b2.png)
Plot a) works, and plot b) fails: but this is easy to fix, and I'll submit a PR soon.
