### ISSUE TITLE
New Julia 1.0 compatible release?

### ISSUE THREAD

**Issue by mohamed82008** [GiovineItalia/Gadfly.jl#1203]
Hi,

When is the new release for Julia 1.0 expected to come out? Any blocking issues?

**Comment by bjarthur** [comment]
the master branch works on 1.0.  we could tag it, but there are regressions when rendering text, as pango support currently doesn't work.

**Comment by mohamed82008** [comment]
Tagging a version would be useful for me. Fixing regressions can be done in minor releases, if you are ok with that.

**Comment by bjarthur** [comment]
it's really not that inconvenient to use master.  just install with `]add Gadfly#master` instead of `]add Gadfly`.

**Comment by tlnagy** [comment]
A 1.0 release is imminent, see #1192

**Comment by tlnagy** [comment]
The latest release supports Julia 1.0: https://github.com/GiovineItalia/Gadfly.jl/releases/tag/v1.0.0
