### ISSUE TITLE
v1.01, support Gadfly ?

### ISSUE THREAD

**Issue by lamhoson** [GiovineItalia/Gadfly.jl#1209]
(JuliaPro_v1.0.1.1) pkg> add Gadfly
ERROR: The following package names could not be resolved:
 * Gadfly (not found in project, manifest or registry)
Please specify by known `name=uuid`.

**Comment by tlnagy** [comment]
A 1.0 compatible release is imminent (https://github.com/GiovineItalia/Gadfly.jl/issues/1192). In the mean time, try running `Pkg.update` and then `add Gadfly#master`

**Comment by lamhoson** [comment]
Tried but following errors:


(JuliaPro_v1.0.1.1) pkg> update
  Updating registry at `C:\Users\hoson\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\registries\JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com/registry/JuliaPro`
 Resolving package versions...
  Updating `C:\Users\hoson\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\environments\JuliaPro_v1.0.1.1\Project.toml`
 [no changes]
  Updating `C:\Users\hoson\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\environments\JuliaPro_v1.0.1.1\Manifest.toml`
 [no changes]


(JuliaPro_v1.0.1.1) pkg> add Gadfly#master
ERROR: The following package names could not be resolved:
 * Gadfly (not found in project, manifest or registry)
Please specify by known `name=uuid`.


(JuliaPro_v1.0.1.1) pkg>


发自网易邮箱 iPhone 版
On 10/17/2018 03:07，Tamas Nagy<notifications@github.com> wrote：

A 1.0 compatible release is imminent (#1192). In the mean time, try running Pkg.update and then add Gadfly#master

**Comment by tlnagy** [comment]
What about trying?

```
add https://github.com/GiovineItalia/Gadfly.jl
```

**Comment by lamhoson** [comment]
Thanks !  It can find the package now. 


But following errors come up and same case that i cannot add Compose, CoupledFields etc...
On 10/18/2018 03:46，Tamas Nagy<notifications@github.com> wrote：

What about trying?

add https://github.com/GiovineItalia/Gadfly.jl

**Comment by bjarthur** [comment]
does this work now that we have [tagged a release](https://github.com/JuliaLang/METADATA.jl/pull/18913)?  if so, please close this issue.  thanks.

**Comment by tlnagy** [comment]
This should be fixed with the latest tagged release so you should be able to run `] add Gadfly` and everything should work. Please open a new issue if this is not the case.
