### ISSUE TITLE
spy does not plot

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#1216]
Gadfly.spy(convert(Array{Float64,2}, rand(3)'))

this should produce a vector map. I think. It produces nothing.

**Comment by Mattriks** [comment]
Does this work for you?:
```
Gadfly.spy(rand(3)', Scale.y_discrete)
```

**Comment by montyvesselinov** [comment]
Yep! It does! Thank you!

-monty

**Comment by bjarthur** [comment]
does anything need to be done here?

**Comment by montyvesselinov** [comment]
This was fixed. Sorry.
