### ISSUE TITLE
subplot_grid not working with Scale

### ISSUE THREAD

**Issue by ptaitAtMcMaster** [GiovineItalia/Gadfly.jl#1218]
Hi, 
I am using Julia 1.0.1 with Gadfly v1.0.0

The following plot does not render with a Scale. 
`p1 = plot( filter(row -> row[:y] < 99, tmp_hb ), 
    ygroup =:c3, x=:x1, y=:y1,
    Scale.color_continuous(colormap=Scale.lab_gradient("blue", "white", "orange")),
    Geom.subplot_grid(Geom.hexbin)
)`
In Julia v 0.6, it would render with one scale for the entire plot (which is what I want).

`p1 = plot( filter(row -> row[:y] < 99, tmp_hb ), 
    ygroup =:c3, x=:x1, y=:y1,
    Geom.subplot_grid(Scale.color_continuous(colormap=Scale.lab_gradient("blue", "white", "orange")), Geom.hexbin)
)`
Produces one Scale per subplot, which is what I expected.

Is this a bug or am I missing something obvious. 
Thanks
Peter

**Comment by tlnagy** [comment]
Can you provide a minimal working example for us to reproduce? i.e. data -> script -> plot

**Comment by ptaitAtMcMaster** [comment]
Hi @tlnagy ,
thanks for getting back to me. Here is some code that illustrates the problem:
`
using DataFrames, Distributions, StatsBase, Random, Gadfly, Cairo

Random.seed!(825)

N = 50000

df1 = DataFrame(
  x1 = rand(Normal(1,3), N),
  x2 = [sample(["High", "Medium", "Low"],
              pweights([0.25,0.45,0.30])) for i=1:N],
  x3 = rand(Normal(2, 6), N)
 )

p1 = plot(df1, 
     x=:x1,  y=:x3,
    Scale.color_continuous(colormap=Scale.lab_gradient("blue", "white", "orange")),
    Geom.hexbin
)

p2 = plot(df1, 
    ygroup =:x2,  x=:x1,  y=:x3,
    Scale.color_continuous(colormap=Scale.lab_gradient("blue", "white", "orange")),
    Geom.subplot_grid(Geom.hexbin)
)
`
p1 looks as I would expect. p2 is missing the Scale labelled "count".
Any ideas why that is happening?
