### ISSUE TITLE
Line break not working in color key title

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1225]
Dear all,

I would like to add a line break in the title of the color key, but `\n` is not working anymore. Here is a MWE:
```
using Gadfly

Gadfly.spy(rand(50, 50), Guide.ColorKey(title="Some label"))
```
If I use `title="Some \n label"`, the title in the plot becomes 'Some'. Is this a known problem? Is there a workaround?

**Comment by bjarthur** [comment]
text is not going to work like it did previously until we [get pango fixed](https://github.com/GiovineItalia/Compose.jl/pull/312).

long term though we should work towards getting rid of non-julian dependencies.

in this particular case though, i'm not sure line breaks in SVG have ever worked.  your example works for PDF.

see http://giovineitalia.github.io/Compose.jl/latest/tutorial/#Text-1

**Comment by IgorDouven** [comment]
Thanks, you're right: PDF works fine. However, I can't use PDF because it makes the background black (even if I explicitly ask for a white background -- is this problem known?, should I open another issue?). My workaround is to export via SVG and then to use cairosvg in the command line to convert to a pdf file.

**Comment by Mattriks** [comment]
The background opacity issue was resolved on master (#1208). Did you do `Theme(background_color="white")` or `Theme(panel_fill="white"`)?

For the history of this issue see: https://github.com/GiovineItalia/Compose.jl/issues/322#issuecomment-433663628

**Comment by IgorDouven** [comment]
Thanks for pointing this out. I did the first. Using the second now and the problem is solved!

**Comment by tlnagy** [comment]
AFAIK, multiline text was never supported in Gadfly SVGs, probably because (as @Mattriks points out) it's not supported in the SVG1.x spec. I think we can add preliminary SVG2-esque features if Inkscape supports it and if it gracefully fails on SVG 1.x rendering engines.
