### ISSUE TITLE
How do I omit the Shapekey?

### ISSUE THREAD

**Issue by Shushman** [GiovineItalia/Gadfly.jl#1233]
This is probably an obvious one but I am unable to completely omit `Guide.shapekey`. I tried `Guide.shapekey(nothing)` as an argument, like with `Guide.xlabel(nothing)`, but I got unmatched argument errors. The closest I could get to was with `Guide.shapekey(;title="", labels=[""], pos=Float64[])` but that seems messy and also still retains the symbols and numbers.

**Comment by Mattriks** [comment]
Please provide the code of your plot statement, e.g. are you using more than one key? Did you try `Theme(key_position=:none)`?

**Comment by Shushman** [comment]
Oh that did it, thank you!

**Comment by jonathanBieler** [comment]
I don't think that really solves the issue because if you want a ColorKey and a ShapeKey then `key_position=:none` hides both. Maybe a `shape_key_position` parameter is needed. A workaround I found is to move the ShapeKey out of the plot

```julia
plot(
    layer(x=rand(10), y=rand(10), shape=rand(0:1,10), Geom.point),
    layer(x=rand(10), y=rand(10), shape=rand(0:1,10), Theme(default_color=colorant"red"), Geom.point),
    Guide.manual_color_key("",["A","B"],["deepskyblue","red"]),
#    Guide.shapekey("",[""],[-10cm,-10cm]),
)
```

**Comment by tlnagy** [comment]
I think the `key_position` code was developed prior to the inclusion of `shapekey` so we likely need to break up that parameter to into two separate ones. Thoughts, @Mattriks?

**Comment by Mattriks** [comment]
There is also `sizekey`, `alphakey` and `linekey` [tbd](http://gadflyjl.org/stable/tutorial/#Discrete-Scales-1).
There are at least 2 potential ways to switch off multiple keys:

1) `Guides.guide(color=nothing, shape=nothing, line=nothing)` (similar to ggplot's `guides()`)
2) `layer(x= , y= , color= , Theme(key_position=:none))`

Each way would be useful for different situations, so it would be good to implement both.
