### ISSUE TITLE
Docs aren't getting deployed?

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1241]
@bjarthur any ideas on why Travis is skipping doc deployment? https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/476704204

```
Documenter: populating indices.
Documenter: rendering document.
Documenter: skipping docs deployment.
```

**Comment by bjarthur** [comment]
https://github.com/GiovineItalia/Gadfly.jl/blob/master/.travis.yml#L34

**Comment by tlnagy** [comment]
http://gadflyjl.org/dev/ is out of date as well because there are some bugs in the plots that have been fixed on master, e.g. opacity in the [`Geom.ribbon`](http://gadflyjl.org/dev/gallery/geometries/#[Geom.ribbon](@ref)-1) is broken in the docs, but the exact same code works on master.

**Comment by tlnagy** [comment]
Line L34 in `.travis.yml` refers to after the docs have been deployed. Deployment should not be skipped. You can verify that at your previous link:

```
Documenter: skipping docs deployment.
Documenter: You can set DOCUMENTER_DEBUG to "true" in Travis to see more information.
...
Skipping the after_success step, as specified in the configuration.
```

**Comment by bjarthur** [comment]
cc @mortenpi can you please help with a travis doc deployment question?

**Comment by tlnagy** [comment]
I've started up the VM with the DOCUMENTER_DEBUG key set to true. Hopefully that'll give us a better idea of what is going on: https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/476704204

**Comment by mortenpi** [comment]
The build linked in the OP looks like a PR build for #1240, right? The PR builds are not supposed to deploy docs (among other reasons, they don't have access to `DOCUMENTER_KEY`).

The last build for the `master` branch deployed fine as far as I can tell: https://travis-ci.org/GiovineItalia/Gadfly.jl/builds/475701320

**Comment by tlnagy** [comment]
Ah, good catch. My bad. I wonder why the plots are broken in the documentation, but build fine locally on master. That's a separate problem and I'll open a separate issue for that.

**Comment by mortenpi** [comment]
Regarding plots, I didn't look into it, but could it be something similar to JuliaDocs/Documenter.jl#921?
