### ISSUE TITLE
Manual continuous color legend?

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1253]
It would be nice to be able to add a manual color key that is continuous. `Guide.manual_color_key` only support discrete color scales.

```julia
using Gadfly
using Distributions
using ColorSchemes
using Random

n = 1000
Random.seed!(1234)
xs = rand(Normal(0, 1), n)
ys = rand(Normal(0, 1), n)

x_t = cumsum(xs)
y_t = cumsum(ys)
colors = get(ColorSchemes.viridis, collect(1:n-1)./(n-1))

layers = []
for i in 1:n-1
    push!(layers, layer(x=x_t[i:i+1], y=y_t[i:i+1], Geom.line, Theme(default_color=colors[i], line_width=0.5mm)))
end
plot(layers..., Coord.cartesian(aspect_ratio=1.0))
```

![image](https://user-images.githubusercontent.com/1661487/52981476-e152ff00-3394-11e9-90b0-46dfe553f86a.png)

**Comment by Mattriks** [comment]
I would do the above plot like this:
```julia
x, y = cumsum(randn(n)), cumsum(randn(n))
D = DataFrame(x1=x[1:end-1], y1=y[1:end-1], x2=x[2:end], y2=y[2:end], colv=1:n-1)
palettef(c::Float64) = get(ColorSchemes.viridis, c)

p = plot(D, x=:x1, y=:y1, xend=:x2, yend=:y2, 
     color = :colv, Geom.segment, Coord.cartesian(aspect_ratio=1.0),
     Scale.color_continuous(colormap=palettef, minvalue=0, maxvalue=1000)
)
```

**Comment by tlnagy** [comment]
That's definitely a better way to make this plot, but my nascent feeling is that it could be useful to have a `Guide.manual_color_key` for continuous color scales too, since we have it already for discrete ones.

**Comment by Mattriks** [comment]
The intent of the grammar of graphics is to "map plot aesthetics to data". I think that for a grammar of graphics package manual keys are a good patch while the package is in development, but in the long-term "manual" keys shouldn't be needed. Scales (with mapping functions) and their respective Guides (with title, labels, position etc) is the intent of gog.

**Comment by bjarthur** [comment]
that's a beautiful plot!  would be great to put it in the gallery as there is currently no `Geom.segment` entry.
