### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by MartaVanin** [GiovineItalia/Gadfly.jl#1261]
Hello,
I am using Julia 0.7 on windows and I was plotting a bar plot with Gadfly, which worked fine until yesterday, when I installed/updated packages after which I get an error and can't plot.
I don't know what versions I used to have, but what I have now is the following:

Cairo v0.5.6
Colors v0.9.5
Compat v2.0.0
Compose v0.7.3
CSV v0.4.3
DataFrames v0.17.1
DataFramesMeta v0.4.1
FileIO v1.0.5
Fontconfig v0.2.0
Gadfly v1.0.1
Memento v0.11.0
Plots v0.19.3
PyCall v1.90.0
PyPlot v2.8.0
RDatasets v0.6.1

plus some other packages that I don't think are related to the issue.

The error I get is:

Error showing value of type Plot:
ERROR: TypeError: in text_extents, in typeassert, expected Compose.PangoLayout, got Nothing

My code is something like the following: 

using DataFrames
using CSV
using Gadfly
import Cairo
import Fontconfig
using Compose

my_plot = Gadfly.plot(my_dataframe, y=:Percentage, x=:Modality, Geom.bar)

**Comment by bjarthur** [comment]
can you please try checking out the dev versions of Gadfly and Compose and seeing if the error persists?  so `]dev Gadfly Compose`.  there have been a couple fixes made lately that effect barplots on 0.7.

**Comment by MartaVanin** [comment]
Thank you @bjarthur, works as earlier now.
