### ISSUE TITLE
Horizontal Geom.bar not working

### ISSUE THREAD

**Issue by xiaodaigh** [GiovineItalia/Gadfly.jl#1266]
```julia
plot(x = ["a","b","c"], y= 1:3, Geom.bar(orientation = :horizontal))
```
this doesn't plot for me.

**Comment by Mattriks** [comment]
Does this work?:
```
p = plot(x=["a","b","c"], y=1:3, Geom.bar(orientation = :horizontal),
    Scale.x_discrete )
```

**Comment by xiaodaigh** [comment]
Yes. So that's a bug? `Scale.x_discrete` seems to be a good default in this case

**Comment by Mattriks** [comment]
See [these lines](https://github.com/GiovineItalia/Gadfly.jl/blob/9df68de0e658be4a2c9ef83770e0d9116f6a68af/src/statistics.jl#L139-L140): For a typical [barplot](http://gadflyjl.org/stable/gallery/geometries/#[Geom.bar](@ref)-1), if the `orientation=:vertical` then I would expect that the y-axis is numerical, and if `orientation=:horizontal`, I would expect that the x-axis is numerical. But your x-axis isn't numerical: why is that btw?

**Comment by xiaodaigh** [comment]
It's a barplot so it's reasonable for xaxis to be categories, i.e. discrete

**Comment by Mattriks** [comment]
I'm not sure that Gadfly works the way you think (for horizontal bars).
In this plot, the x-axis is numerical:
```
p = plot(y=["a","b","c"], x=1:3, Geom.bar(orientation = :horizontal) )
```

**Comment by xiaodaigh** [comment]
ok this makes sense, so maybe need to update the doc. I might help with that
