### ISSUE TITLE
Stroke and Stroke Color

### ISSUE THREAD

**Issue by neilpanchal** [GiovineItalia/Gadfly.jl#1268]
Hello,

I just tried to find a way to change the outline or border color of a point. In the Themes section of the help menu, this option is disguised under `discrete_highlight_color`. The most common name for border or outline color is "stroke". It is used in Illustrator, Matlab, Matplotlib, etc... 

What is the rationale behind `discrete_highlight_color` nomenclature? I think it should be called "stroke_color" or simply "stroke".

Also the description is confusing: "_Color used to outline plot geometry. This is a function that alters (e.g. darkens) the fill color of the geometry. (Function)_". First part is talking about "outline of the plot geometry" and then it says "alters the fill color of the geometry". *stroke* and *fill* have specific meanings in semiological representation so I think the description should be altered. I am curious if there are other reasons for naming it in a particular way.

**Comment by Mattriks** [comment]
I agree that the description should be changed to stroke.

I don't know the answer for your q. about using `_highlight_color` vs. `_stroke_color`, and that might require the original creator ([he sometimes reappears](https://github.com/GiovineItalia/Gadfly.jl/issues/1003#issuecomment-303294716)).

Did you notice that `stroke_color` appears in the list of [Theme options](http://gadflyjl.org/stable/lib/gadfly/#Gadfly.Theme) (it's option 36), but without explanation (some text should be added). There are comment lines [here](https://github.com/GiovineItalia/Gadfly.jl/blob/9df68de0e658be4a2c9ef83770e0d9116f6a68af/src/theme.jl#L172-L175), and an example [here](http://gadflyjl.org/dev/gallery/geometries/#[Geom.errorbar](@ref)-1) (2nd code block).

**Comment by neilpanchal** [comment]
@Mattriks Yea, it does seem apply to[ error bars](https://github.com/GiovineItalia/Gadfly.jl/blob/9df68de0e658be4a2c9ef83770e0d9116f6a68af/src/theme.jl#L172-L175) only.

Here is an example from R's ggplot2 library:
https://ggplot2.tidyverse.org/reference/geom_point.html

Stroke is used to modify the width of the border but not color. 

There is a great example at the bottom:
```
p + geom_point(colour = "black", size = 4.5) +
  geom_point(colour = "pink", size = 4) +
  geom_point(aes(shape = factor(cyl)))
```
![image](https://user-images.githubusercontent.com/8161031/55299233-e456fb80-53e6-11e9-86d8-4cee29ec2d8b.png)

I like this better!

**Comment by Mattriks** [comment]
You can do the same in Gadfly:

```
using RDatasets
mtcars = dataset("datasets", "mtcars")

theme(color,size)= Theme(default_color=color, point_size=size, discrete_highlight_color=identity)

plot(mtcars, x=:MPG, y=:WT, shape=:Cyl, Geom.point,
    layer(Geom.point,  theme("pink", 4pt)),
    layer(Geom.point, theme("black", 4.5pt)),
    Scale.shape_discrete(levels=[4,6,8]),
    Theme(key_swatch_color="pink", default_color="black")
)
```

**Comment by Mattriks** [comment]
With recent improvements to Gadfly  e.g. keys (soon to be tagged #1378), here is an update of this plot.
I use `push_theme` first because this makes it easy to Theme several plots.
```julia
Gadfly.push_theme(
 Theme(default_color="pink", discrete_highlight_color=c->"black", point_size=4.5pt,
    panel_fill="gray92", grid_color="white", grid_line_style=:solid)
)

plot(mtcars, x=:MPG, y=:WT, shape=:Cyl,
    layer(style(default_color=colorant"black", point_size=1pt)),
    layer(), Scale.shape_discrete(levels=[4,6,8])
)
```
![iss1268](https://user-images.githubusercontent.com/18226881/73159753-61ecb480-413b-11ea-96c8-7ce2c212df34.png)
