### ISSUE TITLE
Simple opacity setting

### ISSUE THREAD

**Issue by robsmith11** [GiovineItalia/Gadfly.jl#1270]
There should be an easy way to set the opacity of a geometry to a fractional value.  For example, in ggplot2 one can simply write `alpha=0.5`, but with Gadfly, it's very verbose and non-intuitive: `Theme(lowlight_color=c->RGBA{Float32}(c.r, c.g, c.b, 0.5))`.

**Comment by Mattriks** [comment]
`alpha` functionality has been added to the master branch. You can use it now by doing [`add Gadfly#master`](https://julialang.github.io/Pkg.jl/v1/managing-packages/#Adding-registered-packages-1). There are examples in the [dev docs](http://gadflyjl.org/dev/gallery/scales/#[Scale.alpha_continuous](@ref)-1).  Feedback welcome! You can keep up with the latest developments by checking news.md, which appears in the file list on the main page: https://github.com/GiovineItalia/Gadfly.jl

**Comment by robsmith11** [comment]
Thanks.  `Theme(alphas=[0.5])` does work with the master branch.
