### ISSUE TITLE
Gadfly's Project.toml

### ISSUE THREAD

**Issue by Mattriks** [GiovineItalia/Gadfly.jl#1282]
Following up from this [discourse issue](
https://discourse.julialang.org/t/cant-install-gadfly-unsatisfiable-requirements-detected/22205/10), I looked further at StatsBase and Distributions in Gadfly's Project.toml.

StatsBase is only used in the docs, and for 1 test script, hence in the main Project.toml it should be in the `[extras]` and `[targets]`, not in the `[deps]` and `[compat]`. 

Distributions is used in Gadfly, but since it is a package that users might want to install the latest version independently in an environment (which contains Gadfly), does it need to be listed in the `[compat]` section in Gadfly's Project.toml?

**Comment by bjarthur** [comment]
unsatisfiable requirements for StatsBase is also the reason that the docs don't build.

@non-Jedi said he was going to look into the docs.  we should assign someone to this issue so we don't repeat each others efforts.
