### ISSUE TITLE
Relax dependency versions?

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1287]
I'm stuck on a broken version of Distributions because Gadfly's dependencies are a little too restrictive as of https://github.com/GiovineItalia/Gadfly.jl/pull/1283. My understanding is that currently the max allowed version of Distributions is v0.19.1 even though v0.20.0 is out and fixes my problem and it's due to the hard caps in the `[compat]` section of `Project.toml`

https://github.com/GiovineItalia/Gadfly.jl/blob/8813880fe4fc7dfae7cbddebe8c6053b51c2164f/Project.toml#L40

I suspect we want to use inequalitys instead of the default caret values: https://julialang.github.io/Pkg.jl/dev/compatibility/#Inequality-specifiers-1

**Comment by Mattriks** [comment]
JuliaRegistries/General#647

**Comment by bjarthur** [comment]
if Gadfly's tests work for you with Distributions 0.20, then submit a PR to Gadfly which adds that version to the compat section of Project.toml.  @non-Jedi made a convincing [argument](https://github.com/GiovineItalia/Gadfly.jl/pull/1283#issuecomment-489631263) (to me) that we shouldn't leave the version bounds open ended.

**Comment by tlnagy** [comment]
>  @non-Jedi made a convincing argument (to me) that we shouldn't leave the version bounds open ended.

That argument makes sense. Alright, let me run the tests and see how they perform.
