### ISSUE TITLE
Bugs in histogram when the x-axis are strings

### ISSUE THREAD

**Issue by Moelf** [GiovineItalia/Gadfly.jl#1289]
![image](https://user-images.githubusercontent.com/5306213/59088615-d7f68f80-88bc-11e9-856c-aba3394ef03f.png)
`plot(df, x=:dayofweek, color=:from, Geom.histogram(position=:dodge))` for the above but not the below
![image](https://user-images.githubusercontent.com/5306213/59088645-ee045000-88bc-11e9-9823-7e1042a1309b.png)

**Comment by Mattriks** [comment]
I think this is fixed by #1236. Do [`add Gadfly#master`](https://julialang.github.io/Pkg.jl/v1/managing-packages/#Adding-registered-packages-1)
