### ISSUE TITLE
Guide.ytick should accept a range

### ISSUE THREAD

**Issue by cmcaine** [GiovineItalia/Gadfly.jl#1293]
```julia
using Statistics
using Gadfly

plot(
    y=1:15|> cumsum,
    Geom.line, 
    Guide.yticks(ticks = 0:25:100 |> collect))
```

It would be nice not to have to collect the ticks myself.

In my testing adding this constructor is sufficient:

```julia
Yticks(label, ticks::AbstractRange, orientation) =
    Yticks(label, collect(ticks), orientation)
```

**Comment by tlnagy** [comment]
Agreed. This would be really nice to add, I often forget to collect `ticks` as well. Do you mind submitting a PR with this change? Also, could you fix it for XTicks as well?

**Comment by cmcaine** [comment]
PR submitted.
