### ISSUE TITLE
Plot not opening in web browser

### ISSUE THREAD

**Issue by bojohnson02** [GiovineItalia/Gadfly.jl#1300]
Just today Gadfly has stopped plotting from scripts in my Firefox web browser. It also happens when I call the plot function from the REPL. It opens the file in the default ImageViewer application on Fedora 30, but ImageViewer can't view .html files. I can plot when I'm in a Jupyter Notebook, but I can't do it any longer from a script or in the REPL where it used to just open a new tab in my browser and show the plot.

**Comment by Mattriks** [comment]
There's also problems in the plot gallery with some missing figures:
E.g. http://gadflyjl.org/stable/gallery/geometries/

**Comment by bojohnson02** [comment]
I figured out the issue: I needed to change the default application that opened the files created by Gadfly. Somehow this was changed on my system

**Comment by arielf** [comment]
@bojohnson02 

In my case, `plot()` in REPL was working well, until I installed Gadfly, Compose and a few other packages.  Once I did, the default image-viewer seems to have changed to `gimp` (not by me) and failure to display some temporary generated files `/tmp/...html` ensued.

For the benefit of others, can you add how did you change the default Image-viewer for Julia/Gadfly back to your browser?

Thanks!
