### ISSUE TITLE
Plots missing from docs

### ISSUE THREAD

**Issue by Mattriks** [GiovineItalia/Gadfly.jl#1302]
There's a few plots missing from the docs (both v1.1 and dev). E.g.
[Geom.bar](http://gadflyjl.org/dev/gallery/geometries/#[Geom.bar](@ref)-1), [Geom.contour](http://gadflyjl.org/dev/gallery/geometries/#[Geom.contour](@ref)-1) (2nd figure), [Geom.ellipse](http://gadflyjl.org/dev/gallery/geometries/#[Geom.ellipse](@ref)-1) etc. All these plots use RDatasets, but there are also other plots that use RDatasets and are displayed.

**Comment by tlnagy** [comment]
Looks like the docs are failing to build: https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/563198906

**Comment by tlnagy** [comment]
This looks to be fixed by #1315, but I still need to manually force the build due https://github.com/JuliaRegistries/General/issues/3440 that causes the failures on Julia 0.7
