### ISSUE TITLE
Update DOI and newest DOI doesn't work.

### ISSUE THREAD

**Issue by rapus95** [GiovineItalia/Gadfly.jl#1306]
10.5281/zenodo.3337394 _should_ point to the [1.1.0 release](https://zenodo.org/record/3337394#.XV3GuOgzaUk) but entering it on doi.org (https://doi.org/10.5281/zenodo.3337394) doesn't resolve. You might consider to reference 10.5281/zenodo.593105 since that always leads to the newest version and the page where you can select an explicit version. Though that should probably be noted then.

**Comment by tlnagy** [comment]
Thanks for noticing and finding a solution!
