### ISSUE TITLE
Gadfly doesn't show plots in julia-vscode plot pane.

### ISSUE THREAD

**Issue by synxroform** [GiovineItalia/Gadfly.jl#1311]
I don't think it is Gadfly isuue, but the guy at julia-vscode say it is. Look at this <a href="https://github.com/julia-vscode/julia-vscode/issues/523">thread</a>.

**Comment by tlnagy** [comment]
Hey @bjarthur or @MikeInnes, any thoughts on this? I don't much experience with the Juno/display stack code.

**Comment by davidanthoff** [comment]
I think if the package really needs to push something onto the display stack, it should follow the Plots.jl pattern and make sure it doesn't end up being on top of the stack:

https://github.com/JuliaPlots/Plots.jl/blob/172193e70690c8c72996fb32ea4b3e235e0b72f0/src/init.jl#L22

That is probably the most compatible way to do this right now.

The current implementation breaks both VS Code and ElectronDisplay.jl, whereas the Plots.jl way of handling this works with both (and presumably also Juno).

**Comment by davidanthoff** [comment]
Great!
