### ISSUE TITLE
MIME-type when plotting in Atom/Juno

### ISSUE THREAD

**Issue by NicholasWMRitchie** [GiovineItalia/Gadfly.jl#1316]
The 1.0.1 version of Gadfly in the current version of Atom (1.40.1) produces the following warning:
  * Warning:   The "application/juno+plotpane" MIME type is deprecated. Please use "application/prs.juno.plotpane+html" instead.

# Atom Data

# Atom:
Version: 1.40.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.10.1
Config:
{
  "firstBoot": false,
  "juliaPath": "C:\\Users\\nritchie\\AppData\\Local\\Julia-1.2.0\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}

# ink:
Version: 0.11.0
Config:
undefined

# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.1
Config:
undefined

# language-weave:
Version: 0.6.4
Config:
undefined

# indent-detective:
Version: 0.4.0
Config:
undefined

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

    Status `C:\Users\nritchie\.julia\environments\v1.2\Project.toml`
  [1520ce14] AbstractTrees v0.2.1
  [c52e3926] Atom v0.9.1
  [6e4b80f9] BenchmarkTools v0.4.2
  [fe54227b] BoteSalvatICX v0.0.1 [`C:\Users\nritchie\.julia\dev\BoteSalvatICX`]
  [336ed68f] CSV v0.5.11
  [5ae59095] Colors v0.9.6
  [a93c6f00] DataFrames v0.19.3
  [1313f7d8] DataFramesMeta v0.5.0
  [31c24e10] Distributions v0.21.1
  [7876af07] Example v0.5.4 #master (https://github.com/JuliaLang/Example.jl.git)
  [10506e09] FFAST v0.0.1 [`C:\Users\nritchie\.julia\dev\FFAST`]
  [38e38edf] GLM v1.3.1
  [c91e804a] Gadfly v1.0.1
  [708ec375] Gumbo v0.5.1
  [cd3eb016] HTTP v0.8.5
  [7073ff75] IJulia v1.20.0
  [5903a43b] Infiltrator v0.1.0
  [43edad99] InstantiateFromURL v0.3.3
  [a98d9a8b] Interpolations v0.12.2
  [e5e0dc1b] Juno v0.7.2
  [e1d29d7a] Missings v0.4.1
  [5fb14364] OhMyREPL v0.5.2
  [7b2266bf] PeriodicTable v0.1.2
  [5ad8b20f] PhysicalConstants v0.2.0
  [f27b6e38] Polynomials v0.5.2
  [295af30f] Revise v2.1.9
  [028f657a] TotalLeastSquares v0.1.2
  [1986cc42] Unitful v0.16.0
  [37e2e46d] LinearAlgebra 
  [de0858da] Printf 
  [2f01184e] SparseArrays

**Comment by Mattriks** [comment]
I don't use Juno, but does this work for you?:
```julia
using Gadfly
function Gadfly.show(io::IO, m::MIME"application/prs.juno.plotpane+html", p::Plot)
    buf = IOBuffer()
    svg = SVGJS(buf, Compose.default_graphic_width,
                Compose.default_graphic_height, false)
    draw(svg, p)
    show(io, "text/html", svg)
end
```
