### ISSUE TITLE
Update instructions to use `precompile`

### ISSUE THREAD

**Issue by kazimuth** [GiovineItalia/Gadfly.jl#1321]
The docs say:

> Alternatively, one can avoid the first-time-to-plot penalty altogther by ahead-of-time (AOT) compiling Gadfly into the Julia system image using PackageCompiler.jl.
> ```julia
> julia> ]dev PackageCompiler
> julia> using PackageCompiler
> julia> compile_package("Gadfly", force=false)
> ```

However, this isn't necessary anymore. You can just do `>]precompile` and things will work great.

**Comment by tlnagy** [comment]
The instruction there say something a bit different. The idea is that you can build Gadfly into the system image so that there's no lag when making the first plot. Simply precompiling the image allows Gadfly to load quickly, but the time-to-first-plot penalty is still present.
