### ISSUE TITLE
font family and color in guide.annotation

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1323]
I'm using `Guide.annotation` to add some text to a plot. As far as I can see, both the font family is different from the one Gadfly uses by default and also the color of the font is different (black instead of gray). I tried correcting the former by using `font("Helvetica Neue")`, but that doesn't seem to do anything. And I wasn't able to find out how I can change the font color (if that can be done at all; changing the font size of the annotation works fine). I'd be grateful for any advice.

**Comment by Mattriks** [comment]
Gadfly plots are drawn using the graphics package [Compose.jl](https://github.com/GiovineItalia/Compose.jl).
There are some examples of text in Compose [here](http://giovineitalia.github.io/Compose.jl/latest/tutorial/#Text-1) and [here](http://giovineitalia.github.io/Compose.jl/latest/gallery/forms/#[text](@ref)-1).  Also in the Gadfly docs for [Geom.abline](http://gadflyjl.org/dev/gallery/geometries/#[Geom.abline](@ref)-1) 
(p1 uses `Guide.annotation`).

  The `font()` property should work, assuming that font is available.

**Comment by IgorDouven** [comment]
Thank you, that's very helpful. I can't find here how to change the font
color (in particular, how to make that match the color of the other labels
in the plot). Is that possible? If not, that's not a big problem. But it
would be nice to have this option.

Op ma 30 sep. 2019 om 10:01 schreef Mattriks <notifications@github.com>:

**Comment by Mattriks** [comment]
For Gadfly, the text properties (including color) for plot labels are found [here](https://github.com/GiovineItalia/Gadfly.jl/blob/aa4855ca7d113e31a51389edbfdd87cff15a60a2/src/theme.jl#L126-L158). Does that solve "not matching the color of the other labels"? If not, please provide example code of what you are doing.

**Comment by IgorDouven** [comment]
Well, I could of course change the color of the "other" labels to black. Then the color would match the labels generated via `compose`. But then they would no longer match with the colors of the labels in all the other figures in the paper. (Of course, I could change them to black as well, but ...)

I don't have any special use case in mind. A MWE of what I'm doing is this:
```
using Gadfly, Compose

xcoords=rand(50)
ycoords=rand(50)
cols=rand(50)

Gadfly.plot(x=xcoords, y=ycoords, color=cols, Geom.point, Guide.title("Title"),
    Guide.annotation(compose(context(), Compose.text(0.4115, 0.89, "XXX"), fontsize(10pt), font("Helvetica-Neue"))))
```
The label XXX appears in a darker font than the other ones.

**Comment by Mattriks** [comment]
In this example, I've changed the font color of the Compose.text to Gadfly's `major_label_font` color. 

```Julia
using Colors
p1 = plot(x=xcoords, y=ycoords, color=cols, Geom.point, Guide.title("Title"),
    Guide.annotation(compose(context(), Compose.text(0.4115, 0.89, "XXX"), fontsize(10pt),
            font("Helvetica-Neue"), fill("black"), stroke(nothing)) ))
p2 = plot(x=xcoords, y=ycoords, color=cols, Geom.point, Guide.title("Title"),
    Guide.annotation(compose(context(), Compose.text(0.4115, 0.89, "XXX"), fontsize(10pt),
            font("Helvetica-Neue"), fill(colorant"#564a55"), stroke(nothing)) ))
hstack(p1, p2)
```
Does that help?

**Comment by IgorDouven** [comment]
That solves the problem! Many thanks!

Op di 1 okt. 2019 om 12:20 schreef Mattriks <notifications@github.com>:
