### ISSUE TITLE
ERROR: TypeError: in typeassert, expected Compose.PangoLayout, got Nothing

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#1324]
I have to pin cairo @ 0.6.0 to avoid this error.

**Comment by Mattriks** [comment]
An issue has been opened in [Compose](https://github.com/GiovineItalia/Compose.jl#compose) to update Compose to use Cairo 0.7: https://github.com/GiovineItalia/Compose.jl/issues/357
