### ISSUE TITLE
Help required in drawing a chart

### ISSUE THREAD

**Issue by hajsf** [GiovineItalia/Gadfly.jl#1327]
I've the below table of data:
```bash
2×7 DataFrame
│ Row │ Customer │ M0      │ M1       │ M2    │ M3    │ ...   │ Mn    │
│     │ String   │ Int64   │ Int64    │ Int64 │ Int64 │ Int64 │ Int64 │
├─────┼──────────┼─────────┼──────────┼───────┼───────┼───────┼───────┤
│ 1   │ x        │ 8       │ 7        │ 9     │ 2     │ .     │ 3     │
│ 2   │ y        │ 6       │ 3        │ 4     │ 2     │ .     │ 7     │
```
That is generted from the below:
```julia
using CSV, Query, DataFrames
df = CSV.read("deliveries.csv"; header=true, delim=',')

x = by(
    sdf -> mapcols(sum, sdf[:, 3:end]),
    df, 
    :Customer
)
println(x)
```
I'm trying to use `using Gadfly`, to draw the chart, so that each row (customer) is a series, so I'll be having a multiple time serials lines. but not sure how to go!

**Comment by Mattriks** [comment]
See Julia discourse:
https://discourse.julialang.org/t/help-required-for-drawing-a-chart/29694

**Comment by tlnagy** [comment]
In general, the julia discourse is the best avenue for asking questions. Github issues are primarily for development, bug reports, design discussions, etc.
