### ISSUE TITLE
Testing broken on 0.7

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1328]
Continuing the discussion from #1318, cc @Mattriks 

I had a bit more time to look into this and it looks like we initially install Parsers v0.3.0 (https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/594389463#L217), but then install Parsers v0.2.22 https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/594389463#L456 when actually doing the testing? 

But AFAICT JSON.jl stays on v0.21 https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/594389463#L305, which is the version that introduces the requirement on Parsers. So likely what is happening is that Parsers is downgraded after Compose is installed and that causes the build failure. The solution is probably to install Compose#master again in the test environment to force dependency resolution.

**Comment by tlnagy** [comment]
@bjarthur are you okay with sunsetting 0.7 support?

**Comment by bjarthur** [comment]
i'm fine with dropping 0.7 support.  it's been over a year now.  but only because so many of our dependencies are dropping it.  unnecessary for them to do so because the only difference with 1.0 is the removal of deprecation warnings.  i'll submit PRs to Compose and Gadfly.
