### ISSUE TITLE
Show datapoints on hover

### ISSUE THREAD

**Issue by DJ-kim** [GiovineItalia/Gadfly.jl#1334]
Hi.
Is it possible to display X and Y values when I click or hover with mouse cursor in Gadfly?

It works in Plotly (https://github.com/JuliaPlots/Plots.jl/issues/1590).

**Comment by bjarthur** [comment]
it is when SVG is displayed in a browser.  notice the question mark in the upper right corner.  hover over the mouse and hit that key and a menu of keyboard shortcuts will be displayed.  the C key will enter a mode in which the cursor coordinates are displayed.  last i checked this did NOT work in Juno.  would be great if someone could help us figure that out.  see https://github.com/JunoLab/Juno.jl/issues/125

**Comment by bjarthur** [comment]
displaying X,Y coordinates of the mouse [should work now in Juno](https://github.com/GiovineItalia/Gadfly.jl/issues/1115#issuecomment-575040163).  please re-open this issue if you still have problems.
