### ISSUE TITLE
Different line width for error bar

### ISSUE THREAD

**Issue by dovahcrow** [GiovineItalia/Gadfly.jl#1336]
Currently it seems like errorbar uses the line_width property in the `Theme`. Is there any way to let Geom.errorbar uses a thiner line width?

**Comment by Mattriks** [comment]
[See the docs](http://gadflyjl.org/dev/man/themes/) e.g. `Theme(line_width=4pt)`.  If that doesn't work, then please post example code of what you have tried, and provide `versioninfo()`.

**Comment by dovahcrow** [comment]
@Mattriks 

The problem is that `Theme.line_width` also controls the line with for `Geom.line`, which is the one I don't want to change.

Using ggplot with `geom_linerange`
![image](https://user-images.githubusercontent.com/998606/67643633-b8491d80-f8d6-11e9-87b2-845cef0d1eb1.png)

Gadfly with `Theme.line_width` and `Geom.errorbar`
![image](https://user-images.githubusercontent.com/998606/67643652-dd3d9080-f8d6-11e9-9534-d01640f2245f.png)

`Geom.errorbar` and `Geom.line` both use `Theme.line_width` makes the plot looks weird.

**Comment by Mattriks** [comment]
See the docs section on [layers](http://gadflyjl.org/dev/man/compositing/#Layers-1): Layers can input Geometries, Statistics, and Themes"

**Comment by dovahcrow** [comment]
@Mattriks Feasible solution! Thanks.
