### ISSUE TITLE
How to make lines with Julia using Gadfly (Facility location problem)?

### ISSUE THREAD

**Issue by raul-utec** [GiovineItalia/Gadfly.jl#1337]
Im trying to make the facility location problem algorithm where i have to connect a supplying point to a supplied point , so i got hundreds of supplied points binded to many supplying points so i got something like [this](https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiFr_Gk6sXlAhWyxFkKHbfdBg8QjRx6BAgBEAQ&url=https%3A%2F%2Fwww.researchgate.net%2Ffigure%2FFacility-location-problem-example_fig1_221182599&psig=AOvVaw0ap5dpb3EbPMzLkycU7JPE&ust=1572588356325290)
,So i got a possible solution , but dont know how to graph more than one supply point grid  im trying to use the next code as example:

```
using Gadfly
xc = [0,1,0,-1,0,4,0,-2,0,-2]
yc = [0,3,0,-2,0,1,0,2,0,-2]
Gadfly.plot(x=xc, y=yc, Geom.path, Geom.point)
```

 Im also using this code ,with vectors as geometry, but can not graph more than a single supply point and its supplied points which is binded:

```
using Gadfly

# coordinate system and scales are necessary for Geom.vector

coord = Coord.cartesian(xmin=-5, xmax=5, ymin=-5, ymax=5)
xsc  = Scale.x_continuous(minvalue=-5, maxvalue=5)
ysc  = Scale.y_continuous(minvalue=-5, maxvalue=5)

# prepare the points you want to show

xend = [1,-1,4,-2,-2]
yend = [3,-2,1,2,-2]

# create the supplying center (1,2)

x = fill(1,length(xend))
y = fill(2,length(yend))

# plot everything

Gadfly.plot(x=x,y=y,xend=xend,yend=yend,xsc,ysc,Geom.vector,coord)

```
So in attempt to graph more than one supply point i get a error, I could make using layers , but dont think proper to make it for hundreds of layers by each supply point.Regards

**Comment by Mattriks** [comment]
See Julia discourse:
https://discourse.julialang.org/t/how-to-make-lines-with-julia-using-gadfly-facility-location-problem

**Comment by Mattriks** [comment]
Also, the error you get above (with `Geon.vector`) is because `Geom.vector` is expecting floats not Integers, so add this line to the above code:
```julia
x, y = fill(1.0, length(xend)), fill(2.0, length(yend))
```
