### ISSUE TITLE
shape does not properly work with layers

### ISSUE THREAD

**Issue by CNOT** [GiovineItalia/Gadfly.jl#1338]
If one wants to change the shape of the points in the plot, [the documentation](http://gadflyjl.org/stable/gallery/shapes/#Shapes-1) suggests the following format:

    using Gadfly
    plot(x=1:10,y=rand(10),shape=[Shape.cross],Geom.point)
![test](https://user-images.githubusercontent.com/7808287/68078404-a6bab680-fdab-11e9-80fd-20b56d906a70.png)

However, when one tries to naturally generalize this to layers, it produces an error:

    using Gadfly
    l1 = layer(x=1:10,y=rand(10),shape=[Shape.cross],Geom.point)
    l2 = layer(x=1:10,y=rand(10),shape=[Shape.xcross],Geom.point)
    plot(l1,l2)

    ERROR: promotion of types typeof(Gadfly.Shape.cross) and typeof(Gadfly.Shape.xcross) failed to change any arguments
    Stacktrace:
    [1] error(::String, ::String, ::String) at ./error.jl:42
    [2] sametype_error(::Tuple{typeof(Gadfly.Shape.cross),typeof(Gadfly.Shape.xcross)}) at ./promotion.jl:308
    [3] not_sametype(::Tuple{typeof(Gadfly.Shape.cross),typeof(Gadfly.Shape.xcross)}, ::Tuple{typeof(Gadfly.Shape.cross),typeof(Gadfly.Shape.xcross)}) at ./promotion.jl:302
    [4] promote(::Function, ::Function) at ./promotion.jl:285
    ...

In fact, digging around I found other methods that should work fine in plot, but did not work in layers. For example, based on #1137 one would try:

    l1 = layer(x = 1:10, y = rand(10), style(point_shapes=repeat([Shape.cross],10),point_size=2mm),Geom.point)
    l2 = layer(x = 1:10, y = rand(10), style(point_shapes=repeat([Shape.xcross],10),point_size=2mm),Geom.point)
    plot(l1,l2)

![test](https://user-images.githubusercontent.com/7808287/68078477-a7078180-fdac-11e9-8a5e-d7808892458e.png)

Which is not what was expected.

**Comment by Mattriks** [comment]
Your first example above works now on Gadfly master branch (it was fixed by PR #1333) which got merged today.  You can use it now by doing:
```
]add Gadfly#master
```
See the [Pkg docs](https://julialang.github.io/Pkg.jl/v1/managing-packages/#Adding-registered-packages-1). And if you want to change the point size, do:
```julia
plot(l1,l2, Theme(point_size=4pt))
```

**Comment by CNOT** [comment]
Thanks. I spent way more time on this than I'd like to admit. But I guess it's a good thing that it got fixed.

**Comment by CNOT** [comment]
I think it was premature of me to close this issue right away. In my actual use case, I need these shapes to be applied inside layers that are embedded inside a `Geom.subplot_grid`. And PR #1333 doesn't seem to be fixing that.

**Comment by CNOT** [comment]
Here's a MWE:

    using DataFrames, Gadfly
    DF = DataFrame(x = repeat(1:10,2),
                y = rand(20),
                z = append!(repeat(["a"],10),repeat(["b"],10)))
    set_default_plot_size(10cm, 8cm)
    plot(DF,xgroup = :z, Geom.subplot_grid(layer(x=:x,y=:y,shape=[Shape.square], Geom.point)))

![test svg](https://user-images.githubusercontent.com/7808287/68080293-84866000-fdce-11e9-99ff-f9d919c0cbbc.png)
