### ISSUE TITLE
Documentation Gadfly.Guide.title

### ISSUE THREAD

**Issue by dev-energy** [GiovineItalia/Gadfly.jl#1341]
I think there is a typing mistake in the documentation at Gadfly.Guide.title
There it is written Geom.title(title) shouldn't it be Guide.title(title)?

**Comment by Mattriks** [comment]
It's correct in the [Gallery](http://gadflyjl.org/dev/gallery/guides/#[Guide.title](@ref)-1), but yes a typo on the library page.

**Comment by tlnagy** [comment]
Hi @dev-energy, please submit a PR for our docs if you have time, it'll help us get better!
