### ISSUE TITLE
StackOverflowError: Gadfly.draw() fails for large images

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#1342]
```
(v1.2) pkg> status Gadfly
    Status `~/.julia/environments/v1.2/Project.toml`
  [5ae59095] Colors v0.9.6
  [34da2185] Compat v2.2.0
  [a81c6b42] Compose v0.7.4 #master (https://github.com/GiovineItalia/Compose.jl.git)
  [864edb3b] DataStructures v0.17.5
  [31c24e10] Distributions v0.21.6
  [c91e804a] Gadfly v1.0.1
  [c8e1da08] IterTools v1.2.0
  [682c06a0] JSON v0.21.0
  [e5e0dc1b] Juno v0.7.2
  [442fdcdd] Measures v0.3.0
  [ae029012] Requires v0.5.2
  [2913bbd2] StatsBase v0.32.0
  [ade2ca70] Dates
  [8dfed614] Test
```

```
X=rand(50,10000);
pS = Gadfly.plot([Gadfly.layer(x=1:50, y=X[:,i], color=["c$(i)" for j in 1:50], Gadfly.Geom.line(), Gadfly.Theme(line_width=2Gadfly.pt)) for i=1:10000]..., Gadfly.Theme(key_position=:none))
```

this works.

```
display(pS)
```

also works. However,

```
Gadfly.draw(Gadfly.PDF("a.pdf"), pS)
Gadfly.draw(Gadfly.PNG("a.png"), pS)
```

fail:

```
ERROR: StackOverflowError:
Stacktrace:
 [1] compose!(::Compose.Context, ::Compose.Context, ::Compose.Context, ::Compose.Context, ::Vararg{Compose.Context,N} where N) at /Users/monty/.julia/packages/Compose/6FIbD/src/container.jl:310 (repeats 9620 times)
 [2] #render_prepared#99(::Bool, ::Bool, ::typeof(Gadfly.render_prepared), ::Gadfly.Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at /Users/monty/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:814
 [3] render_prepared(::Gadfly.Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at /Users/monty/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:803
 [4] render(::Gadfly.Plot) at /Users/monty/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:749
 [5] draw(::Compose.Image{Compose.PDFBackend}, ::Gadfly.Plot) at /Users/monty/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:854
 [6] top-level scope at REPL[37]:1
```

**Comment by Mattriks** [comment]
Another way ([see docs](http://gadflyjl.org/dev/man/plotting/#Wide-formatted-data-1)):
```julia
 X = [1:50 exp.(-0.05*[1:50;]).*randn(50,5000)]
 p = plot(X, x=Col.value(1), y=Col.value(2:5000...), color=Col.index(2:5000...), Geom.line)
draw(PNG("issue1342.png"), p)
```
![issue1342](https://user-images.githubusercontent.com/18226881/68514682-840c2e80-02d2-11ea-850a-d6be9f3106df.png)

**Comment by montyvesselinov** [comment]
I do not want to have continuous colors; how i can produce the same with discreet colors (i do not mind that they are repeated).

Also around 10,000 is the break point; the old way works 5,000 as well

**Comment by Mattriks** [comment]
For discrete colors, just add `Scale.color_discrete` to my plot, but note Gadfly's default discrete color limits (#1317). My plot works for 10000 lines:

![issue1342](https://user-images.githubusercontent.com/18226881/68520435-d4dc5100-02eb-11ea-8487-7f48aacb8d2a.png)

**Comment by montyvesselinov** [comment]
i know your code works for 10000. 

one more stupid question; i want to use a set of discrete colors; not a map; how i can use these colors (repeated):

colors = ["red", "blue", "green", "orange", "magenta", "cyan", "brown", "pink", "lime", "navy", "maroon", "yellow", "olive", "springgreen", "teal", "coral", "#e6beff", "beige", "purple", "#4B6F44", "#9F4576"]

**Comment by montyvesselinov** [comment]
Still for me the most puzzling question is why I can `display` the image but I cannot `draw` it?!

**Comment by Mattriks** [comment]
The difference between your plot and my plot is that your plot has 10000 layers with 1 line, and my plot has 1 layer with 10000 lines.  Layers are more expensive than lines.

On your question about repeated discrete colors, typically how many points does each of your lines have? i.e is 50 points based on a real world example?

**Comment by Mattriks** [comment]
Currently in Gadfly, discrete colors don't auto-repeat for `Geom.line`. Instead, here I make the color palette repeat:
```julia
# colors vec as above
palette = Gadfly.parse_colorant(colors)
colorep(nc) = palette[rem.((1:nc).-1, length(palette)).+1]

n = 23
X = [1:50 exp.(-0.05*[1:50;]) * permutedims([2:n;])]
p = plot(X, x=Col.value(1), y=Col.value(2:n...), 
    color=Col.index(2:n...), group=Col.index(2:n...),
    linestyle=Col.index(2:n...), Geom.line,
    Scale.DiscreteColorScale(colorep)
)
```
![issue1342b](https://user-images.githubusercontent.com/18226881/68522681-27286c80-0302-11ea-96d3-162999029250.png)
 There are 2 red lines in this figure, as expected (columns 2 and 23). The key labels show the newest column with that color.

**Comment by montyvesselinov** [comment]
This is perfect; my other concern is frequently my x-labels are Dates. E.g.

```
collect(Dates.Date(2000):Dates.Month(1):Dates.Date(2004,2,1))
```
Of course

```
X = [collect(Dates.Date(2000):Dates.Month(1):Dates.Date(2004,2,1)) exp.(-0.05*[1:50;]) * permutedims([2:n;])]
```
works but my concern is than now X becomes `Any` and this can be memory issue for huge X.

is there another tricky way to pass x values? other than adding X column.

**Comment by Mattriks** [comment]
To do that, make small `x` a vector like this:
```julia
n = 22
X = exp.(-0.05*[1:50;]) * permutedims([1:n;])
date1 = collect(Date(2000):Month(1):Date(2004,2,1)) 
ci = Col.index(1:n...)

p = plot(X, x=repeat(date1, inner=n), 
    y=Col.value(1:n...), color=ci, group=ci, linestyle=ci, 
    Geom.line, Scale.color_discrete(colorep)
)
```

**Comment by montyvesselinov** [comment]
Ok; this is perfect; i think finally i understand how wide-format works. thank you very much!

**Comment by Mattriks** [comment]
This issue can be closed, except it would be good to add a doc example for matrix data of how to add a variable that isn't in the matrix e.g. `x=repeat(date1, inner=n)` as in my example above.
