### ISSUE TITLE
Alpha in SVGJS

### ISSUE THREAD

**Issue by CiaranOMara** [GiovineItalia/Gadfly.jl#1353]
The theme is not displayed correctly in the left-hand plot. There should be some transparency.

http://gadflyjl.org/stable/gallery/geometries/#[Geom.rect](@ref),-[Geom.rectbin](@ref)-1

<img width="830" alt="image" src="https://user-images.githubusercontent.com/24236593/69471737-df700d80-0df6-11ea-9ab6-e0b1be46d472.png">

**Comment by CiaranOMara** [comment]
The `fill-opacity` tag is not present in the left-hand plot.

**Comment by Mattriks** [comment]
Note that this happens when `hstack` is used (plot `pa` renders correctly by itself), and with the SVG/SVGJS backend (its a Compose issue).

But the better way to do this now should be:
```julia
pa = plot(D, x=:x, y=:y, alpha=[0.5], Geom.rectbin)
```
so the `alpha` aesthetic needs to be enabled for `Geom.rectbin`, https://github.com/GiovineItalia/Gadfly.jl/pull/1263#issuecomment-478302717. Once enabled, this will work with `hstack`.

**Comment by CiaranOMara** [comment]
I've since tried a MWE. Unfortunately, it has worked...

```julia
using Colors, Gadfly

set_default_plot_size(21cm, 8cm)

p1 = plot(x=1:9, y=1:9, Geom.blank, layer(xmin=[2], ymin=[2], xmax=[8], ymax=[8], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5))));
p2 = plot(x=1:9, y=1:9, Geom.blank, layer(xmin=[2], ymin=[2], xmax=[8], ymax=[8], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5))));

p = hstack(p1,p2)

p |> SVG("foo.svg")
p |> SVGJS("foo.html")

import Cairo
import Fontconfig

p |> PNG("foo.png")
```

<img width="1006" alt="mwe" src="https://user-images.githubusercontent.com/24236593/69473428-72fe0a00-0e08-11ea-8147-50399cb4c58a.png">


<img width="676" alt="image" src="https://user-images.githubusercontent.com/24236593/69473459-c53f2b00-0e08-11ea-8664-399842fe2ff3.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/24236593/69473500-06373f80-0e09-11ea-8a23-ef1735513a1b.png">

**Comment by Mattriks** [comment]
But now p1 and p2 each have 2 layers , so you've changed the Compose tree and the inheritance (its a Compose issue).

**Comment by CiaranOMara** [comment]
Some more information to determine where in the tree that there is an issue. Also, it seems that only SVGJS is affected.

```julia
p1 = plot(layer(xmin=[2], ymin=[2], xmax=[3], ymax=[3], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5))));
p2 = plot(layer(xmin=[2], ymin=[2], xmax=[3], ymax=[3], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5))));
```

<img width="938" alt="image" src="https://user-images.githubusercontent.com/24236593/69474024-397ccd00-0e0f-11ea-98ad-cf68d5ea68a5.png">


```julia
p1 = plot(layer(xmin=[2,4], ymin=[2,4], xmax=[3,8], ymax=[3,8], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5)))); 
p2 = plot(layer(xmin=[2,4], ymin=[2,4], xmax=[3,8], ymax=[3,8], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5))));
```
<img width="941" alt="image" src="https://user-images.githubusercontent.com/24236593/69474031-48637f80-0e0f-11ea-82ba-617813a18ef1.png">

```julia
p1 = plot(layer(xmin=[2], ymin=[2], xmax=[3], ymax=[3], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5)))); 
p2 = plot(layer(xmin=[2,4], ymin=[2,4], xmax=[3,8], ymax=[3,8], Geom.rect, Theme(default_color=RGBA(0.5,0.5,0.5,0.5))));
```

<img width="933" alt="image" src="https://user-images.githubusercontent.com/24236593/69474036-531e1480-0e0f-11ea-815e-1cfd04e08955.png">

**Comment by CiaranOMara** [comment]
@Mattriks, can one reasonably use Compose's introspect function on these plots? If so, all MWE plots in this thread have the same tree.

**Comment by CiaranOMara** [comment]
Maybe the introspect plot was clipped or had overlapping elements.

**Comment by Mattriks** [comment]
Actually this issue is the same problem as in #1242. It was "fixed" for `Geom.ribbon` because the `alpha` aesthetic was enabled for ribbon.  So the issue can be: 

i) "fixed" in Gadfly, e.g. enable `alpha` for `Geom.rect`, or
ii)  maybe fixed in Compose.

 I'm guessing there's an unidentified inheritance issue in the SVG backend, which is appearing in SVGJS for unknown reasons.

**Comment by CiaranOMara** [comment]
It'd be nice to track this down and fix it in Compose so that `Colorant` can be used willy-nilly.

**Comment by Mattriks** [comment]
On the introspect function, Gadfly's plot tree has a `Compose.Table` node, so to view it:
```julia
set_default_graphic_size(8inch, 4inch)
p = plot(x=[0,10], y=[0,1], Geom.blank)
tbl = render(p).container_children.head.container_children.head
# compose(context(), tbl[1,3]) # see what renders
introspect(tbl[1,3][1])
```
Note the plot tree includes 3 guides for SVGJS, which are easy to pick out because they contain text.

**Comment by CiaranOMara** [comment]
When checking out the `Compose.table`, I found that `render()` expects `Plot`. Naturally, I had a look at the affected plot without `hstack`. The plot by its self was fine. I maybe the issued is in [stack.jl](https://github.com/GiovineItalia/Compose.jl/blob/master/src/stack.jl).

<img width="988" alt="image" src="https://user-images.githubusercontent.com/24236593/69494333-898e8900-0f0e-11ea-8907-f3c24e7b11fb.png">

**Comment by Mattriks** [comment]
PR #1439 will close this issue in Gadfly. If there is a related problem in Compose, than an example should be illustrated using Compose only (and an issue opened there).
