### ISSUE TITLE
Function flatten conflict with exported function flatten from DataFrames

### ISSUE THREAD

**Issue by Greg-R** [GiovineItalia/Gadfly.jl#1359]
v0.19.4 DataFrames did not export flatten.  v0.20.0 exports flatten.
I am seeing this warning:

WARNING: both DataFrames and Iterators export "flatten"; uses of it in module Gadfly must be qualified

and then this error:

ERROR: UndefVarError: flatten not defined

Is this a problem in DataFrames or Gadfly?

**Comment by Greg-R** [comment]
The error reported above should be:

ERROR: UndefVarError: flatten not defined

**Comment by Mattriks** [comment]
That needs to be fixed in Gadfly, so that it's compatible with DataFrames v0.20.0.  In the meantime, you'll need to use DataFrames 0.19.4:
```julia
]add DataFrames@0.19.4
```

**Comment by Greg-R** [comment]
Thank you, that eliminates the warning and error; my code is running to completion now.
