### ISSUE TITLE
Gadfly shouldn't push a display onto the stack at init

### ISSUE THREAD

**Issue by davidanthoff** [GiovineItalia/Gadfly.jl#1361]
In general, plot packages should leave the display stack alone, because pushing displays onto the stack breaks how actual displays can integrate into the multi media stack.

The current behavior of Gadfly breaks the VS Code extension plot pane and ElectronDisplay.jl.

**Comment by Mattriks** [comment]
See #1311

**Comment by davidanthoff** [comment]
Ah, duplicate :)
