### ISSUE TITLE
making scatter plots with different shaped markers (issues)

### ISSUE THREAD

**Issue by SimonEnsemble** [GiovineItalia/Gadfly.jl#1366]
# issue 1

```
plot(x=rand(4), y=rand(4), Geom.point, shape=[Shape.hexagon],
     Guide.xlabel("Re"),
     Guide.ylabel("Im")
)
```
automatically includes a legend, which I don't want. this seems an odd default, and how can I remove the legend?

![image](https://user-images.githubusercontent.com/30643894/71052076-323f9b00-20ff-11ea-88aa-51ce8cd8c12a.png)

# issue 2
this code results in no output
```
plot(layer(x=rand(4), y=rand(4), Geom.point, shape=[Shape.hexagon]),
     layer(x=rand(4), y=rand(4), Geom.point, shape=[Shape.cross]),
     Guide.xlabel("Re"),
     Guide.ylabel("Im")
)
```
how can I make two layers with different symbols outside (without building a `DataFrame`)?

# issue 3
the markers in the key seem to be a different size than inside the plot. is it possible to make them the same size using `Theme.point_size`?

![image](https://user-images.githubusercontent.com/30643894/71052313-d3c6ec80-20ff-11ea-98f2-2caee6d8c618.png)

# issue 4
even in the `DataFrame` paradigm, 

```
df = DataFrame(x=rand(3), y=rand(3), z=["a", "a", "b"])

plot(df, x=:x, y=:y, shape=:z, hipster_theme, shapes=[Shape.cross, Shape.circle])
```
how can I control which shapes are used, e.g. specify crosses and circles?

![image](https://user-images.githubusercontent.com/30643894/71052524-6ebfc680-2100-11ea-8a6a-7551144857ea.png)

# issue 5
is there a manual key (legend) I could make while specifying the shapes of the data? That way I could get rid of the title on the legend above, which is "z".

**Comment by Mattriks** [comment]
1) and 4.  use `Theme()` e.g. 
`Theme(key_position=:none, point_shapes=[Shape.cross, Shape.circle])`
To see all the options do `dump(Theme(), maxdepth=1)`

2) Has been fixed recently on master branch (#1333). To use master branch do
```
]add Gadfly#master
```

I'll get back to you about 3 and 5.

**Comment by Mattriks** [comment]
For 5, try [Guide.shapekey](http://gadflyjl.org/dev/gallery/guides/#[Guide.shapekey](@ref)-1). `Scale.shape_discrete(levels= )` can be used to set the order of the levels, which will 'match' the order in `Theme(point_shapes= )`. There's a generic discrete scale example in the [Tutorial](http://gadflyjl.org/dev/tutorial/#Discrete-Scales-1).

**Comment by SimonEnsemble** [comment]
thanks. I am passing around a theme:
```
hipster_theme = Theme(default_color="orange", line_width=1mm, 
    major_label_font_size=14pt, minor_label_font_size=12pt, 
    panel_fill="ivory", minor_label_font="Courier", 
    major_label_font="Courier", point_size=5pt);
```

but when I for example `Gadfly.push_theme(hipster_theme)` then:

```
Gadfly.push_theme(Theme(point_shapes=[Shape.cross, Shape.star2]))
plot(layer(x=rand(4), y=rand(4), Geom.point, shape=[Shape.cross]),
     layer(x=rand(4), y=rand(4), Geom.point, shape=[Shape.star2]),
     Guide.xlabel("Re"),
     Guide.ylabel("Im"),
     Guide.shapekey(title="", labels=["zeros", "poles"])
)
```
to do as you say, it deletes all of the other settings in `hipster_theme`! :(
and I want keys in *some* of my plots so I wouldn't want to pass `key_position=:none` to my `hipster_theme`.

I can't seem to figure out how `Scale.shape_discrete` works/what its purpose is from the docs.

**Comment by Mattriks** [comment]
Here's an example of `Scale.shape_discrete`:
```julia
plot(layer(x=rand(4), y=rand(4), Geom.point, shape=["poles"]),
     layer(x=rand(4), y=rand(4), Geom.point, shape=["zeros"]),
    Scale.shape_discrete(levels=["zeros","poles"]),
     Guide.xlabel("Re"), Guide.ylabel("Im"),
     Guide.shapekey(title=""), style(point_shapes=[Shape.cross, Shape.star2])
)

```

**Comment by Mattriks** [comment]
# issue 6

When in layers, shape aesthetic levels don't auto-group in the same way as color aesthetic levels:
```julia
pa = plot( Theme(point_size=6pt),
    layer(x=rand(4), y=rand(4), color=["A level"]),
     layer(x=rand(4), y=rand(4), color=["B level"]) )
pb = plot( Theme(point_size=6pt),
    layer(x=rand(4), y=rand(4), shape=["A level"]),
     layer(x=rand(4), y=rand(4), shape=["B level"]) )
hstack(pa, pb)
```
![iss1366_6](https://user-images.githubusercontent.com/18226881/78554596-c9fffb00-784e-11ea-9674-ff71f801b65e.png)
