### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by matthieugomez** [GiovineItalia/Gadfly.jl#1378]
A lot of bugs have been fixed since the last release. Would it be possible to tag a new one?

**Comment by bjarthur** [comment]
need to resolve https://github.com/GiovineItalia/Gadfly.jl/issues/1368 first

**Comment by kimikage** [comment]
cf. https://github.com/GiovineItalia/Gadfly.jl/pull/1377#issuecomment-571809271

**Comment by jaakkor2** [comment]
`]add Gadfly` installs v0.8.0 (!) on Julia v1.3.1, and now seems like master works, time for the tag?

**Comment by bjarthur** [comment]
in a clean environment `]add Gadfly` installs 1.1.0 for me on julia 1.3.1.  but agreed, we should tag a release soon.

@Mattriks when in your [roadmap](https://github.com/GiovineItalia/Gadfly.jl/issues/1385) is a logical time to tag a release?  perhaps after #1386 is merged??

**Comment by Mattriks** [comment]
I think tag after #1386, and #1389, #1390 are merged. Those 3 PRs are ready to merge.

**Comment by rsrock** [comment]
I know you're on this, but please tag soon (may need a tag for Compose too?). I currently can't install Gadfly alongside other packages that use Colors.

**Comment by Mattriks** [comment]
In the meantime, try switching to Gadfly master branch:
```
]add Gadfly#master
```

**Comment by bjarthur** [comment]
closed by https://github.com/GiovineItalia/Gadfly.jl/pull/1393
