### ISSUE TITLE
Render to Gtk

### ISSUE THREAD

**Issue by Kelvyn88** [GiovineItalia/Gadfly.jl#1381]
Hi,

Will anyone know how to put a plot on a Gtk Canvas?

**Comment by Mattriks** [comment]
See [Immerse.jl](https://github.com/JuliaGraphics/Immerse.jl).

**Comment by Mattriks** [comment]
@Kelvyn88 if you found an answer for your question, please provide a brief summary here and/or close this issue.

**Comment by Kelvyn88** [comment]
Sorry @Mattriks. Immerse was the solution! Thanks.
