### ISSUE TITLE
Weird stacking of layers

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#1391]
The code is complicated so I cannot give you a simple breaking example. However, in essence, I plot a series of gray curves and a single red curve. However, when the curves are plotted the red curve is sometimes behind and sometimes in front of the gray layers. How is this possible?!

<img width="204" alt="image" src="https://user-images.githubusercontent.com/5632376/73478684-bff3e480-4353-11ea-88df-2329b891a738.png">

the code is something like this:

```
colormap =
function(nc)
[Gadfly.parse_colorant(["red"]); repeat(Gadfly.parse_colorant(["gray"]), inner=nc-1)]
end
pS = Gadfly.plot(X, x=repeat(xaxis, inner=nS), y=Gadfly.Col.value(1:nS...), color=colindex, group=colindex, Gadfly.Scale.color_discrete(colormap))
```
What I can potentially do to avoid this from hqppening?!

**Comment by Mattriks** [comment]
I can reproduce this by inserting a NaN into the matrix X:

```julia
x = 0.001:0.01:10
n = length(x)
y = advdiff.(x) # a custom function to generate y
X = hcat(50y+randn(n), 50y+0.4*randn(n), 50y+0.3*randn(n))
 X[500,1] = NaN

ci = Col.index(1:3...)
plot(X, x=repeat(x, inner=3), y=Col.value(1:3...), color=ci, Geom.line,
    Scale.color_discrete)
```
![iss1391](https://user-images.githubusercontent.com/18226881/73500172-19244c80-4416-11ea-9800-db13702d3166.png)


A workaround would be to remove the row with NaN (or missing).
A long-term fix might be better done in Compose.jl than in Gadfly, but I'll investigate.

**Comment by Mattriks** [comment]
I opened an issue in Compose (GiovineItalia/Compose.jl#384), which is a first step towards fixing the above issue.  The issue here is that in Gadfly, `Geom.line` contains a patch which works generically for NaNs and Missing values, but to do so, the line containing NaNs or Missing values is split into two lines (plotted separately), rather than keeping (or creating) a single line with a NaN.

**Comment by montyvesselinov** [comment]
@Mattriks You nailed it. I really had NaN's in the dataset. I was suspecting that they cause this behavior but i was not sure!!! Thank you very much!!!

My short term solution was to plot all the gray lines first because they did not have NaNs and plot the red line (with NaN's) last.
