### ISSUE TITLE
Add Gadfly.Scale.linestyle_discrete_manual() ?

### ISSUE THREAD

**Issue by frankwswang** [GiovineItalia/Gadfly.jl#1406]
Is it possible to add this function in the future?
```
Gadfly.Scale.linestyle_discrete_manual(styles...; levels=nothing, order=nothing)
```
Because sometimes I find the default arrangement of line styles may not fit well for certain shapes of lines.

Thank you.

**Comment by Mattriks** [comment]
The palette for discrete scales can be changed using `Theme`, see the [Tutorial](http://gadflyjl.org/stable/tutorial/#Discrete-Scales-1). 
For line styles, the default palette is `Theme().line_style`.  Custom line styles are possible:

```julia
using Compose, DataFrames, Gadfly, RDatasets

D = dataset("ggplot2", "economics")
Dl = stack(D[:, [1,2,6]],  Not(:Date))

# Example of a custom line style palette
lstyle = [[1, 1].*3.0mm, [5, 2, 3, 2].*2.0pt]

 p = plot(Dl, x=:Date, y=:value, color=:variable, linestyle=:variable,
    Geom.line, Scale.y_log10, 
#     Theme(line_style=[:dot, :dash])
    Theme(line_style=lstyle)
)
```
![linestyle](https://user-images.githubusercontent.com/18226881/77601628-5eb94d80-6f5f-11ea-86c3-8a009aa5bc92.png)

**Comment by frankwswang** [comment]
Could you please illustrate the meaning of each element in `lstyle = [[1, 1].*3.0mm, [5, 2, 3, 2].*2.0pt]`?

Thank you!

**Comment by frankwswang** [comment]
Thank you! This is very helpful!
