### ISSUE TITLE
Possible improvements for panel border

### ISSUE THREAD

**Issue by frankwswang** [GiovineItalia/Gadfly.jl#1407]
When I added a border to the panel of the plot using `panel_stroke=colorant"black"`. I noticed that the lines and the grids are on the top of the borders, which seems not very pretty. Is this intended or will it be fixed in the future? Also, I wonder if you can add another function to adjust the thickness of the border. Thank you!

![0001](https://user-images.githubusercontent.com/41162655/77805611-c0111780-7058-11ea-8cbc-78416e7ad0c8.jpg)

**Comment by Mattriks** [comment]
That' the current default, but it should be possible to add something like 
`Theme(grid_line_order= )`

**Comment by frankwswang** [comment]
Hi. Thank you for the change! However, the curves with different colorkeys are still on the top of the borders. I wonder wouldn't it be better to create a function that alters the order of the border lines instead of the grid lines?  like `panel_line_order`? Thank you!
