### ISSUE TITLE
test Gadfly

### ISSUE THREAD

**Issue by WeishengLiu-edu** [GiovineItalia/Gadfly.jl#1409]
(@v1.4) pkg> test Gadfly
    Testing Gadfly
┌ Error: Pkg.Resolve.ResolverError("empty intersection between Cairo@1.0.2 and project compatibility 0.7-0.8", nothing)
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:1365

**Comment by bjarthur** [comment]
does it work in a fresh environment?

**Comment by WeishengLiu-edu** [comment]
Yes, it is OK. Thank you!


In addition, does Julia software itself have updated commands? In this case, there is no need to uninstall the old version and reinstall the new version when the new version is released.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ben Arthur"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 上午9:34
收件人:&nbsp;"GiovineItalia/Gadfly.jl"<Gadfly.jl@noreply.github.com&gt;;
抄送:&nbsp;"Liu"<wsliu_edu@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GiovineItalia/Gadfly.jl] test Gadfly (#1409)





 
does it work in a fresh environment?

**Comment by bjarthur** [comment]
i'm not sure what you mean by "updated commands".  can you clarify?

**Comment by WeishengLiu-edu** [comment]
For now, assuming Julia1.5 is released, I have to uninstall Julia1.4 first, and then install Julia1.5. But what I need is to upgrade Julia1.4 to Julia1.5 directly with a command.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ben Arthur"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 上午10:07
收件人:&nbsp;"GiovineItalia/Gadfly.jl"<Gadfly.jl@noreply.github.com&gt;;
抄送:&nbsp;"Liu"<wsliu_edu@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GiovineItalia/Gadfly.jl] test Gadfly (#1409)





 
i'm not sure what you mean by "updated commands".  can you clarify?

**Comment by Mattriks** [comment]
You may find hints on [Julia Discourse](http://discourse.julialang.org/) about upgrading:
https://discourse.julialang.org/search?q=julia%20upgrade%20jill
