### ISSUE TITLE
Error in xlabel, with unicode characters and subscript

### ISSUE THREAD

**Issue by wilburtownsend** [GiovineItalia/Gadfly.jl#1410]
Guide.xlabel("γ<sub>1</sub>") throws a StringIndexError.

See this discussion of a related issue: https://stackoverflow.com/questions/51977406/string-index-error-julia

**Comment by Mattriks** [comment]
I don't see this issue with Gadfly v1.2:
```julia
using Cairo, Gadfly
p = plot(x=1:5, y=rand(5), Geom.point, Guide.xlabel("γ₁") )
draw(PNG(4inch, 3inch), p)
```
![issue1410](https://user-images.githubusercontent.com/18226881/78466036-36d89f80-7740-11ea-869e-020bf28013fb.png)


The stackoverflow link doesn't show that the problem originates in Gadfly, so the next step is to search the Julia issues page:
https://github.com/JuliaLang/julia/issues?q=StringIndexError

**Comment by wilburtownsend** [comment]
Sorry -- rather than the character 1, I meant to use \<sub\> tags. Here is a breaking example:
```
p = plot(x=1:5, y=rand(5), Geom.point, Guide.xlabel("γ<sub>1</sub>") )
```

**Comment by Mattriks** [comment]
This works for me (Gadfly v1.2, Julia 1.3):
```julia
using Cairo, Gadfly
p = plot(x=1:5, y=rand(5), Geom.point, Guide.xlabel("γ<sub>1</sub>") )
draw(PNG(4inch, 3inch), p)
```
![issue1410](https://user-images.githubusercontent.com/18226881/78471258-49200100-7773-11ea-95e3-dfee495e14bf.png)

What is your `versioninfo()` ?

**Comment by wilburtownsend** [comment]
Ok this seems to be a compatibility issue with Fontconfig -- sorry, should have debugged this more myself before posting here.

Here is breaking code:
```
julia> using Gadfly

julia> import Cairo, Fontconfig

julia>  plot(x=1:5, y=rand(5), Geom.point, Guide.xlabel("γ<sub>1</sub>") )

(process:29945): Pango-WARNING **: 08:21:56.260: pango_layout_set_markup_with_accel: Error on line 1 char 23: “/” is not a valid character following the close element name “sub<”; the allowed character is “>”
Error showing value of type Plot:
ERROR: StringIndexError("γ1", 2)
```

In case it's helpful:
```

julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 9 entries:
  "CSV"           => v"0.5.26"
  "Compose"       => v"0.8.2"
  "Fontconfig"    => v"0.4.0"
  "Cairo"         => v"1.0.2"
  "Distributions" => v"0.22.6"
  "DataFrames"    => v"0.20.2"
  "RDatasets"     => v"0.6.6"
  "Colors"        => v"0.11.2"
  "Gadfly"        => v"1.2.0"

julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by Mattriks** [comment]
With Fontconfig 0.4, on windows I see a "base 64 binary data warning" but no error, & I can output to a file, no problems. 

Compose.jl, the graphics package that Gadfly plots on,  currently supports Fontconfig 0.3 ([see Project.toml](https://github.com/GiovineItalia/Compose.jl/blob/1749b92d21b97820550af7a5b2bb7534f7886297/Project.toml#L24)), and is not tested with Fontconfig 0.4.  Also, the problem may lie in Fontconfig, see the discussion at JuliaGraphics/Cairo.jl#312.

You can go revert to Fontconfig 0.3 by doing:
```
]add Fontconfig@0.3
```
Sometimes it's good to delete the Fontconfig package directory first (~/.julia/packages/Fontconfig).

**Comment by wilburtownsend** [comment]
The error is still there when I revert to Fontconfig 0.3.

In case it's helpful: the error disappears when I add a space between the `γ` and the `<sub>`, 
as in `plot(x=1:5, y=rand(5), Geom.point, Guide.xlabel("γ <sub>1</sub>") )`.

**Comment by bjarthur** [comment]
possibly related to https://github.com/GiovineItalia/Compose.jl/pull/391 ?  to see, `]dev Compose`, or do *not* import Cairo and Fontconfig and save to SVG.

**Comment by wilburtownsend** [comment]
`]dev Compose` causes this error:
```
(v1.3) pkg>  dev Compose
[ Info: Path `/Users/wtownsend/.julia/dev/Compose` exists and looks like the correct package, using existing path
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Colors [5ae59095]:
 Colors [5ae59095] log:
 ├─possible versions are: [0.9.0, 0.9.2-0.9.6, 0.10.0-0.10.2, 0.11.0-0.11.2, 0.12.0] or uninstalled
 ├─restricted to versions 0.9 by Compose [a81c6b42], leaving only versions [0.9.0, 0.9.2-0.9.6]
 │ └─Compose [a81c6b42] log:
 │   ├─possible versions are: 0.7.4 or uninstalled
 │   └─Compose [a81c6b42] is fixed to version 0.7.4
 └─restricted to versions 0.11.2 by an explicit requirement — no versions left
```

I'm not sure I understand -- it looks like Compose is demanding I use Colors 0.7.4? Not sure why that'd be the case for `]dev Compose` but not `using Compose`. (I'm not super familiar with the Julia package manager.)

**Comment by tomyun** [comment]
I had a similar problem to this issue where color key title including unicode string was occasionally clipped away with pango warning. I believe GiovineItalia/Compose.jl#393 should fix this.

**Comment by bjarthur** [comment]
in the first line of your error message it says "...Compose\` exists..." on the first line, which means you have already previously done a `]dev Compose`, which means you are now telling it you want to use that same version of the master branch that you checked out a long time ago, which is by now out of date.  the current version of Compose is [compatible with Colors up to v0.12](https://github.com/GiovineItalia/Compose.jl/blob/master/Project.toml#L21).

to fix this, you need to `cd /Users/wtownsend/.julia/dev/Compose; git pull` and then back at the julia prompt `]dev Compose` again.

**Comment by Mattriks** [comment]
To use the latest changes in Compose (without dev) you can also do:
```
]add Compose#master
```
Then `up Compose`  will automatically give you the latest changes in Compose#master.  See the [Julia Package manager docs](https://julialang.github.io/Pkg.jl/v1/managing-packages.html#Adding-registered-packages-1).

**Comment by wilburtownsend** [comment]
Ok thanks for the help with the package manger. This code leads to no error:
```
]dev Compose
using Gadfly
p = plot(x=1:5, y=rand(5), Geom.point, Guide.xlabel("γ<sub>1</sub>") )
draw(SVG("test-image.svg"), p)
```
does not lead to any errors

**Comment by bjarthur** [comment]
so you're good then?  if so, please close this issue.  we'll tag a new release of Compose at some point so others don't have the same problem.
