### ISSUE TITLE
Legend title getting cut off

### ISSUE THREAD

**Issue by tomyun** [GiovineItalia/Gadfly.jl#1417]
```julia
using Gadfly
import Cairo, Fontconfig

using DataFrames
df = DataFrame(x=[1,2], y=[1,2], c=[1,2])

plot(df, x=:x, y=:y, color=:c, Guide.colorkey(title="CO2 (μmol mol⁻¹)"))
```

would result into a color key title getting cut off at the end with a warning message from pango.

![before](https://user-images.githubusercontent.com/906626/79183626-cdebca00-7dc6-11ea-9256-9d08ccdc8f24.png)

```
(process:51946): Pango-WARNING **: 20:37:22.372: pango_layout_set_markup_with_accel: Error on line 1 char 25: Invalid UTF-8 encoded text in name — not valid “CO2 (μmol mol\xe2\x81”
```

This warning could potentially show up whenever using Unicode symbols in a text label under Pango layout and get its label width smaller than expected, but the glitch seemed only visible in a narrow layout used in such as color key title. A related issue I found was #1410.

I posted a PR for this issue in Compose.jl: GiovineItalia/Compose.jl#393
Here is the same plot after fix applied. No more pango warning.

![after](https://user-images.githubusercontent.com/906626/79183646-dba14f80-7dc6-11ea-8b8c-50fedf047ed4.png)

**Comment by bjarthur** [comment]
https://github.com/GiovineItalia/Compose.jl/pull/393 has been merged.
