### ISSUE TITLE
Make Gadfly compatible with the new versions of Turing

### ISSUE THREAD

**Issue by dfioravanti** [GiovineItalia/Gadfly.jl#1440]
Would it be possible to update the version of "CoupledFields" used by Gadfly? Right now it makes it impossible to install the new versions of Turing.  [Here](https://github.com/GiovineItalia/Gadfly.jl/files/4642250/log.txt) you can find the log of what happens when one tries to force install Turing@0.12 on a fresh julia install.

Thanks for this amazing package

**Comment by Mattriks** [comment]
It's been updated on Gadfly#master, so just do `]add Gadfly#master`.  We should do a minor release of Gadfly soon.

**Comment by dfioravanti** [comment]
Cool, thanks a lot =)
