### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by juliohm** [GiovineItalia/Gadfly.jl#1442]
I've noticed that the master branch is 127 commits ahead of the latest release. Any plans to submit a new release in the following weeks?

**Comment by Mattriks** [comment]
Gadfly v1.2 was released on 16th Feb, but for some reason we didn't get nice [release info](https://github.com/GiovineItalia/Gadfly.jl/releases) for v1.2.  `Gadfly#master` is only 38 commits ahead of v1.2 (there was also a v1.2.1 on March 22)

**Comment by juliohm** [comment]
Thank you for clarifying it. Could you please explain the release model adopted by Gadfly?

Just sharing that I finished a visualisation with it for a paper, and it was nice to learn more about the project. Appreciate your help. We've added the master branch of Gadfly in the environment for reproducibility.

**Comment by Mattriks** [comment]
I think minor releases every 4 months is good (patch releases might happen in between), see [Julia's release model](https://julialang.org/blog/2019/08/release-process/).  There is also a NEWS.md file (https://github.com/GiovineItalia/Gadfly.jl), to see what's in the next minor release.

**Comment by juliohm** [comment]
Thank you @Mattriks , as usual very insightful and professional. I will close this issue for now. Looking forward to the next release.
