### ISSUE TITLE
Out of curiosity, when does gadfly use data-melting?

### ISSUE THREAD

**Issue by BrucePBon** [GiovineItalia/Gadfly.jl#1451]
I am using Gadfly and decided to look at Gadfly's source code to get an appreciation of how figures are rendered. I found the concept of data-melting interesting. In R data-melting seems to be an important issue when using  ```ggplot```. I don't know, I've never used it. But I am interested in understanding what its role in Gadfly is.

Looking at mapping.jl I can't see how a user can pass a Col.GroupedColumn, Col.GroupedColumnValue or Row.GroupedColumnRowIndex among the mappings of ```plot(...)``` or ```layer(...)```. 

https://github.com/GiovineItalia/Gadfly.jl/blob/fe95b773b307341a79dead50f1db289a9aa5d826/src/mapping.jl#L219-L223

As far as I understand, mappings that aren't found among the list of possible aesthetics are ignored. Because there is no aesthetic with these types (Col.GroupedColumn, Col.GroupedColumnValue or Row.GroupedColumnRowIndex ), I can't image when the previous condition can be true, leading to the only call (as far as I know) to ```meltdata()```. 

https://github.com/GiovineItalia/Gadfly.jl/blob/fe95b773b307341a79dead50f1db289a9aa5d826/src/mapping.jl#L227-L231

I have only been looking at the source code for a couple days, so I might be missing some important design principle.

**Comment by Mattriks** [comment]
Here's an example, using the same dataset as in the Gadfly docs [wide-form example](http://gadflyjl.org/dev/man/plotting/#Wide-formatted-data-1):
```julia
births = RDatasets.dataset("HistData", "Arbuthnot")[:,[:Year, :Males, :Females]]
cv = Col.value(:Males, :Females)
@show typeof(cv)
p = plot(births, x=:Year, y=cv, color=Col.index(:Males, :Females), Geom.blank)
Gadfly.evalmapping!(p.mapping, p.data_source, p.data)
```

**Comment by BrucePBon** [comment]
I completely missed that part of the documentation. Thanks :) that's very helpful

**Comment by Mattriks** [comment]
Closing this issue, please reopen if you have more questions
