### ISSUE TITLE
manual_color_key fails when handed color = Colorant[RGB(...), RGB(...)]

### ISSUE THREAD

**Issue by NicholasWMRitchie** [GiovineItalia/Gadfly.jl#1454]
This fails on version 1.3.0 but not 1.2.1

    Guide.manual_color_key("Title",["Item 1","Item 2"], Colorant[RGB(1.0,0.0,0.0),RGB(0.0,1.0,0.0)])

with
    ERROR: TypeError: in new, expected Array{Colorant,1}, got Array{RGB{Float64},1}

    
I think the problem is `parse_color(...)` in `Compose`

    parse_colorant(c::Union{Tuple,Vector}) = [parse_colorant(x) for x in c]

which should be

    parse_colorant(c::Union{Tuple,Vector}) = Colorant[parse_colorant(x) for x in c]

In the meanwhile, adding 
    
    Compose.parse_colorant(c::Array{<:Colorant,1}) = convert(Array{Colorant,1}, c)

resolves the issue without modifying `Compose`

**Comment by NicholasWMRitchie** [comment]
Probably a better way to handle this would be to change `manual_color_key` to take a

    color::Array{<:Colorant,1}

rather than a

    color::Colorant[]

**Comment by Mattriks** [comment]
I'm not seeing this error. What version of Colors and Compose do you have (I have Colors 0.12.2 and Compose#master)  ?:
```julia
p = plot(
    Guide.manual_color_key("Title",["Item 1","Item 2"], [RGB(1.0,0.0,0.0),RGB(0.0,1.0,0.0)],
        pos=[0.5, 1.5])
)
draw(PNG(), p)
```
![issue1454](https://user-images.githubusercontent.com/18226881/84568268-83d09600-adc1-11ea-8066-f51a167d60a9.png)

**Comment by NicholasWMRitchie** [comment]
v0.8.2

> 
> 
> I'm not seeing this error. What version of Colors and Compose do you have (I have Colors 0.12.2 and Compose#master) ?:
> 
> ```julia
> p = plot(
>     Guide.manual_color_key("Title",["Item 1","Item 2"], [RGB(1.0,0.0,0.0),RGB(0.0,1.0,0.0)],
>         pos=[0.5, 1.5])
> )
> draw(PNG(), p)
> ```
> 
> ![issue1454](https://user-images.githubusercontent.com/18226881/84568268-83d09600-adc1-11ea-8066-f51a167d60a9.png)
> 
> Also as a side note, checkout the new options for the color arg `?Guide.manual_color_key`, and see the [new examples](http://gadflyjl.org/dev/gallery/guides/#%5BGuide.manual_color_key%5D(@ref),-%5BGuide.manual_discrete_key%5D(@ref)-1).

[a81c6b42] Compose v0.8.2

**Comment by Mattriks** [comment]
What about version of Colors?

**Comment by NicholasWMRitchie** [comment]
It must be something in my code.
    > using Gadfly
    > using Colors
    > Guide.manual_color_key("Title",["Item 1","Item 2"], [RGB(1.0,0.0,0.0),RGB(0.0,1.0,0.0)])

seems to work fine.  However, similar code within my package doesn't.   I'll have to investigate further.

**Comment by NicholasWMRitchie** [comment]
Colors 0.12.2

**Comment by NicholasWMRitchie** [comment]
I remain puzzled about why my code is failing but I believe that it is my problem and not a bug in Gadfly.
Thanks for your quick response @Mattriks.  Love the library!
