### ISSUE TITLE
error on drawing a horizontal line

### ISSUE THREAD

**Issue by yordiak** [GiovineItalia/Gadfly.jl#1457]
hello,

i am using Gadfly (v1.3) and julia (v1.4.2) on a wn10 64bit machine 

the code
```
f(x)=x/(1-x)
plot(f,0,0.8, yintercept=1.5,  Geom.hline(style=:dot))
```
produces an error

> Couldn't process recipe args: (typeof(f), Int64, Float64, Gadfly.Geom.HLineGeometry)

what am I missing?

**Comment by Mattriks** [comment]
Gadfly mainly expects vectors for aesthetics, even one-length vectors. This works for me:
```julia
using Gadfly
f(x)=x/(1-x)
p = plot(f,0,0.8, yintercept=[1.5],  Geom.hline(style=:dot))
draw(PNG(), p)
```
Also see #1430 which lists the current syntaxes available for the color aesthetic.

**Comment by Mattriks** [comment]
Closing this issue because it's been answered here and on [stackoverflow](https://stackoverflow.com/questions/62412002/horizontal-line-in-gadfly)
