### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by fanyuan-lab** [GiovineItalia/Gadfly.jl#1464]
It seems that Gadfly still cannot support latex form of axis. I think that is quite important for researchers who want to plot figures of papers.

**Comment by Mattriks** [comment]
See #1094 and GiovineItalia/Compose.jl#369 (Compose is the graphics package that Gadfly uses).

**Comment by fanyuan-lab** [comment]
Thanks a lot. By the way, why to_latex("\\lambda_i") works, but to_latex("\\lambda_A") does not work. I mean sub of Capital character doesn't support.

**Comment by Mattriks** [comment]
Yes, not all all characters have been added to [julia unicode](https://docs.julialang.org/en/v1/manual/unicode-input/) superscript/subscript.
An alternative is to use [pango markup](https://developer.gimp.org/api/2.0/pango/PangoMarkupFormat.html). You can mix julia unicode and pango e.g. `"V<sup>×10⁻⁵</sup>"`.

**Comment by fanyuan-lab** [comment]
Thanks for your patience. That is nice.

**Comment by fanyuan-lab** [comment]
Sorry to disturb again. to_latex("\\mu<sub>A</sub>") does not work as well.

**Comment by Mattriks** [comment]
Gadfly relies on julia itself or other packages to provide symbol support.  In a julia REPL (or Jupyter) try typing "\mu" (without the quote marks) and press tab key immediately. This will give you the symbol μ.   You can copy and paste the symbol into any julia code e.g. `"μ<sub>A</sub>"`.  If you really want to use  the UnicodeFun.jl package, and something doesn't work, then you should open an issue there: https://github.com/SimonDanisch/UnicodeFun.jl/issues.

**Comment by Mattriks** [comment]
Closing this now because the info is in #1094
