### ISSUE TITLE
Perhaps tag new patch version?

### ISSUE THREAD

**Issue by dehann** [GiovineItalia/Gadfly.jl#1482]
Hi, would it perhaps be possible to tag patch version v1.3.1 please?

EDIT: following fix to #1466

**Comment by dehann** [comment]
Hi, a friendly bump on this issue?

**Comment by ChrisRackauckas** [comment]
Friendly bump? This was identified as the source of an issue on the Slack and Discourse. The DataStructures 0.18 compatibility commit is particularly necessary to get tagged.

**Comment by dehann** [comment]
Hi @bjarthur , thank you very much!
