### ISSUE TITLE
Infer more defaults for univariate distributions

### ISSUE THREAD

**Issue by rikhuijzer** [GiovineItalia/Gadfly.jl#1489]
I would like to quickly visualise univariate distributions. However, currently it requires quite a lot of code to do so. I have found two possible roads to plot this distribution.

One way is via `Stat.func`
```
using Distributions
using Gadfly

n = Normal(10, 1)
plot(xmin = [quantile(n, 0.01)], xmax = [quantile(n, 0.99)], y = [x -> pdf(n, x)], 
    Stat.func, Geom.line, Guide.xlabel("x"), Guide.ylabel("density")
)
```
![image](https://user-images.githubusercontent.com/20724914/97112683-fe051580-16e5-11eb-9e96-702e8a6ce4ef.png)
which is quite nice; it also correctly handles multiple distributions when passing multiple values to `xmin` and `xmax`.

![image](https://user-images.githubusercontent.com/20724914/97112923-512b9800-16e7-11eb-90c5-6542ecd16b0b.png)

Another way could be via `Stat.density`. This would seem the most obvious candidate for me, but it appears to calculate the density of the density. 

## Attempt to create a pull request

I have tried to create a pull request for this feature. Unfortunately, I am now a little bit stuck on the solution. I have tried to catch the "poorly" defined distributions after 
```
statistics = collect(statistics)
```
in `src/Gadfly.jl` and then quickly ensure that `Stat.apply_statistic(statistics, scales, coord, plot_aes)` jumps to `apply_statistic(stat::FunctionStatistic, ...)` with 
```
if eltype(plot_aes.y) <: UnivariateDistribution && plot_aes.x == [1]
    statistics = [Stat.func() for y in plot_aes.y]
end
```
my plan was to prepare the plot for the `apply_statistic` method in this addition, but I get 
```
MethodError: no method matching apply_statistics(::Gadfly.Stat.FunctionStatistic, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics)
```
I have checked all the types and they match even though Julia report that they don't.

**Comment by bjarthur** [comment]
would be easiest for us to help debug if you put your code into a pull request so we could see it

**Comment by Mattriks** [comment]
Some features of Gadfly which support Distributions include [Stat.qq](http://gadflyjl.org/stable/gallery/statistics/#[Stat.qq](@ref)-1) and `Stat.ellipse` (used by [Geom.ellipse](http://gadflyjl.org/stable/gallery/geometries/#[Geom.ellipse](@ref)-1)).  Those Stats show the general way that support for Distributions can be included in Gadfly.  To plot UnivariateDistributions, you could make a `Stat.distribution`, which outputs to `Geom.ribbon` (effectively automating the first plot shown in [Stat.density](http://gadflyjl.org/stable/gallery/statistics/#[Stat.density](@ref)-1)).  When proposing a new PR, it's good to give a design outline!

Note that Gadfly also some special signatures for [plots](http://gadflyjl.org/stable/man/plotting/#Functions-and-Expressions-1) (and layers), so this is possible:
```
d1, d2 = Normal.([10, 0],1)
p = plot(layer([x->pdf(d1, x), x->pdf(d2, x)], -3, 13))
```

**Comment by rikhuijzer** [comment]
I couldn’t figure this one out in a few hours and have some other priorities first. I hope to come up with a pull request in a few weeks. Thanks for the comments 🙂
