### ISSUE TITLE
transparency affects color key

### ISSUE THREAD

**Issue by IgorDouven** [GiovineItalia/Gadfly.jl#1531]
If I add transparency to a plot, it also affects the color key. I cannot find a way to override it. Here is a MWE:
```julia
v = randn(1000)
plot(x=v, Stat.density, Geom.polygon(fill=true, preserve_order=true),
    xintercept=[-1, 1],
    Geom.vline(color="MidnightBlue"),
    Guide.manual_color_key("", ["Some interval"], ["rgba(25, 25, 112, 1.)"]),
    Theme(default_color="lightskyblue", line_width=2pt, alphas=[.3]))
```
The transparency is meant to pertain to the fill. It doesn't pertain to the vlines, but then also shouldn't pertain to the color key, which pertains to the vlines (in actuality I'm showing several intervals).

Also, is there a way to show the vlines 'on top of' the fill? Without the transparency, they would be partly hidden.

**Comment by Mattriks** [comment]
Layer order matters, and `alphas` in `Theme` affects the colorkey, but `alpha` in layers does not:

```julia
plot(x=v,
    layer(xintercept=[-1, 1], Geom.vline(color="MidnightBlue")),
    layer(Stat.density, Geom.polygon(fill=true, preserve_order=true), alpha=[.3]),
    Guide.manual_color_key("", ["Some interval"], ["rgba(25, 25, 112, 1.)"]),
    Theme(default_color="lightskyblue", line_width=2pt)
)
```

The bit about layer order is in the [Gadfly docs](http://gadflyjl.org/stable/man/compositing/#Layers) (at the bottom of page).

**Comment by IgorDouven** [comment]
Thank you, and sorry for overlooking this in the documentation.
