### ISSUE TITLE
Geom.label positioning with stacked bar plot

### ISSUE THREAD

**Issue by tomyun** [GiovineItalia/Gadfly.jl#1547]
```julia
using DataFrames
using Gadfly

df = DataFrame(
    x = [:A, :A, :A, :B, :B, :B],
    y = [0.2, 0.3, 0.5, 0.1, 0.6, 0.3],
    l = ["0.2", "0.3", "0.5", "0.1", "0.6", "0.3"],
    c = [:a, :b, :c, :a, :b, :c],
)
plot(df, x = :x, y = :y, color = :c, label = :l, Geom.label, Geom.bar(position = :stack))
```

![label](https://user-images.githubusercontent.com/906626/128249236-ca1c47f8-1083-4664-b946-eb1b36b3cecb.png)

Couldn't find a way to get correct position for labels in stacked bar plot.

**Comment by Mattriks** [comment]
The trick here is to use [Stat.dodge](http://gadflyjl.org/stable/gallery/statistics/). For Geoms+Stats outside layers [order matters](http://gadflyjl.org/stable/man/compositing/#Layers).
I also had to add 'Scale.x_discrete', not sure why and I should investigate.

```
p = plot(df, x=:x, y=:y, color=:c, label=:l, 
    Geom.label(position=:centered), Stat.dodge(position=:stack),
    Geom.bar(position=:stack), Scale.x_discrete
)
```
![issue1547](https://user-images.githubusercontent.com/18226881/128270475-94986190-126a-4757-bc2b-8f1730a9dfa6.png)

**Comment by tomyun** [comment]
`Stat.dodge` with `Scale.x_discrete` worked great for me. Thanks for the tip!

**Comment by Aina29** [comment]
@Mattriks how to do it when using Geom.subplot_grid()?
