### ISSUE TITLE
Gadfly no interactivity in VSCode plot pane (and how to fix it)

### ISSUE THREAD

**Issue by MrVPlusOne** [GiovineItalia/Gadfly.jl#1548]
Hi, I noticed this issue today when trying out Gadfly, and it looks like [others are experiencing the same issue](https://discourse.julialang.org/t/interactive-gadfly-plots-in-vscode-plot-pane/59020) as well. It looks like it's caused by VSCode recently dropping support for displaying MIME"text/html" and can be fixed by simply adding
```julia
Base.show(io::IO, ::MIME"juliavscode/html", p::Gadfly.Plot) = show(io, "text/html", p)
``` 
Can anyone please merge this change into the master branch so that others don't have to experience the same issue? I can also send a pull request if needed. Thanks!

**Comment by bjarthur** [comment]
a PR would be great

**Comment by MrVPlusOne** [comment]
PR sent!
