### ISSUE TITLE
Error regarding Wine - Artix Linux

### ISSUE THREAD

**Issue by BuddhiLW** [GiovineItalia/Gadfly.jl#1550]
When I use Gadfly to plot the following happens

```jl
julia> Gadfly.plot(y=[1,2,3])
/usr/bin/env: 'wine': No such file or directory
Opening in existing browser session.
```

Then, the it do renders in the browser.

![pic-selected-210810-2009-00](https://user-images.githubusercontent.com/59554283/128946199-6b225316-1ca5-4014-9b70-b2083b6cdae9.png)

I would like that Gadfly used my external viewer. Is there a way to configure the package so to use GTK/GKS QtTerm/sxiv etc?

**Comment by bjarthur** [comment]
nope.  gadfly is designed to output SVG or PDF and then open in a browser.
