### ISSUE TITLE
Gadfly labels overlapping and not readable

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#1571]
I am trying to plot a figure which is very elongated. However, the Gadfly labels overlap and are not readable.

See below:

```
Gadfly.draw(Gadfly.PDF("a.pdf"), Gadfly.spy(rand(1000,10), Gadfly.Scale.y_discrete(labels=i->string(i)), Gadfly.Guide.yticks(label=true), Gadfly.Theme(minor_label_font_size=0.3Gadfly.pt, major_label_font_size=0.3Gadfly.pt, key_title_font_size=0.3Gadfly.pt, key_label_font_size=0.3Gadfly.pt)))
```

**Comment by Mattriks** [comment]
I can't see your plot, so I can't tell if this is the same as #859?  (See also #1385, point 4).

**Comment by montyvesselinov** [comment]
The same problem occurs regardless if the plot is dumped as pdf or png or jpg. The only reason i am using PDF is that it is not a raster format and the overlap is visible. Here is a screenshot of the PDF
<img width="273" alt="Screen Shot 2022-02-18 at 9 10 35 AM" src="https://user-images.githubusercontent.com/5632376/154719840-e42bdbd2-69ac-4716-906e-c4d3897c778d.png">
:

**Comment by montyvesselinov** [comment]
Here is the actual PDF:

[a.pdf](https://github.com/GiovineItalia/Gadfly.jl/files/8098625/a.pdf)

**Comment by montyvesselinov** [comment]
Here is how PNG looks like
![a](https://user-images.githubusercontent.com/5632376/154720102-95b39cd6-2abe-4d19-bd0a-67bd4b523348.png)
:

**Comment by montyvesselinov** [comment]
I think the problem is related to 

https://github.com/GiovineItalia/Gadfly.jl/issues/859#issuecomment-570852643

**Comment by montyvesselinov** [comment]
is there a way to trick the code to work in this case?! Changing the canvas size?! Using a different font?!

**Comment by bjarthur** [comment]
`set_default_plot_size(10cm,200cm)` or use `PDF("a.pdf",10cm,200cm)`

**Comment by montyvesselinov** [comment]
Both options below fail. The labels are overlapped:

```
Gadfly.set_default_plot_size(10Gadfly.cm,200Gadfly.cm)
```

```
Gadfly.draw(Gadfly.PDF("a.pdf", 10Gadfly.cm, 100Gadfly.cm), Gadfly.spy(rand(1000,10), Gadfly.Scale.y_discrete(labels=i->string(i)), Gadfly.Guide.yticks(label=true), Gadfly.Theme(minor_label_font_size=0.3Gadfly.pt, major_label_font_size=0.3Gadfly.pt, key_title_font_size=0.3Gadfly.pt, key_label_font_size=0.3Gadfly.pt)))
```

**Comment by bjarthur** [comment]
works for me:

<img width="122" alt="Screen Shot 2022-02-19 at 2 33 50 PM" src="https://user-images.githubusercontent.com/1538268/154816286-0dc5a448-fb49-4572-80e2-6d4f982b8f68.png">

**Comment by montyvesselinov** [comment]
I agree it works!  Sorry! How to remove the gray lines (ticks) next to the numbers in the figure above?! 

```
Gadfly.Guide.yticks(label=true, ticks=nothing)
```

Above disable both labels and ticks.

**Comment by bjarthur** [comment]
`Theme(grid_line_width=0mm)`

**Comment by montyvesselinov** [comment]
Thank you!
