### ISSUE TITLE
Why prepare_display is still exported?

### ISSUE THREAD

**Issue by ulysses4ever** [GiovineItalia/Gadfly.jl#1578]
`prepare_display` is exported from `Gadfly` but there's no method definitions.
https://github.com/GiovineItalia/Gadfly.jl/blob/423f170cc5fa4966f1dfc31640464e02c2e4e588/src/Gadfly.jl#L25
Is it expected that this may be useful for clients somehow (how?) or is it simply an oversight?

**Comment by bjarthur** [comment]
just an oversight.  the method definition was deleted in fd8fdfbce17383e59d38b1c87d745ff58310ab5e. would you care to submit a PR to remove the export?

**Comment by ulysses4ever** [comment]
Sure! #1591
