### ISSUE TITLE
Documentation website redirect

### ISSUE THREAD

**Issue by nathanrboyer** [GiovineItalia/Gadfly.jl#1580]
http://gadflyjl.org/ now takes me to the website shown below.
![image](https://user-images.githubusercontent.com/65452054/165989901-e78fccb9-6bb6-4764-96a6-72ff36030490.png)

**Comment by Mattriks** [comment]
yep, it's happened before: https://github.com/GiovineItalia/Gadfly.jl/issues/832

**Comment by dcjones** [comment]
Sorry about that, the domain name didn't auto-renew because it was under an old credit card. I've re-registered it now, and should be back to normal once the DNS updates propagate.
