### ISSUE TITLE
How to make Stat.x_jitter work with Geom.subplot_grid

### ISSUE THREAD

**Issue by rkmalaiya** [GiovineItalia/Gadfly.jl#1581]
Hello,
I posted this issue [in discourse](https://discourse.julialang.org/t/how-to-make-stat-x-jitter-work-with-geom-subplot-grid/80152) but couldn't come to a solution. Hence, I am re-posting the same issue here.

The plot that I am trying to make requires me to jitter the points in a grid plot. But I cannot figure out how? The code example below replicates my situation. Please suggest what may I be missing?

Fake Data:

```
df_plot = DataFrame(
model = repeat([“M1”,“M2”, “M3”, “M4”, “M5”, “M6”,“M7”,“M8”],inner=5),
metric = repeat([“Me1”,“Me2”, “Me3”, “Me4”],outer=10),
sample = repeat(1:2,outer=20),
value=rand(40)
)
```
![image](https://user-images.githubusercontent.com/3996928/167454991-f4e72561-b156-41a5-aefd-e6d4683abff5.png)

**A plot with jitter but without a grid**
I am putting this plot here to show how the jitter looks in my data
_Code_
```
Gadfly.plot(df_plot,
x=:sample,
color = :model,
y=:value,
Geom.point, Stat.x_jitter(range=0.4),
Scale.x_discrete
)
```
_Plot_
![image](https://user-images.githubusercontent.com/3996928/167455112-d3a88004-b5cb-4652-adb3-03224e34ee58.png)

**Now, if I add Geom.subplot_grid, the jitter functionality seems to stop working**
_Code_
```
Gadfly.plot(df_plot,
x=:sample,
color = :model,
xgroup = :metric, # Added this new parameter
y=:value,
Geom.subplot_grid(Geom.point, Stat.x_jitter(range=0.4), 
free_x_axis = true), #Updated to subplot_grid
Scale.x_discrete
)
```
_Plot_
![image](https://user-images.githubusercontent.com/3996928/167455238-3abff504-bcb0-4e71-acfe-c1020b25b28f.png)

I also tried to put x_jitter out of subplot_grid, but it doesn’t work! Please advise.

```
Stat.x_jitter(range=0.2),
Geom.subplot_grid(Geom.point,
free_x_axis = true), #Updated to subplot_grid
```

**Comment by Mattriks** [comment]
I already added a link to your discourse post in https://github.com/GiovineItalia/Gadfly.jl/issues/1516#issuecomment-1111603725 (so I can check it for #1520, which should fix it).
