### ISSUE TITLE
Alpha for Geom.line and Geom.path

### ISSUE THREAD

**Issue by arnold-c** [GiovineItalia/Gadfly.jl#1589]
Apologies if this is covered elsewhere, but I couldn't find it in the issues or the documentation. Is it possible to enable `Theme(alphas = [])` for `Geom.line` and `Geom.path`? It would be very helpful for situations where trajectories are simulated and are overlayed e.g. stochastic disease modeling. Small reprex below (`alphas` works as expected when the geom is changed to `Geom.point`, for example).

Thanks very much

```
test = DataFrame(
  x = 1:100,
  y = rand(100)
)

Gadfly.plot(
  test,
  x = :x,
  y = :y,
  Geom.line,
  Theme(alphas = [0.1])
)
```

**Comment by Rapsodia86** [comment]
This is not a direct solution you are asking for, but maybe will help. 
See: https://discourse.julialang.org/t/gadfly-how-to-change-width-and-opacity-of-lines-in-geom-density/37823/2
Using Colors library, you can set a style:

```
using Gadfly
using Colors

test = DataFrame(
    x=1:100,
    y=rand(100)
)

Gadfly.plot(
    test,
    x=:x,
    y=:y,
    Geom.line, style(
        default_color=RGBA(0.1, 0.1, 0.9, 0.3))
)


```

**Comment by arnold-c** [comment]
Thanks @Rapsodia8. Sorry for the follow up - I should have made a better reprex. I have more than one group that produce the colors. From the documentation it seems like I could use `plot(Scale.color_discrete_manual())` to set the colors, but I've only got it working when naming the colors. Is there a way to use `RGBA()` (and therefore specify the alphas)?

```
using Gadfly, Colors

test = DataFrame(
    x=1:100,
    y=rand(100),
    z = repeat(["a", "b"], outer = 50)
)

personal_theme = Theme(
  panel_fill="white",
  background_color = "white"
  )

Gadfly.plot(
    test,
    x=:x,
    y=:y,
    color = :z,
    Geom.line,
    personal_theme
    Scale.color_discrete_manual("red", "blue")
)
```

**Comment by arnold-c** [comment]
Thanks for your help. I was receiving the same error. I have updated the code to plot each series in a `for` loop. Code below in case it's of any help to others/please feel free to point out bad practices given my inexperience with Julia.

```
using Gadfly, Colors, DataFrames, DataFramesMeta

test = DataFrame(
    x = 1:100,
    y = rand(100),
    z = repeat(["a", "b"], outer = 50)
  )

test_colors = (
    a = RGBA(0.106,0.62,0.467, 0.5),
    b = RGBA(0.851,0.373,0.008, 0.5)
  )

personal_theme = Theme(
    panel_fill = "white",
    background_color = "white"
  )

test_plot = Gadfly.plot(personal_theme)
for state in collect(keys(test_colors))
    str_states = String(state)
    
    test_plot = push!(
        test_plot, 
        layer(
            @subset(test, :z .== str_states),
            x = :x,
            y = :y,
            Geom.line,
            style(default_color = test_colors[state])
        )
    )
end

test_plot
```

**Comment by Rapsodia86** [comment]
Thank you for the code. I hope 'alphas' will be working with Geom.line soon.

**Comment by Brinkhuis** [comment]
Using `color(RGBA(.. , .. , ..))` seems to work (Julia 1.7.2 and Gadfly 1.3.4).

```
test = DataFrame(
    x=1:100,
    y=rand(100),
    z = repeat(["a", "b"], outer = 50)
)

personal_theme = Theme(
  panel_fill="white",
  background_color = "white"
  )

Gadfly.plot(
    test,
    x=:x,
    y=:y,
    color = :z,
    Geom.line,
    personal_theme,
    Scale.color_discrete_manual(color(RGBA(0.3, 0.1, 0.6, 0.3)), color(RGBA(0.8, 0, 0.9, 0.2)))
)
```
<img width="503" alt="Screenshot 2022-06-07 at 19 30 12" src="https://user-images.githubusercontent.com/3044985/172445951-33d0f265-ef84-4d32-a57c-6523a3ea8e10.png">

**Comment by Rapsodia86** [comment]
True, does not throw the error, but also does not apply the transparency. color() just changes it from RGBA to RGB.

**Comment by bjarthur** [comment]
sorry for the delay in looking into this issue.  i've pushed a [PR](https://github.com/GiovineItalia/Gadfly.jl/pull/1603) which should fix it.  can you three please checkout the branch and make sure it works for you?
