### ISSUE TITLE
Gadfly not working for simple point plot

### ISSUE THREAD

**Issue by hcfugro** [GiovineItalia/Gadfly.jl#1602]
I'm working on wsl2. I'm not sure why this code doens't work. I dont know which file its looking for?

![image](https://user-images.githubusercontent.com/93892283/204183174-9cbc688b-c0d0-47ea-aac3-f3b08eeab354.png)

**Comment by Mattriks** [comment]
Gadfly is trying to open the plot in a browser, but I'm guessing it can't find a browser under wsl2.  A similar issue is raised [here with VScode](https://askubuntu.com/questions/1394366/issue-opening-html-code-via-browser-using-visual-studio-code), but it looks like you're using the Julia REPL. I included some [code here in Julia discourse](https://discourse.julialang.org/t/can-i-choose-display-software/29510) for opening Gadfly plots in chosen default software, maybe test it under wsl2?

**Comment by Mattriks** [comment]
@hcfugro Did you find a solution?  If so, please post here, to help other users that encounter this issue

**Comment by hcfugro** [comment]
> @hcfugro Did you find a solution? If so, please post here, to help other users that encounter this issue

Nope I couldnt resolve it

**Comment by hcfugro** [comment]
Stale and closing now
