### ISSUE TITLE
Question re wrapping Gadfly.jl functionality in Tidier.jl

### ISSUE THREAD

**Issue by kdpsingh** [GiovineItalia/Gadfly.jl#1611]
Dear package maintainers,

I have recently been working on a package Tidier.jl that aims to bring an R tidyverse-like API to Julia. Here's a link to the package: https://github.com/kdpsingh/Tidier.jl

The package is written using macros and serves as syntactic sugar on top of a DataFrames.jl backend, converting R-like expressions into valid DataFrames.jl code.

At some point, I would like to similarly bring a ggplot2-like interface to the package, again using macros to create an R-like feel.

After looking at several plotting packages, it looks like Gadfly.jl may be the best option as a backend for a variety of reasons (including it being a really well-done package)!

I wanted to ask if you'd be supportive of that effort to bring a Gadfly.jl backend into Tidier.jl. I didn't want to step on any toes and wanted to do this in partnership to respect the amazing work you've done. My intent would be to credit Gadly on our README and on our documentation.

I wouldn't need anything from you. Just wanted to check and make sure this is okay from your standpoint.

I appreciate your consideration,

Karandeep

**Comment by Mattriks** [comment]
That sounds ok by me (I guess the point is to appeal to R users).  Gadfly's `layer` allows syntax like:
```julia
plot( layer(df1, x=:x1, y=:y1, Geom.point, Geom.line),
    layer(df2, x=:x2, y=:y2, Geom.point, Geom.line)) 
```
or 'multiple geoms per layer'. `layer` is actually mentioned in  [a snippet from HW](https://groups.google.com/forum/?fromgroups#!topic/gsofgs/ozQpoIQZMZo).

**Comment by kdpsingh** [comment]
Yeah, the composability of Gadfly is really appealing, including the way it handles layers. And yes, the intent is primarily to cater to R users considering Julia.

**Comment by kdpsingh** [comment]
If okay with everyone, feel free to close this issue. Primarily wanted to make the connection so I develop in a respectful, inclusive way.

**Comment by bjarthur** [comment]
https://github.com/MakieOrg/AlgebraOfGraphics.jl sounds similar to what you propose, but for Makie instead of Gadfly

**Comment by kdpsingh** [comment]
Hi @bjarthur. Thanks for pointing it out.

In our issue here (https://github.com/kdpsingh/Tidier.jl/issues/66), I had mentioned my initial proposal to use Gadfly, which is when I had posted my issue to Gadfly. Several folks replied on GitHub and elsewhere (Twitter) that we should consider wrapping AlgebraOfGraphics due to the potential to support the larger Makie ecosystem.

I opened the issue on AoG's GitHub as a result of that discussion.

I'm still studying the issue but I think both Gadfly and AoG look possible to wrap from my end. Looking for guidance from others as I'm new to the Julia ecosystem.

**Comment by kdpsingh** [comment]
This is really helpful context. I think Makie itself is something I'm not that interested in directly using because it reminds me more of base R plotting (but I could be wrong).

I really like the composability of both Gadfly (thanks to Compose.jl) and AOG, and I honestly won't really fully grasp the nuances until I've had a chance to play with the different permutations of things I would normally do in R.

I'll definitely continue to work with both packages, even if I pick one or the other as a starting backend in Tidier.jl.

**Comment by kdpsingh** [comment]
I appreciate your time and kindness, and I'm excited to see the Julia ecosystem grow!
