### ISSUE TITLE
Wrong x-axis upper limit with date ?

### ISSUE THREAD

**Issue by apraga** [GiovineItalia/Gadfly.jl#1612]
Hi,

With the following minimal example, I find the upper plot limit is higher than it should be, resulting in a lot of blank space :

```
d = DataFrame(date=[
    DateTime(2023,03,23),
    DateTime(2023,03,22),
    DateTime(2023,03,21),
    DateTime(2023,03,20),
    DateTime(2023,03,19),
    DateTime(2023,03,18),
    DateTime(2023,03,17),
    DateTime(2023,03,16),
    DateTime(2023,03,15),
    DateTime(2023,03,14)
],
              result= [0.37, 1.66, 0.1, 2.64, 0.6, 3.73, 0.74, 5.69, 1.82, 2.93])
plot(d, x=:date, y=:result)

```
![image](https://user-images.githubusercontent.com/914687/227235553-81ae62d1-4f3d-466c-8ab1-e8ac88cd958e.png)

Is there a way to correct the default behaviour ? Using `maxvalue` with scale.x_continous did not help. Thanks!

**Comment by bjarthur** [comment]
or `Scale.x_continuous[maxvalue=...`.

it's not a bug per se.  there is an [optimization algorithm](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/ticks.jl#L66-L167) which computes the bounds and number of ticks.  ideally we need to figure out a way to hoist the parameters (ie granularity_weight, simplicity_weight, coverage_weight, and niceness_weight) into a user accessible function instead of just hard-coding defaults.

**Comment by apraga** [comment]
Using integer instead of date gives a result much more satisfying for the end-user:

`using DataFrames, Gadfly, Dates
d = DataFrame(date = [23, 22, 21, 20, 19, 18, 17, 16, 15, 14],
              result= [0.37, 1.66, 0.1, 2.64, 0.6, 3.73, 0.74, 5.69, 1.82, 2.93])
plot(d, x=:date, y=:result)
![Uploading axis.png…]()

`

**Comment by bjarthur** [comment]
a lot of [changes](https://github.com/GiovineItalia/Gadfly.jl/commit/32ed25b7dec41bd99a1dbc12cf07cb7a43816279) were made to dates recently and there hasn't been a new release made to include them.  try checking out master (with `] dev Gadfly`) and see if the ticks are any better for you.  i get the following plots on master for your two examples above:
<img width="530" alt="Screenshot 2023-03-26 at 5 59 02 PM" src="https://user-images.githubusercontent.com/1538268/227807260-06793045-bfa5-412c-8175-6320b81a6d07.png">
<img width="529" alt="Screenshot 2023-03-26 at 5 59 09 PM" src="https://user-images.githubusercontent.com/1538268/227807266-0d82383a-77a5-4541-a5d9-e78195e92f16.png">

**Comment by apraga** [comment]
Thanks for your quick answer ! It does fixes my issue, closing it now.
