### ISSUE TITLE
Specifying number of ticks

### ISSUE THREAD

**Issue by tvqt** [GiovineItalia/Gadfly.jl#1615]
Hi there, 

I was wondering if it is possible to specify the number of ticks on a scale of a Gadfly chart? I see in the source code that the class allows for a minticks and a maxticks variable, but it's unclear to me if those are accessible to regular users. Any help you could provide would be much appreciated! Thanks

**Comment by bjarthur** [comment]
you can specify exactly where to put ticks with `Guide.xticks`:  http://gadflyjl.org/stable/gallery/guides/#[Guide.xticks](@ref),-[Guide.yticks](@ref)

**Comment by bjarthur** [comment]
ideally, at some point it would be nice to hoist `granularity_weight` [and friends](https://github.com/GiovineItalia/Gadfly.jl/blob/026576ae24065098a76a542a3015dcdc804748d1/src/statistics.jl#L792) into the Theme struct and/or kwargs to `Guide.{x,y}ticks`.

**Comment by bjarthur** [comment]
i'd forgotten that `granularity_weight` can be specified in `Stat.xticks`:

```
help?> Stat.xticks
  Stat.xticks[(; ticks=:auto, granularity_weight=1/4, simplicity_weight=1/6,
              coverage_weight=1/3, niceness_weight=1/4)]

  Compute an appealing set of x-ticks that encompass the data by transforming the x, xmin,
  xmax, xintercept and xend aesthetics into the xtick and xgrid aesthetics. ticks is a vector
  of desired values, or :auto to indicate they should be computed. the importance of having a
  reasonable number of ticks is specified with granularity_weight; of including zero with
  simplicity_weight; of tightly fitting the span of the data with coverage_weight; and of
  having a nice numbering with niceness_weight.
```

it doesn't provide a way to directly specify the number of ticks though.

**Comment by nsajko** [comment]
Could this be reopened? I think that a good interface would be to allow the user to provide an interval for Gadfly to choose the number of tick marks from, for example: *there should be no less than four ticks and no more than ten*.

My issue in particular is that some of my plots have only **a single** tick mark on the x-axis.

**Comment by nsajko** [comment]
`Scale.x_continuous` actually accepts the parameters `minticks` and `maxticks`, and those are actually documented. The parameters don't seem to affect my plots though, I think that Gadfly maybe just ignores them for some reason?
