### ISSUE TITLE
Gadfly histogram ignore the bincount (and how to remove background lines)

### ISSUE THREAD

**Issue by Axze-rgb** [GiovineItalia/Gadfly.jl#1618]
Hello, 

Here is the code 

```
Gadfly.plot(df, x=:QUAL,Geom.histogram(bincount=100, density=true), Guide.xticks(label=false), Guide.yticks(ticks=nothing), Theme(background_color=color("white")))
p |> SVG("bin100.svg",30cm,25cm)
```

I obtain the exact same plot whatever value I give for bincount.

My dataframe is huge with 1.5 million points. Is it what's causing the issue? 

Thanks 

PS: also, how do you remove the horizontal grid line behind the histogram? 

Thank you

**Comment by bjarthur** [comment]
`Theme(grid_line_width=0mm` should turn of the grids.

so that others can more easily debug, could you change your example to use a random data set of equal size?  and show a plot.

**Comment by Axze-rgb** [comment]
Thank you

I am extremely sorry, beginner mistake: in my 1.5 million lines some were not numbers but string, hence the error. I should have checked that, fo course. 

Sorry again. 

the line width =0 did the trick :) 

Cheers
