### ISSUE TITLE
SVG does not work with Gadfly 1.4.0 and Compose 0.9.5

### ISSUE THREAD

**Issue by jojal5** [GiovineItalia/Gadfly.jl#1631]
The following code does not work with Gadfly 1.4.0 and Compose 0.9.5 

```
using DataFrames, Gadfly, RDatasets
iris = dataset("datasets","iris")
p = plot(iris, x=:SepalLength, y=:PetalLength, color=:Species, Geom.point)
draw(SVG("iris_plot.svg", 14cm, 8cm), p)
```

It return _false_.

**Comment by Mattriks** [comment]
The _false_ is a byproduct of some Compose function (yes we should track this down and return nothing).  What version of Julia are you on?  There was a recent issue fixed on Compose.jl#master (GiovineItalia/Compose.jl#441), so try:
```
]add Compose#master
```
if you are on a relatively recent version of Julia?

**Comment by jojal5** [comment]
Thank you for the quick response. I tried it on Julia 1.10.2 and Julia 1.9.4 using Compose.jl#master, but I encountered the same result – it returns false.

**Comment by Mattriks** [comment]
I'm assuming your main issue here is that no file was produced? What OS are you on?  I'll have to check later to see if I can replicate the issue.

**Comment by jojal5** [comment]
Yes, it does not produce the file. I'm on macOS Sonoma 14.4

**Comment by jojal5** [comment]
It returns _false_ but the svg file is generated. Thank you for the answer. Does I close this issue ?

**Comment by jojal5** [comment]
Thank you!
