### ISSUE TITLE
Easier plotting of 2D array data

### ISSUE THREAD

**Issue by andrewsimper** [GiovineItalia/Gadfly.jl#327]
I've got data in a 2D array and would love to plot it easily with Gadfly. Right now I have to jump through the hoops of DataFrames which goes something like:

data = # a 2D array of Float64, the first column is time, the next ones are different signals
df = vcat(
    DataFrame(f=["input" for i in 1:dlen], x=data[:,1], y=data[:,2]),
    DataFrame(f=["lp"    for i in 1:dlen], x=data[:,1], y=data[:,3]),
    DataFrame(f=["hp"    for i in 1:dlen], x=data[:,1], y=data[:,4])
)
plot(df, x=:x, y=:y, color=:f, Geom.line)

Which is a whole lot of not much fun.

I have a feature request: I would love if I could pass a 2D array to Gadfly and use column indexes to plot the signals, and get the colours allocated by column index for me:

plot(data, x=1, y=[2:4], Geom.line)

**Comment by bjarthur** [comment]
closed by https://github.com/GiovineItalia/Gadfly.jl/pull/1013
