### ISSUE TITLE
Plots having Date, the X axis labels are being round off to the next nearest month 

### ISSUE THREAD

**Issue by jaydsolanki** [GiovineItalia/Gadfly.jl#354]
I have been plotting the charts using Dates, but I am facing a problem that the X axis labels are being rounded off to the next nearest month
For instance if the dates are till "2014-08-17" then in the chart the x axis is extended upto Sept 1,2014 i.e. "2014-09-01"
with Data null between "2014-08-18" to "2014-09-01" 
![dateplot](https://cloud.githubusercontent.com/assets/6593003/3506925/004eda5e-0678-11e4-917f-5b24842760c3.png)

CODE:
dates = Array(Date{ISOCalendar},40)
dates[1] = today()
for i=2:length(dates)
    dates[i] = today()+days(i)
end
df = DataFrame(x=dates,y=sort(rand(40)*40))
draw(PNG("DatePlot.png",6inch,4inch),plot(df,x=:x,y=:y,Geom.line))

Is there a way to prevent this round of?

**Comment by bjarthur** [comment]
one can also use `Coord.cartesian(xmin=..., xmax=...)`
