### ISSUE TITLE
Documentation Rendering Obscures Code Samples

### ISSUE THREAD

**Issue by astrieanna** [GiovineItalia/Gadfly.jl#372]
I was trying to figure out how to use a different color-scale, but the documentation is unreadable: 
![screen shot 2014-07-24 at 7 05 45 pm](https://cloud.githubusercontent.com/assets/1205394/3696502/be3e242e-138f-11e4-8ca2-3cd16a41bf85.png)

This is in Chrome (incognito window) on a mac running 10.8.

**Comment by bjarthur** [comment]
closing as not reproducible
