### ISSUE TITLE
Histogram problems in 0.3.3/Julia 0.2.1

### ISSUE THREAD

**Issue by kleinschmidt** [GiovineItalia/Gadfly.jl#386]
I'm not able to get a histogram using version 0.3.3 with Julia 0.2.1.  It plots a single bar across the whole range of the data, with a y value of 1.0 (for example http://nbviewer.ipython.org/gist/kleinschmidt/46998cf74fd8f066485e).  This happens whether I'm running a notebook, or from the terminal, and with the D3 and PNG back ends.

Other plots seem to work fine, as do histograms using Gadfly 0.3.4 under v0.3-rc1.

**Comment by bjarthur** [comment]
closing as it is now fixed
