### ISSUE TITLE
Text too big on plots

### ISSUE THREAD

**Issue by cormullion** [GiovineItalia/Gadfly.jl#405]
Just wondering why the text is always too big:

julia> using Gadfly
julia> plot(x=rand(10), y=rand(10))

![screen shot 2014-08-26 at 07 55 12](https://cloud.githubusercontent.com/assets/52289/4040880/17112b60-2cee-11e4-8430-821063f61578.png)

**Comment by dfannius** [comment]
For what it's worth, this can occur in Firefox as well (I'm using version 38.0.5 on OS X 10.10.3) with effectively the same workaround (Preferences / Content / Fonts & Colors / Advanced / Minimum Font Size = None). I don't know if they're using the same SVG backend or if it's an independent issue.

I'm also including the phrase "large text" in this comment to make this page easier to find for other people with the same issue (I didn't find it until I searched for "big text").

**Comment by romiras** [comment]
Today I've tested both in **Firefox** (46.0) and **Inkscape** (SVG editor). Both display with **too big font size**.
Yet on **Chromium (Blink), Apache Batik** and on **gThumb** displays **OK**.

It appears Firefox and Inkscape use different SVG rasterizer software components.
