### ISSUE TITLE
Axis tick label formatting?

### ISSUE THREAD

**Issue by felixjung** [GiovineItalia/Gadfly.jl#423]
Hi,
Can I somehow set the format of axis tick numbers?

I'm creating various plots that are supposed to have the exact same dimensions. Unfortunately some display y-axis labels like `-1`, others have `-100`, and yet other plots have `-4.5`. I'd like to apply some `sprint()` format to them to fix that.

**Comment by bjarthur** [comment]
this seems to be resolved, so i'll close it.  reopen if not.
