### ISSUE TITLE
Axis label orientation in subplots

### ISSUE THREAD

**Issue by felixjung** [GiovineItalia/Gadfly.jl#424]
Is there a way to set the orientation for the actual axis labels in subplots? I find that `Guide.xlabel()` and `Guide.ylabel()` apply to the overall label for all subplots and not the individual subplots' axis labels.

Thanks!

**Comment by altre** [comment]
Is there any way to change the label orientation in sublots now?

**Comment by Mattriks** [comment]
Tick label orientation works, but axis label orientation only works if you want to replace the labels: 
```julia
iris = dataset("datasets", "iris")
p = plot(stack(iris, Not(:Species)),
         xgroup=:variable, ygroup=:Species, x=:value,
         Geom.subplot_grid(Geom.histogram, 
            Guide.xlabel("vars"; orientation=:vertical),
            Guide.xticks(orientation=:horizontal)
    ) 
)
```
I wonder why axis label orientation wasn't better implemented?
