### ISSUE TITLE
How to place the colorkey legend inside the plot?

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#487]
How to place the colorkey legend inside the plot? How to control colorkey legend location?

**Comment by CorySimon** [comment]
+1
The `:right` position is I think unacceptable for many journals because of the white space that it wastes. The `:top` is much better, but still it would be great to be able to put the legends inside the plot, like in matplotlib.

**Comment by v-i-s-h** [comment]
Hi,
when I use `:top` , entries in the legend gets crowded to left alignment.
Is there any way to nicely spread them out evenly across the horizontal space?

**Comment by Mattriks** [comment]
```julia
using DataFrames, Gadfly, RDatasets
iris = dataset("datasets","iris")

d = Dict{String,String}("setosa"=>"setosa \t","versicolor"=>"versicolor \t", "virginica"=>"virginica \t")
# Add a new variable to the dataframe:
iris[:g] = map(x -> d[x], iris[:Species])

cscale = Scale.color_discrete_manual(colorant"red", colorant"green", colorant"blue")
theme1 = Theme(key_max_columns=3, key_position=:top, guide_title_position=:left)

p = plot(iris, x = :SepalWidth, y = :SepalLength, color = :g, Geom.point, 
    cscale, Guide.colorkey(""),
    theme1
)
```
![issue487a](https://cloud.githubusercontent.com/assets/18226881/21637813/d25f00ec-d2bc-11e6-8640-624042641464.png)

**Comment by Mattriks** [comment]
Now back to the initial question in this issue. Note in the code below its possible to use absolute e.g. `context(7,6)` or relative e.g. `context(0.75w, 0.25h)` coordinates to locate the key. If using absolute coordinates note the y-coord doesn't match the plot coords, presumably because of the way the key is rendered for 'outside' use. 

```julia
key = Guide.manual_color_key("Iris", ["setosa","versicolor","virginica"], ["red","green","blue"])
# Try changing ctxs[1] to ctxs[2] or ctxs[3] in the line below
# It seems Gadfly automatically renders 3 possible keys
mykey = render(key, Theme(), Gadfly.Aesthetics())[1].ctxs[1]
# Try changing context(7,6) to context(0.75w,0.25h) in the next line
kctx = compose(context(), (context(7,6), mykey))

p = plot(iris, x = :SepalLength, y = :PetalLength, color = :g, Geom.point, 
    cscale, Theme(key_position=:none),
    Guide.annotation(kctx)
)
```
![issue487b](https://cloud.githubusercontent.com/assets/18226881/21641084/a52cd93a-d2cd-11e6-9b3f-e6ed7f383fe9.png)

**Comment by Mattriks** [comment]
This feature was added in #1087.
For discussion on overlapping labels see #859.
