### ISSUE TITLE
Order of Geom.subplot_grid

### ISSUE THREAD

**Issue by rob-luke** [GiovineItalia/Gadfly.jl#496]
Is there a way to force the order of subplot grids?

Taking a leaf from #298 I have tried variations on this

``` julia

X={"128","256","512","1024"} # example order for variable :Length

plot(df, x=:xvals, y=:yvals, ymin=:ymins, ymax=:ymaxs, xgroup=:Length,
    Geom.subplot_grid(Geom.line, Geom.ribbon, Scale.x_discrete(levels=X)), 
    Scale.y_log10)
```

**Comment by GravityAssisted** [comment]
I too am struggling with this issue. Have you found a solution or a workaround to this ?

**Comment by bastinat0r** [comment]
Same here. However I am not even sure if the plots are not sorted or only the labels are out of order.

As I see it the numeric values I use are sorted by string values.
I have angle values that go like 0 120 150 180 210 240 270 30 300 330 60 90.
Which is exactly how you would sort strings, but is probably going to confuse someone looking at the diagram.

**Comment by bastinat0r** [comment]
I want to provide a pull request solving this problem. I am currently thinking about how to best solve this problem.
I guess the best solution is passing an additional argument to Geom.subplot_grid like ```Geom.subplot_grid(lt=foobar)``` where foobar is a function the plots are sorted by the same way the [sort-function](http://docs.julialang.org/en/release-0.4/stdlib/sort/) works.

**Comment by CiaranOMara** [comment]
I was able to change the order of the ygroup by changing the sort order on the DataFrame provided to Gadfly.

**Comment by bjarthur** [comment]
does the `order` keyword argument of `xgroup` work for this?  see https://github.com/GiovineItalia/Gadfly.jl/pull/1247/files

**Comment by CiaranOMara** [comment]
The order keyword works. But, care is needed as the original order of the DataFrame with affect the result.

```julia
import Pkg

Pkg.activate(".")
Pkg.instantiate()

using Gadfly
import Cairo, Fontconfig
using DataFrames
using Colors

df = DataFrame(XG = Int[], YG = Int[], X = Int[], Y = Int[], C = Int[])

for XG = 1:4, YG = 1:4, X = 1:4, Y = 1:4
        C = XG == YG == X == Y ? 1 : 0
        push!(df, (XG, YG, X, Y, C))
end

sort!(df, (:XG, :YG, :X, :Y), rev = (false, true, false, false))

p_base =  plot(
	df,
	xgroup=:XG,
	ygroup=:YG,
	x=:X,
	y=:Y,
	color=:C,
	Geom.subplot_grid(Geom.rectbin),
	Scale.color_continuous(colormap=Scale.lab_gradient("white", "green"), minvalue=0, maxvalue=1)
	);

p_order =  plot(
	df,
	xgroup=:XG,
	ygroup=:YG,
	x=:X,
	y=:Y,
	color=:C,
	Geom.subplot_grid(Geom.rectbin),
	Scale.color_continuous(colormap=Scale.lab_gradient("white", "green"), minvalue=0, maxvalue=1),
	Scale.xgroup(order=[1,3,4,2]),
    Scale.ygroup(order=[4,3,2,1])
	);

p_other =  plot(
	sort(df, (:XG, :YG, :X, :Y), rev = (false, false, false, false)),
	xgroup=:XG,
	ygroup=:YG,
	x=:X,
	y=:Y,
	color=:C,
	Geom.subplot_grid(Geom.rectbin),
	Scale.color_continuous(colormap=Scale.lab_gradient("white", "green"), minvalue=0, maxvalue=1),
	Scale.xgroup(order=[1,3,4,2]),
    Scale.ygroup(order=[4,3,2,1])
	);

p_g = gridstack([p_base p_order p_other])

draw(PNG("grid-order.png", 3*6inch, 6inch), p_g)
```

![grid-order](https://user-images.githubusercontent.com/24236593/52183876-6c45dc80-2860-11e9-836d-018310134f03.png)

**Comment by Mattriks** [comment]
For [Discrete Scales](http://gadflyjl.org/dev/tutorial/#Discrete-Scales-1), both `levels` and `order` can be used to order the scale (and they can be used together).
I typically use `levels` in preference to `order`, and view `order` as fine tuning, i.e. `order` orders the order set by levels. If levels is not set, `order` orders the default levels (as pointed out above).
