### ISSUE TITLE
Error:  add_plot_element not defined

### ISSUE THREAD

**Issue by abysmon** [GiovineItalia/Gadfly.jl#543]
I've got Julia 3.5 and Gadfly latest one. Tried running a sample code, but got stuck with `add_plot_element not defined` error message. I've tried `Pkg.update()` multiple times. Running on Win8 64bit. Maybe something is missing ? Below is the code I've tried running.
Edit: I'm using Juno as IDE.

```
using Gadfly
# gadfly sample
xs = [0:0.1:pi]
k = layer(x=xs, y=sin(xs))
add_plot_element(k, Guide.title("Now it has a title"))
p = plot(x=xs, y=sin(xs))
add_plot_element(p, Guide.title("Titular"))
add_plot_element(p, Guide.title("Now it has a title"))
display(p)
```

**Comment by Mattriks** [comment]
This can be closed, since [`push!` is documented](http://gadflyjl.org/dev/man/plotting/#Adding-to-a-plot-1)
