### ISSUE TITLE
Geom.ribbon in does not accept Int vectors as input when used with Geom.smooth

### ISSUE THREAD

**Issue by espintos** [GiovineItalia/Gadfly.jl#559]
Geom.ribbon does't accept Int vectors as input for ymin and ymax when used in combination with Geom.smooth.

http://stackoverflow.com/questions/28966555/geom-ribbon-in-gadfly-julia-does-not-accept-int-vectors-as-input

**Comment by IainNZ** [comment]
At a glance, looks like can relax the `T` to `T,S` and use a `promote_type` to keep it type stable

**Comment by dcjones** [comment]
I don't get this error on julia 0.3 or 0.4 on gadfly master. Maybe it's accidentally fixed already?

**Comment by Mattriks** [comment]
I can't reproduce this either on Julia 0.5 and Gadfly 0.6, so this issue should be closed?
```Julia
x = [-10:10;]
y = x.^2
ymin = y-10
ymax = y+10

p = plot(x=x, y=y,  ymin=ymin, ymax=ymax, Geom.smooth, Geom.ribbon)
```
![issue559](https://cloud.githubusercontent.com/assets/18226881/25154287/6cf85b54-24d3-11e7-880d-c9eff74d4691.png)
