### ISSUE TITLE
Directly control color of each bar on barplot

### ISSUE THREAD

**Issue by CorySimon** [GiovineItalia/Gadfly.jl#569]
I am making a bar plot with differently colored bars.

```
    barplot = plot(df, x="Atom", y="Energy", Geom.bar, Scale.x_discrete, color=df[:Atom], Guide.colorkey("Atom"))
```

Gives me a differently colored bar for each "atom" in the DataFrame df. How do I control the color of each bar, though? e.g. I want the atom "Al" to be green instead of the default order of colors.

**Comment by dcjones** [comment]
You should be able to do this with [`Scale.color_discrete_manual`](http://gadflyjl.org/scale_color_discrete_manual.html).

**Comment by CorySimon** [comment]
Thanks! I defined a dictionary of the colors I need:

    colordict = {"Al" => "green", "P" => "purple", "O" => "blue", "F" => "yellow"}

and then used `Scale.color_discrete_manual`:

     barplot = plot(df, x="Atom", y="Energy", 
                      Geom.bar, Scale.x_discrete, 
                      color=df[:Atom], Guide.colorkey("Atom"),
                      Scale.color_discrete_manual([colordict[i] for i in df[:Atom]]...))

Where can I find a list of colors that are available by default in Gadfly? e.g. "yellow", "green", "red", ...

**Comment by bjarthur** [comment]
closing as this seems resolved.  reopen if not.
