### ISSUE TITLE
Remove title from color key

### ISSUE THREAD

**Issue by Godisemo** [GiovineItalia/Gadfly.jl#585]
I can't figure out how to remove the title from a color key.
I would assume the option is `Guide.colorkey(nothing)` but that does not do anything.
Not sure if it is intended or a bug.

**Comment by darwindarak** [comment]
You should be able to change this in `Themes`:
```julia
plot(..., Theme(key_position = :none))
```

**Comment by Godisemo** [comment]
Just to clarify, I want the color key, just not the title of it. What @darwindarak proposes removes the color key entirely.

**Comment by amellnik** [comment]
Guide.colorkey("")

Is what I'm using, although I guess it might mess with the vertical alignment.

**Comment by bjarthur** [comment]
`colorkey("")` works for me too.  reopen this issue if it doesn't for you.
