### ISSUE TITLE
Titles after vstack/hstack

### ISSUE THREAD

**Issue by tcovert** [GiovineItalia/Gadfly.jl#600]
Is it possible to add titles to a grid of figures?  Say I've got plots p1-p4, and I combine them and render to a PDF (as in the documentation):
draw(PDF("file.pdf",6inch,6inch),vstack(hstack(p1,p2),hstack(p3,p4))

I see that its possible to add titles to each of the individual plots, but how would I add a title above (or below) the grid of p1-p4?

**Comment by dcjones** [comment]
There's not any special support for this, but it's possible to do "manually" through Compose:
```julia
p = hstack(plot(x=rand(50), y=rand(50), Geom.point),
           plot(x=rand(50), y=rand(50), Geom.point))
title = compose(context(0, 0, 1w, 0.25inch),
                text(0.5, 1.0, "These are some plots", hcenter, vbottom))
vstack(title, p)
```

![try](https://cloud.githubusercontent.com/assets/210361/7916207/434ee26a-0837-11e5-8d3e-9b1074d6bbdd.png)

**Comment by tcovert** [comment]
Thanks, this is great.  I assume I need to add "using Compose" to the top of my code?

**Comment by dcjones** [comment]
Oh, right. You do need `using Compose`.

**Comment by tcovert** [comment]
is there documentation for the compose() and text() functions somewhere?  I didn't see it on composejl.org

**Comment by IainNZ** [comment]
Those are the docs right now, plus the source itself
> The all-important function in Compose, is called, not surprisingly, compose. Calling `compose(a, b)` will return a new tree rooted at a and with b attached as a child.

**Comment by dcjones** [comment]
There's unfortunately not API documentation for things like `text`.

**Comment by protogeezer** [comment]
What's the best way to handle the case of an odd number of plots? In other words, how would one leave a blank on one side of the "bottom" row?

**Comment by protogeezer** [comment]
FWIW, here is my best shot. I couldn't figure out how to specify font attributes other than family and size. Creating an all white plot is a bit crude, but it does seem to work.
```
        title1 = compose(context(0, 0, 1w, 0.2h),font("Times"),fontsize(24pt), text(0.5, 1.0, 
                                     "The first line of the title", hcenter, vbottom))
	title2 = compose(context(0, 0, 1w, 0.05h),font("Helvetica"),fontsize(14pt), text(0.5, 1.0, 
                                     "This is the stuff you don't want anyone to notice", hcenter, vbottom))
	blank = plot(x=1:10,y=1:10,Geom.point,
					Theme(default_color=colorant"white",
								grid_color=colorant"white",
								minor_label_color=colorant"white",
								major_label_color=colorant"white"))
	p = plot(x=collect(1:10), y=collect(1:10), Geom.point);
	draw(PDF("test.pdf",8inch,11inch),vstack(title1,title2,hstack(p,p),hstack(p,p),hstack(p,blank)))
```                       
![test](https://cloud.githubusercontent.com/assets/5422230/10589024/5146d2c2-7666-11e5-9ee8-ce9f22608d98.jpg)

**Comment by dcjones** [comment]
That's pretty good. Another way to go about this is with `gridstack`.

```julia
using Gadfly, Compose

M = Array(Compose.Context, (2,2))
M[1,1] = render(plot(x=rand(10), y=rand(10)))
M[1,2] = render(plot(x=rand(10), y=rand(10)))
M[2,1] = render(plot(x=rand(10), y=rand(10)))
M[2,2] = context()
gridstack(M)
```
![try](https://cloud.githubusercontent.com/assets/210361/10589221/d640ad02-765e-11e5-94c6-7017900dce52.png)

It might be worth trying to make this sort of thing simpler.

**Comment by protogeezer** [comment]
contex()? Are you kidding me! This is great. The example I came up with reduces to:
```
...
gs = gridstack(M);
draw(PDF("test.pdf",8inch,11inch),vstack(title1,title2,gs))
```

For some reason, yesterday vstack was complaining about not accepting a type “Table”.

For sure, it is worth making laying out a group of plots easier. 

What I’d belly up to is building on the MatPlotLib model of declaring grids and then allocating rectangular blocks of the grid either to a single plot or another grid. I could also imagine being able to assign a few parameters to each grid - maybe a title and a border of some sort. The purpose of the grid is to provide a sense of relative size - without the need for relative (i.e. unit) coordinates.

I don’t know yet whether it would make sense to finish some of the other work we’ve discussed before diving into something like this which would, admittedly, be fun…

Stephen

**Comment by davidanthoff** [comment]
The example by @dcjones (first response) actually cuts of the x labels from the plots. Any idea how to get them showing?

**Comment by CorySimon** [comment]
+1, this shared title solution cuts off the x-axis labels...

**Comment by Mattriks** [comment]
Try relative not absolute sizes (see also #656).
For example:
```julia
using Compose

pa = hstack(plot(x=rand(50), y=rand(50), Geom.point),
           plot(x=rand(50), y=rand(50), Geom.point))
title = compose(context(0, 0, 1, 0.1),
                text(0.5, 1.0, "These are some plots", hcenter, vbottom))
p = vstack(title, compose(context(0, 0, 1, 0.9), pa))
```
Note that the output of `hstack()` is of type `Compose.Context`.
