### ISSUE TITLE
Boxes drawn in place of numbers with draw

### ISSUE THREAD

**Issue by ZacCranko** [GiovineItalia/Gadfly.jl#604]
The plot shown with `plot(sin,-10,10)` is fine, but I get the following output from `draw(PNG("stuff.png",10cm,10cm),plot(sin,-10,10))`.
![stuff](https://cloud.githubusercontent.com/assets/7624301/8017736/d28e50ec-0c41-11e5-8f30-f457203f59f3.png)

Which is of course accompanied by:

```
julia> draw(PNG("stuff.png",10cm,10cm),plot(sin,-10,10))

(process:45531): Pango-WARNING **: dlopen(/Users/zaccranko/.julia/v0.4/Homebrew/deps/usr/Cellar/pango/1.36.8/lib/pango/1.8.0/modules/pango-basic-coretext.so, 2): Symbol not found: _g_object_new
  Referenced from: /Users/zaccranko/.julia/v0.4/Homebrew/deps/usr/Cellar/pango/1.36.8/lib/pango/1.8.0/modules/pango-basic-coretext.so
  Expected in: flat namespace
 in /Users/zaccranko/.julia/v0.4/Homebrew/deps/usr/Cellar/pango/1.36.8/lib/pango/1.8.0/modules/pango-basic-coretext.so

(process:45531): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='latin'

(process:45531): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='common'
```

**Comment by dcjones** [comment]
I was getting this as well. It's resolved for me now with `Pkg.update()` maybe followed by a `Pkg.build("Cairo")`.

**Comment by ZacCranko** [comment]
Just did another round of `Pkg.update()` and `Pkg.build()`, but it's still not resolved here. In case it is of help, [here's a list](https://gist.github.com/ZacCranko/0740b3ec9c5258bcbffd) of what packages/versions I'm running.

**Comment by dcjones** [comment]
Curious. What does `Homebrew.info("cairo")` and `Homebrew.info("pango")` say?

**Comment by ZacCranko** [comment]
```
julia> Homebrew.info("Cairo")
cairo: 1.14.0 (bottled)

julia> Homebrew.info("Pango")
pango: 1.36.8 (bottled)
```

**Comment by kmsquire** [comment]
I've run into this same issue when running `ProfileView`.  Perhaps it's an issue with the installed Homebrew library?  Might be best as an issue under Tk.jl or Homebrew.jl, but I'm not sure which.

Cc: @staticfloat. @timholy

**Comment by kmsquire** [comment]
Didn't realize that @dcjones already filed https://github.com/JuliaLang/julia/issues/11689.

**Comment by kmsquire** [comment]
... and this should be fixed whenever https://github.com/JuliaLang/julia/pull/11692 (by @dcjones) is merged.

**Comment by bjarthur** [comment]
https://github.com/JuliaLang/julia/pull/12014 reportedly fixed this, so i'll close this issue
