### ISSUE TITLE
Can't reproduce histogram made using base R package in Julia with Gadfly

### ISSUE THREAD

**Issue by ararog** [GiovineItalia/Gadfly.jl#607]
I have the following plot made on R using base package:

![plot1](https://cloud.githubusercontent.com/assets/212631/8216673/63d4c61a-150e-11e5-8ca1-6d9c1a3897fc.png)

I tried to reproduce on Gadfly, but no matter what I do I'm getting a different result:

![plot1](https://cloud.githubusercontent.com/assets/212631/8216702/99510b64-150e-11e5-9764-687c5b072d17.png)

Here's the R script used to create the Julia script:

https://github.com/ararog/ExData_Plotting1/blob/master/plot1.R

**Comment by Keno** [comment]
Try adjusting the [bincount](http://gadflyjl.org/geom_histogram.html) for Gadfly?

**Comment by bjarthur** [comment]
if `bincount` doesn't work, please reopen this issue.
