### ISSUE TITLE
Vector field

### ISSUE THREAD

**Issue by ataias** [GiovineItalia/Gadfly.jl#608]
Firstly, I am not sure where to ask questions about Gadfly, that is why I am posting an issue here. Well, I was just wondering if there is a way to plot 2D vector fields in Gadfly.

**Comment by dcjones** [comment]
There's not currently, though this is certainly something that would be worth adding.

**Comment by bjarthur** [comment]
see https://github.com/GiovineItalia/Gadfly.jl/pull/992
