### ISSUE TITLE
Geom.ribbon opacity

### ISSUE THREAD

**Issue by gestay** [GiovineItalia/Gadfly.jl#611]
In the old documentation the ribbon is transparent, but in the 0.3.12 version it is solid. Is it a bug, or a design change?

http://julia-programming-language.2336112.n4.nabble.com/Opacity-in-Gadfly-plots-td14894.html

**Comment by bdeonovic** [comment]
I would also like this feature back. I also opened an issue about it before realizing this one was relevant https://github.com/dcjones/Gadfly.jl/issues/614

**Comment by dcjones** [comment]
I don't remember the ribbon ever being transparent, but you can do this by adding  `Theme(lowlight_color=c->RGBA{Float32}(c.r, c.g, c.b, 0.2))` to the plot.

**Comment by bdeonovic** [comment]
Will this work on any plot with color?

**Comment by dcjones** [comment]
No, that just works for ribbon colors.

**Comment by gestay** [comment]
thanks!

**Comment by bjarthur** [comment]
seems this issue is resolved, so i'll close it.
