### ISSUE TITLE
Dodged Bars 

### ISSUE THREAD

**Issue by bdeonovic** [GiovineItalia/Gadfly.jl#616]
If I have lots of dodged bars in a `Geom.bar` plot, the drawn plot is too zoomed in

![test-1](https://cloud.githubusercontent.com/assets/805168/8317305/138a94ba-19c2-11e5-880f-cdd7b1bf8d7c.png)

plot should look like this: 

![screenshot from 2015-06-23 16 09 18](https://cloud.githubusercontent.com/assets/805168/8317333/3f6d525c-19c2-11e5-913a-4130d2e9d226.png)

To reproduce:

``` julia
x=[0,1,0,1,0,1,0,1]
y=[0.9722222222222222,0.027777777777777776,0.9871111111111112,0.012888888888888889,0.6737777777777778,0.32622222222222225,0.7188888888888889,0.2811111111111111]
plot(x = x, y=y, Geom.bar(position=:dodge),
     color = [1,1,2,2,3,3,4,4],
     Scale.color_discrete(), Guide.colorkey("Chain"),
     Guide.xlabel("Value", orientation=:horizontal),
     Guide.ylabel("Density", orientation=:vertical),
     Guide.title(sim.names[i]),Theme(lowlight_opacity=0.5))
```

**Comment by gestay** [comment]
I think that using Scale.x_discrete helps to get the right zoom.

**Comment by dcjones** [comment]
Right, `Scale.x_discrete` will work, but it should also should work as written. It turns out the discrete version only works [via kludge](https://github.com/dcjones/Gadfly.jl/blob/master/src/coord.jl#L231) that I've forgot to take care of. I'll do so.

**Comment by bjarthur** [comment]
this seems to work now.  so i'll close this issue.  please reopen if the problem persists.
