### ISSUE TITLE
Stem plot

### ISSUE THREAD

**Issue by gestay** [GiovineItalia/Gadfly.jl#629]
What do you think of adding something like matlab stem plot?
http://www.mathworks.com/help/matlab/ref/stem.html

In Gadfly it would look like:
<img width="516" alt="captura de pantalla 2015-07-07 a las 18 27 07" src="https://cloud.githubusercontent.com/assets/10811856/8557829/3a1058bc-24d6-11e5-8163-a6f5a2cdbc91.png">

**Comment by petermolnarnomicom** [comment]
For two vectors
```julia
 x = linspace(0,9, 10)
 y = sin(x)
```
Try this (all in one line!):
```julia
pl = plot(x=x, y=y, Geom.point); for k in 1:length(x); push!(pl, layer(x=[x[k],x[k]], y=[0, y[k]],    Geom.line));end; pl
```

I switched to PyPlot because of the lack of "stem" in Gadfly. Though, PyPlot has its own issues. I'm back to Gadfly...

**Comment by tbreloff** [comment]
```
using Plots
sticks(sin, 0:0.5:10, markercolor=:red)
savepng(ans, "tmp.png")
```
![tmp](https://cloud.githubusercontent.com/assets/933338/9889865/b4b2d538-5bca-11e5-9841-e1878adb6398.png)

It's only on the dev branch right now though.

**Comment by bjarthur** [comment]
fixed in https://github.com/GiovineItalia/Gadfly.jl/pull/1076
