### ISSUE TITLE
data frame plotting examples don't work?

### ISSUE THREAD

**Issue by swadey** [GiovineItalia/Gadfly.jl#632]
Has the API changed in a way that no longer works with the existing documentation:

``` julia
plot(dataset("car", "SLID"), x="Wages", color="Language", Geom.histogram)
```

Gives:

```
`plot` has no method matching plot(::DataFrame, ::Function)
while loading In[37], in expression starting on line 1
```

**Comment by amellnik** [comment]
```julia
using DataFrames, RDatasets, Gadfly
plot(dataset("car", "SLID"), x="Wages", color="Language", Geom.histogram)
```
This is working for me, what version are you using for each of the three packages?

![image](https://cloud.githubusercontent.com/assets/7132414/8599841/87c22fee-2617-11e5-9dc0-f363cf8f8431.png)

**Comment by swadey** [comment]
versions:
- julia: 0.3.11-pre+13 (2015-07-03 14:31 UTC)
- gadfly: v"0.3.13"
- dataframes: v"0.6.7"
- rdatasets: v"0.1.2"

**Comment by amellnik** [comment]
If you checkout the most recent Gadfly master and run the code above in a fresh kernel, do you get the same thing?  Perhaps something overwrote plot?   What does methods(plot) return?

**Comment by davidakelley** [comment]
I was getting the same problem using 0.3.13. I checked out the current master and that resolved the issue. But now that I've gone back to 0.3.13, I can't replicate the issue.

**Comment by bjarthur** [comment]
works for me.  please reopen if it's still broken for you.
