### ISSUE TITLE
Continuous color scales -- how to use messy manual ranges?

### ISSUE THREAD

**Issue by amellnik** [GiovineItalia/Gadfly.jl#633]
I'm plotting something where the output is limited to data points where we have a large number of samples.  It looks vaguely like this:

``` julia
using DataFrames, Gadfly
data = DataFrame(value = rand(0:10, 100), sample_size = rand(100:400, 100), index = rand(0:10, 100))
plot(data, x="index", y="value",color="sample_size", Geom.point,Scale.color_continuous(minvalue=100, maxvalue=400))
```

![image](https://cloud.githubusercontent.com/assets/7132414/8599640/8a288ee6-2616-11e5-86b5-b0faa63fadab.png)

Could we allow the minvalue and maxvalue aesthetics to directly set these, or maybe some other method to set the color ticks manually?

**Comment by amellnik** [comment]
This also occurs in Scale.x_continuous and similar.  Pretty ticks take precedent over manual axis limits.  

```julia
using DataFrames, Gadfly
tp = plot(x=rand(50), y=rand(50)*110)
```
![image](https://cloud.githubusercontent.com/assets/7132414/8681176/d8562f4e-2a1a-11e5-9af8-73c2825d1cc9.png)

```julia
push!(tp,  Scale.y_continuous(minvalue=-10, maxvalue=110))
```

![image](https://cloud.githubusercontent.com/assets/7132414/8681192/eeda647e-2a1a-11e5-8bbc-e99999c26c71.png)

**Comment by dcjones** [comment]
I think this has come up before. The current behavior is to choose nice ticks that encompass minvalue, maxvalue and there's not a mechanism exposed to choose ticks contained in minvalue, maxvalue.

I'd like to retain the current behavior in some form. I'm thinking I'll add a parameter like `Stat.xticks(strictspan=true)` that would enforce this. Open to other ideas though.

**Comment by amellnik** [comment]
That sounds good.  The current behavior is ideal in most situations, but occasionally can act a bit funky.  So the idea is that it would only span the given range, and use the subset of the original ticks which fell within it, or would the ticks then be recalculated using that range?  

Right now I have some plots where the data spans the last 30 days.  If I turned on strictspan and the ticks remained the same, then the default behavior would leave only a single tick (although this could be manually overwritten).  

![image](https://cloud.githubusercontent.com/assets/7132414/8705337/d0e39080-2add-11e5-9c9e-0be453eeb318.png)

**Comment by babaq** [comment]
i just about to file an issue until i find this thread. Basically i have the similar problem, exemplified as follows:
```julia
using Gadfly
a=rand(10,10)*2pi
spy(a,Scale.ContinuousColorScale(p->Color.HSV(0,p,1),minvalue=0,maxvalue=2pi))
```
![image](https://cloud.githubusercontent.com/assets/92771/8961979/2d9c3760-35e6-11e5-8bfa-8dba9c6c2a6e.png)

i want to map a continuous color scale to exactly 0-2pi, but right now gadfly optimize the ticks and overwrite the manual setting which is obviously inappropriate in my case, and further prevent me to effectively use the color map function. for instance, i may want to set different hues for each quarter of 0-2pi.

i think ticks shouldn't be overwriting manual settings, and as @amellnik suggested we could choose the pretty looking ticks and labels that only within the range of 'minvalue' to 'maxvalue' instead of every ticks from bottom to top of color scale.

**Comment by simleb** [comment]
`strictspan` would be a good solution, although I think it is reasonable to expect than when the user explicitly specifies a min and/or max value, they are to be taken as strict boundaries.

What about the opposite: an `optimize=true` parameter or something similar?

Whatever you decide, this looks like a pretty critical issue for many people. Resolution would be greatly appreciated. Gadfly is fantastic!

**Comment by simleb** [comment]
Ran into this issue again, but I found a workaround in #716. The trick is to use
`Coord.cartesian(xmin=100, xmax=400)`. I wish this was documented, I didn't even know `Coord` was part of the grammar.

**Comment by jotwin** [comment]
I ran into this problem too, there is no analog of Coord.cartesian for the continuous color scale.
