### ISSUE TITLE
whence Plot?

### ISSUE THREAD

**Issue by protogeezer** [GiovineItalia/Gadfly.jl#663]
Gadfly seems to have mysteriously disappeared! Or is there something that can be done to get it going?

Stephen

et-imac-retina: sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6787 (2015-08-17 18:41 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit 72431c5 (3 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Gadfly
ERROR: LoadError: LoadError: UndefVarError: LAB not defined
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
while loading /Users/sjbespa/.julia/v0.4/Gadfly/src/Color.jl, in expression starting on line 14
while loading /Users/sjbespa/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 4

julia> Pkg.rm("Gadfly")
INFO: Removing Calculus v0.1.10
INFO: Removing Codecs v0.1.4
INFO: Removing Color v0.4.7
INFO: Removing Compose v0.3.13
INFO: Removing Contour v0.0.7
INFO: Removing DataStructures v0.3.12
INFO: Removing Dates v0.4.4
INFO: Removing Distances v0.2.0
INFO: Removing DualNumbers v0.1.3
INFO: Removing FixedPointNumbers v0.0.10
INFO: Removing Gadfly v0.3.13
INFO: Removing Graphics v0.1.1
INFO: Removing Grid v0.3.10
INFO: Removing Hexagons v0.0.3
INFO: Removing ImmutableArrays v0.0.9
INFO: Removing KernelDensity v0.1.1
INFO: Removing Loess v0.0.3
INFO: Removing NaNMath v0.0.2
INFO: Removing Optim v0.4.2
INFO: Removing WoodburyMatrices v0.1.1
INFO: Package database updated

julia> Pkg.add("Gadfly")
INFO: Installing Calculus v0.1.10
INFO: Installing Codecs v0.1.4
INFO: Installing Color v0.4.7
INFO: Installing Compose v0.3.13
INFO: Installing Contour v0.0.7
INFO: Installing DataStructures v0.3.12
INFO: Installing Dates v0.4.4
INFO: Installing Distances v0.2.0
INFO: Installing DualNumbers v0.1.3
INFO: Installing FixedPointNumbers v0.0.10
INFO: Installing Gadfly v0.3.13
INFO: Installing Graphics v0.1.1
INFO: Installing Grid v0.3.10
INFO: Installing Hexagons v0.0.3
INFO: Installing ImmutableArrays v0.0.9
INFO: Installing KernelDensity v0.1.1
INFO: Installing Loess v0.0.3
INFO: Installing NaNMath v0.0.2
INFO: Installing Optim v0.4.2
INFO: Installing WoodburyMatrices v0.1.1
INFO: Package database updated

julia> using Gadfly

julia> using Distributions;using ml_no_missing_r2_plot
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/StatsBase.ji for module StatsBase.
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/DataArrays.ji for module DataArrays.
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/DataFrames.ji for module DataFrames.

julia> srand(1117);

julia> m = 1000000;

julia> n = 4;

julia> y = zeros(n,m);

julia> y[1,:]  = rand(Truncated(Normal(0.56,0.95),-3.22,3.08),(m,1));

julia> y[2,:]  = rand(Truncated(Normal(0.85,0.83),-4.02,3.19),(m,1));

julia> y[3,:]  = rand(Truncated(Normal(0.48,0.73),-4.10,4.15),(m,1));

julia> y[4,:]  = rand(Truncated(Normal(0.54,0.64),-4.78,4.65),(m,1));

julia> r2_cl = gen_hist_cl(m,n,y);
globals = 1000000
elapsed time: 0.245713483 seconds

julia> plot(hist(r2))
ERROR: UndefVarError: plot not defined

**Comment by darwindarak** [comment]
Have you tried doing this on a new REPL session after you reinstalled Gadfly?

**Comment by protogeezer** [comment]
Darwin - yes - here's what I get:

et-imac-retina:~ sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6787 (2015-08-17 18:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 72431c5 (3 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Gadfly
ERROR: LoadError: LoadError: UndefVarError: LAB not defined
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
while loading /Users/sjbespa/.julia/v0.4/Gadfly/src/Color.jl, in expression starting on line 14
while loading /Users/sjbespa/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 4

julia>

**Comment by protogeezer** [comment]
BTW, this is the same error I got at the top of the original session, above. It (Gadfly) loaded after I deleted/reinstalled but then Plot was missing...

**Comment by darwindarak** [comment]
Can you try using Color before running using Gadfly?

**Comment by protogeezer** [comment]
Last login: Thu Aug 20 16:18:46 on ttys004
et-imac-retina:~ sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6787 (2015-08-17 18:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 72431c5 (3 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Color
INFO: Precompiling module FixedPointNumbers...

julia> using Gadfly
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at ./deprecated.jl:63
 in require at deprecated.jl:648
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:266
 in require at ./loading.jl:205
while loading /Users/sjbespa/.julia/v0.4/Compose/src/Compose.jl, in expression starting on line 131
WARNING: module Gadfly should explicitly import / from Base
WARNING: module Gadfly should explicitly import / from Base
WARNING: module Gadfly should explicitly import - from Base
WARNING: module Gadfly should explicitly import + from Base
WARNING: module Gadfly should explicitly import - from Base
WARNING: module Gadfly should explicitly import / from Base
WARNING: module Gadfly should explicitly import - from Base
WARNING: module Gadfly should explicitly import - from Base
WARNING: module Gadfly should explicitly import - from Base
WARNING: module Gadfly should explicitly import - from Base
WARNING: module Gadfly should explicitly import * from Base

WARNING: deprecated syntax "zip (" at /Users/sjbespa/.julia/v0.4/Gadfly/src/scale.jl:797.
Use "zip(" instead.

**Comment by protogeezer** [comment]
I just noticed that there weren't any errors - so...

WARNING: deprecated syntax "zip (" at /Users/sjbespa/.julia/v0.4/Gadfly/src/scale.jl:797.
Use "zip(" instead.

julia> plot(1:10)
ERROR: MethodError: `plot` has no method matching plot(::UnitRange{Int64})

julia> plot(x=1:10, y=2*(1:10))

julia> 

It did work after a long delay... I'll test more? Any suggestions?

**Comment by hvillegaspico** [comment]
I updated Julia packages and Gadfly stopped working. 
When invoking plot, a message indicates that plot is not defined.
Is there any work around for this problem?

Hugo

**Comment by Keno** [comment]
The original error message was due to the change in the behavior of `using` combined with a case-insensitive file system (now fixed on julia master).

**Comment by hvillegaspico** [comment]
I still have the problem "pos is not defined" after updating the Packages.
I am using Julia v0.3.4, should I update to v0.3.11?
