### ISSUE TITLE
plot not defined

### ISSUE THREAD

**Issue by hvillegaspico** [GiovineItalia/Gadfly.jl#666]
I updated Julia packages and Gadfly does not work appropriately.
When plot is invoked, an error message 'plot not defined' is displayed.
Similar situation happens when creating layers for a plot.

Is there any fixes for this problem?

Hugo

**Comment by darwindarak** [comment]
Did the package load correctly (any error messages after `using Gadfly`)?

**Comment by hvillegaspico** [comment]
No error message is communicated after executing using Gadfly.
I removed and added over the Gadfly Package, but I still have the same problem that 'plot is not defined'.

**Comment by samuela** [comment]
Same here.

**Comment by hvillegaspico** [comment]
I solved this problem by erasing the local folder that contains locally all Julia packages. For example, I am a MAC user; hence, I removed the folder named "v0.3" that is within: 
/Users/username/.julia 
(with Julia offline). 
Then, I restarted Julia and the folder v0.3 is created again and some basic packages are installed within. One has to reinstall manually other packages one may use.

**Comment by JanicaTang** [comment]
to the comment above, what do you mean by restarted Julia? did you reinstall everything (since you deleted what's in the folder?)

**Comment by hvillegaspico** [comment]
To start Julia again (because the folder v0.3 shall be erased when Julia is Offline). Julia reinstalled some elementary packages; other packages had to be installed manually.
