### ISSUE TITLE
Plot range.

### ISSUE THREAD

**Issue by DJ-kim** [GiovineItalia/Gadfly.jl#668]
<img width="632" alt="2015-08-25 12 52 14" src="https://cloud.githubusercontent.com/assets/13537753/9444803/9ef376d4-4ac3-11e5-99ae-970663c7149b.png">

p = plot(layer(df, x="x", y="y", color="Maser", Geom.line,),
         layer(df, x="x", y="y", color="Maser", Geom.point,),
         Scale.discrete_color_manual("#FFD800","#587058","#E86850"),
         Guide.xlabel("Days"),Guide.ylabel("Integrated Intensity"),Guide.title(" Variation of Integrated Intensity "),
         Coord.Cartesian(xmin=0, xmax=2300, ymin=0))

The maximum value of the data is 2210(x -axis )  but as you saw above, x-axis value plotted up to 2500.
So I tried to insert Coord.catesian but problem have not solved.

What can I do to solve this problem?

 By the way, can I define interval of axis label value?

**Comment by amellnik** [comment]
Also appears in #633 and probably a few other issues.  (@dcjones has a suggestion about how to deal with this in that thread.)

**Comment by bjarthur** [comment]
`Coord.cartesian(xmax=2300...` should work here now, but since you didn't post your data, i can not test to confirm.  please reopen if this is still a problem.
