### ISSUE TITLE
Problems running Gadfly + Julia 0.4.0-rc1+7: MethodError: `circle` has no method matching circle(::Array{Int64,1}, ::Array{Int64,1}, ::Array{Compose.Measure{S,T},1}, ::Symbol)

### ISSUE THREAD

**Issue by cndesantana** [GiovineItalia/Gadfly.jl#685]
Just installed the new stable release of Julia (Version 0.4.0-rc1+7 (2015-09-10 20:01 UTC) ). I tried to run a simple example of Gadfly webpage but I got the following error message:

julia> p = plot(x=[1,2,3], y=[4,5,6])
Error showing value of type Gadfly.Plot:
ERROR: MethodError: `circle` has no method matching circle(::Array{Int64,1}, ::Array{Int64,1}, ::Array{Compose.Measure{S,T},1}, ::Symbol)
Closest candidates are:
  circle(::AbstractArray{T,N}, ::AbstractArray{T,N}, ::AbstractArray{T,N})
  circle(::Any, ::Any, ::Any)
 in render at /home/cdesantana/.julia/v0.4/Gadfly/src/geom/point.jl:45
 in render at /home/cdesantana/.julia/v0.4/Gadfly/src/geometry.jl:47
 in render_prepared at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:846
 in render at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:785
 in display at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:1037
 [inlined code] from multimedia.jl:151
 in display at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:985
 in print_response at REPL.jl:135
 in print_response at REPL.jl:122
 in anonymous at REPL.jl:624
 in anonymous at REPL.jl:827
 in anonymous at LineEdit.jl:767
 in prompt! at ./LineEdit.jl:1636
 in run_interface at ./LineEdit.jl:1605
 in run_frontend at ./REPL.jl:863
 in run_repl at ./REPL.jl:167
 in _start at ./client.jl:453

julia> draw(PNG("myplot.png", 12cm, 6cm), p)
ERROR: MethodError: `circle` has no method matching circle(::Array{Int64,1}, ::Array{Int64,1}, ::Array{Compose.Measure{S,T},1}, ::Symbol)
Closest candidates are:
  circle(::AbstractArray{T,N}, ::AbstractArray{T,N}, ::AbstractArray{T,N})
  circle(::Any, ::Any, ::Any)
 in render at /home/cdesantana/.julia/v0.4/Gadfly/src/geom/point.jl:45
 in render at /home/cdesantana/.julia/v0.4/Gadfly/src/geometry.jl:47
 in render_prepared at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:846
 in render at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:785
 in draw at /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl:885

Any idea?

**Comment by timholy** [comment]
I bet you checked out master on Gadfly. If so, you'll also need to check out master on Compose.

Or we could tag a new release of both Gadfly and Compose...

**Comment by cndesantana** [comment]
Yep! You are right! 

I think the origin of my problem was that I had installed Gadfly using Pkg.clone(). But other packages I installed using Pkg.add(). 

To solve my problem I removed the installation of Gadfly, Compose and a couple of other julia packages and installed only Gadfly by using Pkg.add(). It installed many dependencies (as you can see in the message below). After calling "using Gadfly" it compiled Gadfly and I was able to run the example I gave above without any problem.

julia> Pkg.add("Gadfly")
INFO: Initializing package repository /home/cdesantana/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Installing ArrayViews v0.6.3
INFO: Installing Calculus v0.1.10
INFO: Installing Codecs v0.1.4
INFO: Installing ColorTypes v0.1.4
INFO: Installing Colors v0.5.3
INFO: Installing Compat v0.7.0
INFO: Installing Compose v0.3.14
INFO: Installing Contour v0.0.7
INFO: Installing DataArrays v0.2.18
INFO: Installing DataFrames v0.6.9
INFO: Installing DataStructures v0.3.12
INFO: Installing Dates v0.4.4
INFO: Installing Distances v0.2.0
INFO: Installing Distributions v0.8.6
INFO: Installing Docile v0.5.18
INFO: Installing DualNumbers v0.1.3
INFO: Installing FixedPointNumbers v0.0.10
INFO: Installing GZip v0.2.17
INFO: Installing Gadfly v0.3.14
INFO: Installing Grid v0.3.10
INFO: Installing Hexagons v0.0.4
INFO: Installing ImmutableArrays v0.0.10
INFO: Installing Iterators v0.1.8
INFO: Installing JSON v0.4.5
INFO: Installing KernelDensity v0.1.1
INFO: Installing Loess v0.0.3
INFO: Installing NaNMath v0.1.0
INFO: Installing Optim v0.4.2
INFO: Installing PDMats v0.3.5
INFO: Installing Reexport v0.0.3
INFO: Installing Showoff v0.0.4
INFO: Installing SortingAlgorithms v0.0.5
INFO: Installing StatsBase v0.7.2
INFO: Installing StatsFuns v0.1.3
INFO: Installing WoodburyMatrices v0.1.1
INFO: Package database updated

The lesson of the day (for me) is: Use Pkg.add() instead of Pkg.clone() as many times as you can!

Thanks a lot!
