### ISSUE TITLE
"Cairo must be installed to use the PNG backend" error after trying to run Gadfly.jl + Cairo.jl + Vega.jl

### ISSUE THREAD

**Issue by cndesantana** [GiovineItalia/Gadfly.jl#686]
I just installed the new stable version of Julia (Version 0.4.0-rc1+7 (2015-09-10 20:01 UTC))

And I am trying to run Gadfly together with Vega to generate a figure of a word-cloud. I am using simple examples extracted from http://johnmyleswhite.github.io/Vega.jl/wordcloud.html and http://gadflyjl.org/

I am using Vega.jl to create the word-cloud:

```
    julia> Pkg.checkout("Vega")
    INFO: Checking out Vega master...
    INFO: Pulling Vega latest master...
    INFO: No packages to install, update or remove

    julia> using Vega

    julia> corpus = [
           "Julia is a high-level, bla bla bla....",
           "Julia programs are organized ble ble ble..."
           ];

    julia> wc = wordcloud(x = corpus);
```

And I am trying to use Cairo.jl + Gadfly.jl to plot the word-cloud into a PNG figure. I am doing the following:

```
    julia> Pkg.checkout("Cairo")
    INFO: Checking out Cairo master...
    INFO: Pulling Cairo latest master...
    INFO: No packages to install, update or remove

    julia> Pkg.checkout("Gadfly")
    INFO: Checking out Gadfly master...
    INFO: Pulling Gadfly latest master...
    INFO: No packages to install, update or remove

    julia> using Gadfly

    julia> draw(PNG("myplot.png", 4inch, 3inch), wc)
    ERROR: Cairo must be installed to use the PNG backend.
     in PNG at /home/cdesantana/.julia/v0.4/Compose/src/Compose.jl:137
```

Any idea about it? Is it a problem with my installation of Cairo or Gadfly? Is it a compatibility problem between Gadfly and Vega? 

Thanks for any tip!

**Comment by jiahao** [comment]
Try deleting the cache of Compose.jl in `~/.julia/lib/v0.4/Compose.ji` and run the code again.

**Comment by cndesantana** [comment]
Thanks for your suggestion, @jiahao . It changed the error, but I don't know if it is good or bad news :)

        julia> draw(PNG("myplot.png", 4inch, 3inch), wc)
        ERROR: MethodError: `draw` has no method matching draw(::Compose.Image{Compose.PNGBackend}, ::Vega.VegaVisualization)
        Closest candidates are:
        draw(::Compose.Backend, ::Compose.Transform, ::Compose.UnitBox{S,T,U,V},         ::Compose.AbsoluteBoundingBox, ::Compose.Form{P<:Compose.FormPrimitive})
        draw(::Compose.Backend, ::Compose.Context)
        draw(::Compose.Image{B<:Compose.ImageBackend},         ::Compose.Form{P<:Compose.FormPrimitive})

**Comment by jiahao** [comment]
That error says that Compose.jl doesn't know how to draw a Vega.jl object. I don't think these packages work together.

**Comment by bjarthur** [comment]
please reopen if this issue is still relevant
