### ISSUE TITLE
SVGJS backend - future features and current bugs

### ISSUE THREAD

**Issue by Godisemo** [GiovineItalia/Gadfly.jl#731]
I want this issue to collect a list of ideas for future features for the SVGJS backend to gadfly. Things like panning, zooming and toggling data. Please comment with your ideas and suggestions.

I also want to collect a list of known bugs related to the same backend. No core SVG rendering issues.

**Suggestions and ideas**
- [ ] Box zoom without aspect ratio limitations
- [ ] Crosshair which displays exact coordinate

**Known bugs**
- [ ] ...

**Comment by gestay** [comment]
Zooming and panning are not working well on gadfly master.

**Comment by Godisemo** [comment]
@gestay Could you elaborate?

**Comment by gestay** [comment]
The zoom slide don't show, and the panning don't work.
I tried to record an animated gif of the behavior:

![gadfly](https://cloud.githubusercontent.com/assets/10811856/10777912/1df5238e-7cff-11e5-8885-6411ca0bd05b.gif)

**Comment by gestay** [comment]
There are other cases where the zoom slide only appears when grid lines are touched.

![gadfly2](https://cloud.githubusercontent.com/assets/10811856/10778013/1d9c7c56-7d00-11e5-8c02-0de7e67ff11b.gif)

**Comment by dcjones** [comment]
I can confirm this. There was a pretty big refactor of parts of Compose that just got merged, so I suspect I broke something with that. I'll fix this before I tag a new version.

**Comment by dcjones** [comment]
@gestay Fixed in Compose master now.

**Comment by gestay** [comment]
thanks!

**Comment by gestay** [comment]
@Godisemo,  data toggling is not working for the following geometries:
* Geom.ribbon
* Geom.bar
* Geom.histogram
* Geom.polygon

**Comment by tlnagy** [comment]
Also it would be nice to have a reset to default view option.

**Comment by bjarthur** [comment]
+1 for box zoom w/o aspect ratio limitations.  @Godisemo do you have time to work on this?

**Comment by Natharax** [comment]
Interactive toggling display of colors doesn't work for colors whose names contain periods/decimals.  This is evident in the gasoline example of the tutorial - drawing the plot to SVGJS allows all but U.K. and U.S.A. to be toggled.

**Comment by bjarthur** [comment]
yep, i've noticed that too.  it's even more broken with https://github.com/GiovineItalia/Gadfly.jl/pull/1037.  will try to fix.  thx.

**Comment by bjarthur** [comment]
@Natharax toggling should be fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/1037/commits/ad32399604b99fde64962ad68befafb91bb98b8b.  let me know if you have the time to checkout this PR and try it out.  might be awhile before i merge it.

**Comment by bjarthur** [comment]
fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/1037
