### ISSUE TITLE
Gadfly get into endless loop

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#740]
I am plotting small sets of data (3-4 entries) using the following lines

p = Gadfly.plot(Guide.title(wellname),
layer(x=tc, y=c, Geom.line, Theme(default_color=parse(Colors.Colorant, "blue"), line_width=3pt)),layer(x=td, y=d, Geom.point, Theme(default_color=parse(Colors.Colorant, "red"), default_point_size=4pt)))

the y's are in a very small range. Something like this

tc = [2009.0,2012.0,2015.0]
c = [5.000000176777371,5.000000176858355,5.000000177661828]

I think the code fails to compute the ticks on the vertical axis.

When I ctrl-c julia code I get this:

ERROR: InterruptException:
 in optimize_ticks_typed at /Users/monty/.julia/v0.4/Gadfly/src/ticks.jl:118
 in optimize_ticks at /Users/monty/.julia/v0.4/Gadfly/src/ticks.jl:63
 in multilevel_ticks at /Users/monty/.julia/v0.4/Gadfly/src/ticks.jl:291
 in apply_statistic at /Users/monty/.julia/v0.4/Gadfly/src/statistics.jl:891
 in apply_statistics at /Users/monty/.julia/v0.4/Gadfly/src/statistics.jl:38
 in render_prepare at /Users/monty/.julia/v0.4/Gadfly/src/Gadfly.jl:676
 in render at /Users/monty/.julia/v0.4/Gadfly/src/Gadfly.jl:717
 in vstack at /Users/monty/.julia/v0.4/Gadfly/src/Gadfly.jl:826
 in plotmatches at /Users/monty/Julia/Mads.jl/src/MadsPlot.jl:178

I use julia 0.4

**Comment by tlnagy** [comment]
This seems to have been fixed at some point. Please re-open if you are still having this issue.
