### ISSUE TITLE
Manual's example with position=:centered throws error (v0.4)

### ISSUE THREAD

**Issue by abahm** [GiovineItalia/Gadfly.jl#748]
The documentation provided code for label with position=:centered, and the Scale set,

plot(dataset("MASS", "mammals"), x="Body", y="Brain", label=1,Scale.x_log10, Scale.y_log10, Geom.label(position=:centered))

now throws an error,

ERROR: TypeError: typeassert: expected Compose.TextPrimitive{Tuple{Measures.Length{:cx,Float64},Measures.Length{:cy,Float64}},Compose.Rotation{Tuple{Measures.Length{:w,Float64},Measures.Length{:h,Float64}}}}, got Compose.TextPrimitive{Tuple{Measures.Length{:mm,Float64},Measures.Length{:cy,Float64}},Compose.Rotation{Tuple{Measures.Length{:w,Float64},Measures.Length{:h,Float64}}}}
 [inlined code] from /Users/abahm/.julia/v0.4/Compose/src/misc.jl:103
 in **text#19** at /Users/abahm/.julia/v0.4/Compose/src/form.jl:88
 in text at /Users/abahm/.julia/v0.4/Compose/src/form.jl:423
 in render at /Users/abahm/.julia/v0.4/Gadfly/src/geom/label.jl:286
 in render at /Users/abahm/.julia/v0.4/Gadfly/src/geometry.jl:48
 in render_prepared at /Users/abahm/.julia/v0.4/Gadfly/src/Gadfly.jl:783
 in render at /Users/abahm/.julia/v0.4/Gadfly/src/Gadfly.jl:722
 in display at /Users/abahm/.julia/v0.4/Gadfly/src/Gadfly.jl:974
 [inlined code] from multimedia.jl:151
 in display at /Users/abahm/.julia/v0.4/Gadfly/src/Gadfly.jl:151
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_frontend at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_repl at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib

on my install of Juliav0.4

Julia Version 0.4.0
Commit 0ff703b\* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by timholy** [comment]
This is very similar to https://github.com/dcjones/Compose.jl/issues/172.

**Comment by timholy** [comment]
(They both involve `circle`.)

**Comment by bjarthur** [comment]
works for me now.  please reopen if it's still a problem

```
using Gadfly, RDatasets
mammals = dataset("MASS", "mammals")
plot(mammals, x=:Body, y=:Brain, label=:Mammal,
    Geom.point, Geom.label(position=:centered), Scale.x_log10, Scale.y_log10)
```
