### ISSUE TITLE
Precompilation warning

### ISSUE THREAD

**Issue by ViralBShah** [GiovineItalia/Gadfly.jl#759]
I get this warning when doing `use Gadfly` on the REPL on master as well as 0.4.1.

```
WARNING: eval from module Compose to Gadfly:    
Expr(:import, :Patchwork)::Any
  ** incremental compilation may be broken for this module **
```

**Comment by ViralBShah** [comment]
Cc @shashi

**Comment by rohitvarkey** [comment]
https://github.com/JuliaLang/julia/pull/12400 seems to be the issue causing this. I'm guessing this is because of the use of the `isinstalled` function defined in [Compose](https://github.com/dcjones/Compose.jl/blob/master/src/Compose.jl#L32-L49) but also used in [Gadfly](https://github.com/dcjones/Gadfly.jl/blob/master/src/Gadfly.jl#L881).

From what I understood from the solution for the Images/Color issue, making `isinstalled` a macro rather than doing an `eval` inside should fix it.

**Comment by vtjnash** [comment]
that might potentially trick the warning (although it shouldn't), but that won't fix the error the warning is trying to catch (which is that calling `eval` inside `__init__` isn't compatible with precompilation)

**Comment by shashi** [comment]
@vtjnash thanks, https://github.com/dcjones/Gadfly.jl/commit/cf537053781eff752322854d667b1a559b4d2c9b was my attempt to fix this issue by making the warning go away.

So I guess one way to fix it is just depend on Patchwork, making the number of dependencies of Gadfly even larger (which was what we were trying to avoid). The awesome way to fix this is of course https://github.com/JuliaLang/julia/pull/6884 !

**Comment by ViralBShah** [comment]
I would be ok to make Patchwork a dependency of Gadfly, if that will give faster compilation.

**Comment by shashi** [comment]
@vtjnash what do you mean by "isn't compatible with precompilation"? It doesn't stop precompilation form happening...

I would like to move this logic to a new package called GadflyDiff, which depends on Patchwork, Reactive and Gadfly. The user will have to run `using Gadfly, GadflyDiff` to get the diffing functionality in IJulia, similarly can have `ComposeDiff`. Poor man's conditional modules?

For now I can forgo precompilation in Escher to keep similar conditional setup code working. It loads pretty fast as it is.

cc @JeffBezanson

**Comment by ViralBShah** [comment]
This sounds like a reasonable solution for now. However, we are doing this kind of a band aid in too many places, and it's best to have conditional modules.

**Comment by bjarthur** [comment]
i believe this issue has been resolved.  if not, please reopen it.
