### ISSUE TITLE
Feature Request: Line of best fit

### ISSUE THREAD

**Issue by jgibson2** [GiovineItalia/Gadfly.jl#762]
Aline of best fit would be an incredibly useful tool to bundle with Gadfly. It should determine if the graph should be linear, quadratic, exponential, etc. and then graph a line that reflects the general curve, putting the equation of the line in the legend.

Thanks for this software. It's incredible.

**Comment by Godisemo** [comment]
I would say that line fitting would be better suited as a separate package. You can already plot functions and annotations using Gadfly.

**Comment by tbreloff** [comment]
If you're looking to add new generic plotting recipes, can I suggest/request a PR to tbreloff/MLPlots.jl? We're trying to accumulate plotting recipes for statistics and machine learning leveraging the Plots.jl front end. Gadfly is a supported backend, so you shouldn't miss out on too much (plus your code could be used for other backends).

**Comment by bjarthur** [comment]
it would neither be good to duplicate the code in `GLM.jl` nor to require it in Gadfly.

linear regressions are easy enough:

```
using Gadfly, GLM
x=rand(10)
y=rand(10)
fit = lm([x ones(10)],y)
slope, intercept = coef(fit)
plot(x=x, y=y, Geom.point,
    intercept=[intercept], slope=[slope], Geom.abline(color="red"))
r2(fit)
```
