### ISSUE TITLE
boxplot fails with ERROR: Vector form and vector property differ in length

### ISSUE THREAD

**Issue by bastinat0r** [GiovineItalia/Gadfly.jl#770]
I am using julia to generate plots for my thesis. 
Currently I am working on a quite huge [dataset](http://bastinat0r.de/nightshift.tar.gz) of that I can only plot smaller subsets without errors.
When trying to draw the plot for the whole data I get the following error:

```
Error showing value of type Gadfly.Plot:
ERROR: Vector form and vector property differ in length. Can't distribute.
 in print_vector_properties at /home/sebastian/.julia/v0.4/Compose/src/svg.jl:759
 in draw at /home/sebastian/.julia/v0.4/Compose/src/svg.jl:1200
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:548
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:586
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:580
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:586 (repeats 3 times)
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:580
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:586
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:473
 in drawpart at /home/sebastian/.julia/v0.4/Compose/src/container.jl:586 (repeats 2 times)
 in draw at /home/sebastian/.julia/v0.4/Compose/src/container.jl:430
 in display at /home/sebastian/.julia/v0.4/Gadfly/src/Gadfly.jl:963
 [inlined code] from multimedia.jl:151
 in display at /home/sebastian/.julia/v0.4/Gadfly/src/Gadfly.jl:922
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
```

What I want to do is basically draw a boxplot showing the statistical relation between range (measurement) and distance (real value).

```
function bucketplot(df, bsize)
        df[:bucket] = bsize * div( df[:distance], bsize ) + bsize / 2
        return plot(df, x=:bucket, y=:range, Geom.boxplot)
end
```

However plotting fails with the error I mentioned. Is it possible that the plots are not scaled to the same dimension? Should I use different asthetics to generated the plot?
I tried to find some other description of the problem, but I seem to be quite alone with this.

My julia-version is 0.4.1.

**Comment by nw11** [comment]
I'm befuddled with this too. I'm on 0.4.2. It worked a month back when I was on 0.3, but I probably have also updated packages since then. For larger datasets I notice that it seems to go fine with one category for x, but fails for two.

**Comment by haavardhvarnes** [comment]
I'm having this problem as well. Reducing the number of samples (I'm running MCMC using Mamba) from 5k or 10k to 100 and it works fine. My Julia version is 4.1.0

**Comment by darwindarak** [comment]
From the dataset provided by @bastinat0r, it looks like the problem occurs when plotting the outliers.
Can anyone confirm this by running their examples after commenting out [these lines](https://github.com/dcjones/Gadfly.jl/blob/fdb02ed4d5a8579d46a9d65ea9edac2b757c839e/src/geom/boxplot.jl#L112-L122) in the source?

**Comment by simleb** [comment]
@darwindarak Confirmed!

**Comment by simleb** [comment]
Ok, something weird is happening. It turns out you are only allowed up to 99 outliers!
I could get my plot to draw by adding `[1:99]` at the end [this line][1]. Of course, I must be loosing some outliers (my test dataset had 447 of them).

This is 99 or less. 100 or more doesn't work!

Both PDF and SVG fail so I guess we can rule out Cairo. So it must be Compose. I searched for a hardcoded `99` or `100` in the Compose source but couldn't find one.

I hope this magic number will ring a bell to someone…

[1]: https://github.com/dcjones/Gadfly.jl/blob/fdb02ed4d5a8579d46a9d65ea9edac2b757c839e/src/geom/boxplot.jl#L114

**Comment by simleb** [comment]
I spoke too fast, there is definitely a 100 harcoded in [batch.jl][1]. It has to be this.

[1]: https://github.com/dcjones/Compose.jl/blob/a2366d540f59b1176177885c7b93a5471477f54f/src/batch.jl#L89

**Comment by darwindarak** [comment]
Nice catch!  I'll take a closer look at the batch-forming code.

**Comment by amellnik** [comment]
For a quick and dirty fix, is there a way to manually turn off outliers?  (I tried `plot(... outliers=nothing)` but no dice.

**Comment by monkeygroover** [comment]
I have seen this error when trying to follow this: http://composejl.org/

this code works (from the example)

```using Compose

function generate()
  compose(context(),
        circle([0.25, 0.5, 0.75], [0.25, 0.5, 0.75], [0.1]),
        fill([LCHab(92, 10, 77), LCHab(68, 74, 192), LCHab(78, 84, 29)]))
end

img = SVG("image.svg", 4inch, 4(sqrt(3)/2)inch)
draw(img, generate())```


but if i try to add an extra circle...

```using Compose

function generate()
  compose(context(),
        circle([0.25, 0.5, 0.75, 1.0], [0.25, 0.5, 0.75, 1.0], [0.1]),
        fill([LCHab(92, 10, 77), LCHab(68, 74, 192), LCHab(78, 84, 29)]))
end

img = SVG("image.svg", 4inch, 4(sqrt(3)/2)inch)
draw(img, generate())```


i get ERROR: LoadError: Vector form and vector property differ in length. Can't distribute.

hopefully this is a clue, but the issue is in Compose for me.

**Comment by madeleineudell** [comment]
It would be very nice if this failed gracefully - the error message is rather unhelpful. Perhaps a warning + truncation of outliers?

**Comment by bastinat0r** [comment]
So what works for me is to simply turn off the outliers like so:

```
    # Outliers
    if aes.outliers != nothing && !isempty(aes.outliers) && length(aes.outliers) < 100
```
I'll do a pullrequest that does what @madeleineudell recommended.

**Comment by bjarthur** [comment]
have you done the experiment of setting `batch_length_threshold` in Compose to say 1000 and seeing increases the number of outliers that can be plotted before an error results?

**Comment by bastinat0r** [comment]
No, I did not know this would be possible.
I think a possibility to just disable outliers would be best (I think to many outliers make the plot unreadable)

**Comment by mirkobunse** [comment]
I recently observed this issue in a plot, where I try to put multiple box plots next to each other (on a discrete x axis). So I tried out the fix proposed by @bastinat0r (big thanks!).

The fix _does_ work for my use case, but _only_ if I reduce the number of outliers allowed to a much smaller number, say 10. From what @monkeygroover pointed out, I assume that Compose has its "100 outlier limit" for the entire plot, no matter to which box the outliers belong.

I am not yet deep enough into the implementation of Gadfly to tell, but could the fix proposed by @bastinat0r be checking the outliers of one individual box only? In that case, I would suggest to fix the issue at some other place instead, where the number of overall outliers is known and can be limited.

**Comment by bjarthur** [comment]
@bastinat0r i did not mean to suggest setting the limit to 1000 as an alternative solution.  rather, i just wanted to confirm that this hard coded 100 in Compose is actually the source of the problem with boxplots in Gadfly.  if so, i would think that a better solution to the problem would be to fix Compose, or at least understand the reason for the limit, not to change Gadfly.

**Comment by tlnagy** [comment]
I agree with @bjarthur, I would prefer us to fix the problem in Compose instead of taping over the problem here.

**Comment by bjarthur** [comment]
@bastinat0r please checkout https://github.com/GiovineItalia/Compose.jl/pull/267 and let us know if it fixes this problem with boxplots.  thanks.
