### ISSUE TITLE
Geom.rectbin

### ISSUE THREAD

**Issue by jverzani** [GiovineItalia/Gadfly.jl#771]
It seems that these should be equivalent:

```
plot(x=[1],y=[1], Geom.rectbin)
```

and

```
plot(xmin=[1],ymin=[1], xmax=[1.5], ymax=[1.5], Geom.rectbin)
```

But the latter complains: The following aesthetics are required by RectbinStatistic but are not defined: y, x

Just commenting out `Gadfly.assert_aesthetics_defined("RectbinStatistic", aes, :x, :y)`  is not the solution.

Is there some other way to draw a rectangle with given dimensions?

**Comment by protogeezer** [comment]
John - Nuts. This is something I’ve used. You are correct - commenting out the line raising the error won’t fix anything. It seems that the variable size rectangle support in Geom.rectbin got whacked in a commit back on 9/21.

A possible workaround:

http://stackoverflow.com/questions/23857793/julia-plotting-unknown-number-of-layers-in-gadfly

has worked in other contexts. Maybe put each rectangle in a separate layer, or all the rects of a single size in a layer. The latter would make it possible to have a deterministic number of layers.

Stephen

**Comment by jverzani** [comment]
Thanks for the link. Hopefully this feature can be put back in, as adding primitives like a rectangle can be super useful. I'll take a look at the commit on 9/21 to see if it is something easy to do.

**Comment by bjarthur** [comment]
fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/993
