### ISSUE TITLE
min and max values for y can not be changed for boxplots

### ISSUE THREAD

**Issue by diegozea** [GiovineItalia/Gadfly.jl#773]
![image](https://cloud.githubusercontent.com/assets/2822757/11854821/2f105f92-a425-11e5-872c-7c7fb8b9bc0f.png)

**Comment by amellnik** [comment]
See also https://github.com/dcjones/Gadfly.jl/issues/633, https://github.com/dcjones/Gadfly.jl/issues/668 and maybe others.

**Comment by bjarthur** [comment]
try `Coord.cartesian(ymin=...)` and re-open if that does not work.
