### ISSUE TITLE
Getting a warning incremental compilation may be broken for this module

### ISSUE THREAD

**Issue by ArthurZ** [GiovineItalia/Gadfly.jl#778]
Hi,
I am able to plot graphs, but upon using Gadfly I am getting a warning:
julia> using Gadfly
INFO: Precompiling module Gadfly...
WARNING: eval from module Compose to Gadfly:
Expr(:import, :Patchwork)::Any
  *\* incremental compilation may be broken for this module **

**Comment by alexranaldi** [comment]
I just attempted to use Gadfly for the first time today and am receiving the same warning.

**Comment by bjarthur** [comment]
please reopen if this issue is still relevant
