### ISSUE TITLE
plot not found until Julia restarted

### ISSUE THREAD

**Issue by alexranaldi** [GiovineItalia/Gadfly.jl#780]
After running: 
julia> Pkg.add("Gadfly")

I had to restart Julia before the plot command was found.  Perhaps this should be mentioned in the docs.

**Comment by darwindarak** [comment]
You have to run `using Gadfly` after, since installing the package does not add the module to your current workspace.

**Comment by alexranaldi** [comment]
Forgot to mention that, but I did run "using Gadfly" -- received a number of compilation errors which are described in issue #778
