### ISSUE TITLE
Geom.density isn't normed to 1

### ISSUE THREAD

**Issue by kain88-de** [GiovineItalia/Gadfly.jl#781]
Working with `Geom.density` I noticed that it doesn't normalize the density correctly.
See [Tower Sampling](https://gist.github.com/kain88-de/6208b0082359ddce404f), the two lines should overlap.

**Comment by tlnagy** [comment]
The jupyter notebook provided doesn't run as is (it refers to an undefined variable `sample`). Normalization should be working correctly on master.

```julia
using Gadfly, Distributions
srand(123)
xs = linspace(-2, 2, 30)
dist = Normal(0, 1)
plot(layer(x=xs, y=pdf.(dist, xs), Geom.point, Theme(default_color=colorant"red")), layer(x=rand(dist, 10000), Geom.density), Coord.cartesian(xmin=-3, xmax=3))
```

![image](https://user-images.githubusercontent.com/1661487/40893909-618ed250-675a-11e8-8d98-0e7c9d7d4a25.png)

**Comment by tlnagy** [comment]
Please open a new issue if you run into any problems.
