### ISSUE TITLE
Coloring fails if variable names contains greek symbols

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Gadfly.jl#786]
Plotting this data frame fails when there is alpha in the parameter column using this command:

Gadfly.plot(vdf, x="x", y="y", Gadfly.Geom.line, color="parameter")

| Row | x | y | parameter |
| --- | --- | --- | --- |
| 1 | 0.0 | 0.0 | "α_1" |
| 2 | 9.2199 | 581.326 | "α_1" |
| 3 | 19.1489 | 587.034 | "α_1" |
| 21 | 0.0 | 0.0 | "a2" |
| 22 | 9.2199 | 577.306 | "a2" |
| 23 | 19.1489 | 584.726 | "a2" |

**Comment by montyvesselinov** [comment]
These are the errors I am getting:

ERROR: LoadError: LoadError: ArgumentError: invalid ASCII sequence
 in convert at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in call at /Users/ftuser/.julia/v0.4/Compose/src/property.jl:476
 in svgclass at /Users/ftuser/.julia/v0.4/Compose/src/property.jl:488
 in render at /Users/ftuser/.julia/v0.4/Gadfly/src/geom/line.jl:205
 in render at /Users/ftuser/.julia/v0.4/Gadfly/src/geometry.jl:48
 in render_prepared at /Users/ftuser/.julia/v0.4/Gadfly/src/Gadfly.jl:803
 in render at /Users/ftuser/.julia/v0.4/Gadfly/src/Gadfly.jl:742
 in draw at /Users/ftuser/.julia/v0.4/Gadfly/src/Gadfly.jl:842

**Comment by montyvesselinov** [comment]
The problem is parameter column is expected to be ASCIIString. However, in this case is AbstractString, which includes UTF8String.

**Comment by bjarthur** [comment]
this now works for me

```
plot(x=[1,2,3,4],y=[1,2,3,4],color=["α_1","α_2","α_1","α_2"],Geom.point)
```

please reopen this issue if you still have problems.
