### ISSUE TITLE
Histogram with alpha values, bars overlapping or bar highlight not same as bar color?

### ISSUE THREAD

**Issue by CorySimon** [GiovineItalia/Gadfly.jl#810]
![energy_distn](https://cloud.githubusercontent.com/assets/4196261/13369268/9cfa3b1c-dca7-11e5-8bb1-27360482c9b0.png)

See the ugly dark lines when I use an RGBA (transparent value)? How do I get rid of these? I cannot add an RGBA type as a `bar_highlight` attribute since I get a type error by doing so.

```
myplot = plot(
layer(x=avg_energies["Ni"], Geom.histogram(bincount=50), Theme(default_color=colors["Ni"])),
layer(x=avg_energies["Fe"], Geom.histogram(bincount=50), Theme(default_color=colors["Fe"])),
        Guide.xlabel("Ensemble average Xe energy (kJ/mol)"),
        Guide.ylabel("Count"),
        Theme(background_color=colorant"white"),
    )
```

**Comment by CorySimon** [comment]
One other issue is that when plotting [heretical as I do] two dist'sn, they should have the same bins. Could you please implement an option to pass an array of custom bin locations so that I can make them correspond? I'd put my data into a dataframe, but then I don't see how to control the colors.

**Comment by protogeezer** [comment]
This isn’t the most direct way, but it gets you a bit closer?

x1 = randn(1000)*2+20;
x2 = randn(1000)*1.5+25;
bins = collect(floor(minimum([minimum(x1),minimum(x2)])):maximum(ceil([maximum(x1),maximum(x2)])));
edges = vcat(bins[1]-0.5,bins+0.5);
h1 = hist(x1,edges);
h2 = hist(x2,edges);
y_max = 50*ceil(maximum([maximum(h1[2]),maximum(h2[2])])/50);
plot(x=bins,y=h1[2],Scale.y_continuous(minvalue=0.0,maxvalue=y_max),Geom.bar)
plot(x=bins,y=h2[2],Scale.y_continuous(minvalue=0.0,maxvalue=y_max),Geom.bar)

**Comment by Mattriks** [comment]
For the first two posts above:
1) There's a discussion of this in #1396. One suggestion there is to "use a small overlap of the rectangles". This can be done e.g. `Theme(bar_spacing=-0.1mm)` (note the negative sign)
2) See plot p3 in #1428
