### ISSUE TITLE
Incorrect fill colors for points in subplot if # of points is too high

### ISSUE THREAD

**Issue by JohnHBrock** [GiovineItalia/Gadfly.jl#813]
See https://gist.github.com/JohnHBrock/f0116d666536ed3cf142 for an example Jupyter notebook.

In the first plot, the stroke color looks like it might be OK, but the fill color is wrong -- it shouldn't always be black. Reducing the number of points from 495 to 490 seems to fix the problem. Rendering the first plot by itself results in the correct fill coloring even with 495 points.

This is with Gadfly v0.4.2.

**Comment by tlnagy** [comment]
WTH. That is so weird.

**Comment by tlnagy** [comment]
![image](https://user-images.githubusercontent.com/1661487/36169158-4a639b3e-10b0-11e8-99be-551023254249.png)

This seems to have been fixed on master
