### ISSUE TITLE
Zooming in on a scatter plot enlarges the points

### ISSUE THREAD

**Issue by cstjean** [GiovineItalia/Gadfly.jl#816]
It used to be that zooming in (in IJulia) on a scatter plot would keep the visible dot size constant, but since ~January the behaviour is to grow the points as well:

![screen shot 2016-03-30 at 22 14 16](https://cloud.githubusercontent.com/assets/8622776/14163577/ccf7a4b2-f6c4-11e5-944f-b8a0304631b3.png)

This makes the zooming feature rather useless.

**Comment by tlnagy** [comment]
That's pretty useless.
