### ISSUE TITLE
Change size of points as a free parameter in plot()?

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#842]
Is it possible to set the point size to show another dimension of the data in Gadfly? I envision something like the following

``` .julia
plot(x=1:5, y=1:5, color=["a", "b", "b", "a", "c"], size=1:5, Geom.point)
```

Is this possible?

**Comment by Mattriks** [comment]
There does seem to be a problem with the point size aesthetic in Gadfly (also mentioned here #766).
One work around is to use `Guide.annotation` [http://dcjones.github.io/Gadfly.jl/guide_annotation.html].
For example, `Compose.circle` can take three vectors `circle(x,y,size).`

A fancier way is to make your own geometry. The following is a simple example:

 ```julia
using Compose, DataFrames

immutable PointGeom2 <: Gadfly.GeometryElement 
     tag::Symbol 
 
    function PointGeom2(; tag::Symbol=Gadfly.Geom.empty_tag) 
         new(tag) 
     end 
end 

 
function Gadfly.element_aesthetics(::PointGeom2) 
    [:x, :y, :size, :color, :shape] 
end 


function Gadfly.render(geom::PointGeom2, theme::Gadfly.Theme, aes::Gadfly.Aesthetics) 
 
     default_aes = Gadfly.Aesthetics() 
    default_aes.color = DataArrays.PooledDataArray(Colors.RGBA{Float32}[theme.default_color]) 
     default_aes.size = Measure[theme.default_point_size] 
    aes = Gadfly.inherit(aes, default_aes) 
    ctx = context()
     compose!(ctx, circle(aes.x, aes.y, size, geom.tag), fill(aes.color)) 
    return compose!(context(order=4), svgclass("geometry"), ctx)
end

point2 = PointGeom2

D=DataFrame(x=1:5, y=randn(5), size=(1:5)/10, col=["a","b","b","a","c"])
size = D[:size]
p = plot(D,x=:x,y=:y, color=:col, point2)
```

Now back to the current version of Gadfly.  I think the issue with the size aesthetic (which seems to require an array of type `Measure`) is not in the point geometry render function itself [https://github.com/dcjones/Gadfly.jl/blob/master/src/geom/point.jl], but occurs earlier and hence may take some time sort out.
