### ISSUE TITLE
Missing data points with Geom.beeswarm 

### ISSUE THREAD

**Issue by samoconnor** [GiovineItalia/Gadfly.jl#846]
_[update: see patch for possible fix [below](https://github.com/dcjones/Gadfly.jl/issues/846#issuecomment-219632393)]_

The first example below shows a beeswarm plot of 11 data points.
The second example is the same dataset except that a few of the `x=b` points are moved from `1` to `2`.
These points no longer show up on the plot, only 8 points appear on the plot.

``` julia
julia> t = DataFrame(x = [:a,:a,:a,  :b,:b,:b,:b,:b,:b,:b,:b],
                     y = [ 1, 2, 3,   1, 1, 2, 2, 2, 2, 1, 2],
                     c = [:A,:A,:B,  :B,:A,:A,:A,:A,:A,:B,:A])

julia> draw(PNG("test.png", 3inch, 4inch),
            plot(t, x = :x, y = :y, color = :c, Geom.beeswarm))
```

![test](https://cloud.githubusercontent.com/assets/8266283/15311780/8414d86c-1c41-11e6-9f1d-2050ee5f9a59.png)

``` julia
julia> t = DataFrame(x = [:a,:a,:a,  :b,:b,:b,:b,:b,:b,:b,:b],
                     y = [ 1, 2, 3,   2, 2, 2, 2, 2, 2, 2, 2],
                     c = [:A,:A,:B,  :B,:A,:A,:A,:A,:A,:B,:A])
11x3 DataFrames.DataFrame


julia> draw(PNG("test.png", 3inch, 4inch),
            plot(t, x = :x, y = :y, color = :c, Geom.beeswarm))
```

![test](https://cloud.githubusercontent.com/assets/8266283/15311664/852c762a-1c40-11e6-896f-58350b0be124.png)

**Comment by samoconnor** [comment]
Simpler example where only 5 out of 6 points are plotted:
```julia
julia> t = DataFrame(x = [:b,:b,:b,:b,:b,:b], y = [ 2, 2, 2, 2, 2, 2])
julia> draw(PNG("test.png", 3inch, 4inch), plot(t, x = :x, y = :y, Geom.beeswarm))
```

![test](https://cloud.githubusercontent.com/assets/8266283/15311995/9ec1e4d2-1c43-11e6-869b-a76cd4c8a5ac.png)

**Comment by lobingera** [comment]
i can't qualify, but with a first look at the code i'd say, that there might be constraints, that keep points overlap and that you seen in all your tests exactly max 5 points is an indication. You could render to a SVG (or other vector formats) and look inside or put to a gist. It should be visible that Gadfly tries to draw 6 points into 5 positions.

**Comment by samoconnor** [comment]
This seems to help...

```patch
diff --git a/src/geom/beeswarm.jl b/src/geom/beeswarm.jl
index 7a08505..3242e36 100644
--- a/src/geom/beeswarm.jl
+++ b/src/geom/beeswarm.jl
@@ -115,7 +115,7 @@ function render(geom::BeeswarmGeometry, theme::Gadfly.Theme, aes::Gadfly.Aesthet
                             if !overlaps[k] continue end

                             if sqrt((candidate_off - offsets[k].value)^2 +
-                                    (absvals[i] - absvals[k])^2) < point_dist
+                                    (absvals[i] - absvals[k])^2) < point_dist * 0.999
                                 candidate_has_overlap = true
                                 break
                             end
```

**Comment by lobingera** [comment]
... and this does what? (read as: putting magical constants in the code is one of the ways to make it not-understandable in the long term...)

**Comment by samoconnor** [comment]
@lobingera: I'm not proposing that this patch be applied, I'm posting it here because I hope it makes the cause of the bug obvious to the author of the code, and they can then make an appropriate fix. I don't understand the code enough to propose a fix.

The source of the bug seems to be that floating point numbers are being used to keep track of discreet offset slots for points that have the same y value. There ends up being a comparison like `1.9 <  1.9000000000000001` which is true in a situation where the author intended `1.9 < 1.9` to evaluate to false. The patch above makes sure the comparison is false when the two values are approximately equal.

I suspect that the "right answer" is to use integers instead of floating point multiples of 1.9.
@dcjones ?

**Comment by samoconnor** [comment]
@darwindarak? @timholy?

**Comment by samoconnor** [comment]
I note that Gadfly updates and issue responses have slowed down dramatically in the last 6 months.

I assume that Julia Computing's use of Gadfly in [promotional material](http://juliacomputing.com/juliabox) is an indication that they will continue to support Gadfly.
@JeffBezanson @StefanKarpinski Is this a fair assumption? Does Julia Computing intend to: assign resources to Gadfly bug fixes? ... move Gadfly to `JuliaLang/Gadfly.jl` as some point? or do you intend to take a hands-off approach and let the market decide which plotting package will be the de-facto standard.
https://github.com/tbreloff/Plots.jl ?

**Comment by darwindarak** [comment]
It's really unfortunate that the development have been slowing down. I think a lot of people who work on Gadfly are students.  At least in my case, it's getting more difficult to make excuses for digging through the Gadfly code base instead of working towards my dissertation.  Keeping up with the fast moving changes to the Julia language itself is also a challenge.  Hopefully I'll have more time to look over some of these issues once the summer starts.

**Comment by lobingera** [comment]
@samoconnor 
The situation in standardised julia plotting is diverse and (imho) will stay like this. I'd expect some changes after JuliaCon, but rather a move of Gadfly/Compose to JuliaGraphics (or similar) than JuliaLang (actually from some discussions i get the picture more packages will be moved out from JuliaLang).
Gadfly gets some attention by core julia developers and there are activities around to bring it to v0.5, so i guess it will be available in one form or another for longer time.
Tom Breloff (main driver of Plots.jl) is positive to replace Gadfly in long-term by extending the scope of Plots.jl.

And we should not exclude you. If your solution is tangible and you can provide some testing along that, a PR shouldn't be too complicated...

**Comment by samoconnor** [comment]
Bump @bjarthur ?

**Comment by bjarthur** [comment]
@samoconnor thanks for including a test case and a possible solution to this issue.  makes it much easier for us.

i can confirm your patch works, but offer this alternative instead:

```
diff --git a/src/geom/beeswarm.jl b/src/geom/beeswarm.jl
index 9be8ad8..a380bdd 100644
--- a/src/geom/beeswarm.jl
+++ b/src/geom/beeswarm.jl
@@ -43,6 +43,7 @@ function render(geom::BeeswarmGeometry, theme::Gadfly.Theme, aes::Gadfly.Aesthet
         end
 
         point_dist = (2*theme.point_size + geom.padding).value
+        point_dist += eps(point_dist)
         offsets = Array{Length{:mm}}(length(val))
         positions = Array{Compose.Measure}(length(val))
```

since @dcjones is the original author of `Geom.beeswarm`, as indicated by git blame, perhaps he could comment whether this is a reasonable solution?  if so, either i or sam could submit a PR.

**Comment by samoconnor** [comment]
@bjarthur LGTM Thx!
