### ISSUE TITLE
Missing labels (sometimes) with hide_overlaps = true

### ISSUE THREAD

**Issue by evanfields** [GiovineItalia/Gadfly.jl#868]
Sometimes, some labels fail to render. Here's a small example:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32


julia> srand(47); plot(x = rand(4), y = rand(4), label = map(string, 'a':'d'), Geom.point, Geom.label)
```

And the output:
![badlabels](https://cloud.githubusercontent.com/assets/10092265/17678351/bac141de-6304-11e6-9010-8f3f4a21be4b.PNG)

Notice the missing label by the upper-left point. With `hide_overlaps = false` the label renders. The manual says `hide_overlaps = true` hides labels that would otherwise overlap another label or be drawn outside the plot panel, neither of which is true here.
![alllabels](https://cloud.githubusercontent.com/assets/10092265/17678568/a7973d6a-6305-11e6-8d38-50e93d4a6900.PNG)

**Comment by tlnagy** [comment]
It might be that `b` in the first plot is drawn outside of the plot area and that's why it is hidden. The label passing algorithms for `hide_overlaps=true` and `hide_overlaps=false` differ in their exact label placements so I guess `hide_overlaps=true` algorithm should be tweaked to draw `b` within the plot area.
