### ISSUE TITLE
Color aesthetic issue with Julia 0.5-rc4?

### ISSUE THREAD

**Issue by Mattriks** [GiovineItalia/Gadfly.jl#900]
Can anyone replicate this error?  I'm using Julia 0.5-rc4, Gadfly 0.4.4, and IJulia 1.3 (note I've used the REPL below for convenience). The error doesn't occur:
- if I output to a PNG file
- in any case, with Julia 0.5-rc3
- in any case, if you leave out the `color=id` aesthetic from the plot statement.

![rc4](https://cloud.githubusercontent.com/assets/18226881/18617343/c20009ea-7e10-11e6-9407-c582f98492c5.png)

**Comment by tlnagy** [comment]
Are you using the masters for Gadfly and Compose?

**Comment by tlnagy** [comment]
I can reproduce this on 0.5-rc4. Shoot.

**Comment by tlnagy** [comment]
As far as I'm able to tell, this looks like a bug in Base.

**Comment by Mattriks** [comment]
Yes, using masters. Since the error doesn't occur in 0.5-rc3 (image below), it seems that some change has been made in 0.5-rc4, such that a conflict occurs between `Gadfly` and `Base`. 

![rc3](https://cloud.githubusercontent.com/assets/18226881/18620641/ec7a9390-7e59-11e6-979f-4ec9e609de57.png)

Is it related to those `#NULL` statements  ?

**Comment by tlnagy** [comment]
Yeah it probably is related to that. Let me see if I can make a minimal example. Kind of hard to post this to base as an issue until we narrow this down a bit.

**Comment by tlnagy** [comment]
This works on RC4

```julia
julia> a = Dict(Type, Nullable{Type})
ERROR: MethodError: no method matching Dict{K,V}(::Type{Type}, ::Type{Nullable{Type}})
Closest candidates are:
  Dict{K,V}(::Any) at dict.jl:383
  Dict{K,V}{T}(::Any) at sysimg.jl:53

julia> a = Dict{Type, Nullable{Type}}()
Dict{Type,Nullable{Type}} with 0 entries

julia> a[Int64] = Nullable{Float64}()
Nullable{Float64}()

julia> show(a)
Dict{Type,Nullable{Type}}(Pair{Type,Nullable{Type}}(Int64,#NULL))
```

**Comment by tlnagy** [comment]
The error is pointing to `dict.jl:71` which was last touched by @vtjnash between RC3 and RC4. The corresponding Compose code hasn't changed in three years. https://github.com/JuliaLang/julia/commit/256a29627b79690eb5e43bc90ffe78c4efd13005 looks like it made a lot of changes to printing dicts and might be the culprit here.

**Comment by vtjnash** [comment]
This might be fixed by https://github.com/JuliaLang/julia/pull/18534, but I don't seem to be able to reproduce right now since I get:
```julia
julia> using Gadfly

julia> id = ["a","a","b","b","c"];

julia> p = plot(x=1:5, y=rand(5), color=id, Geom.point); draw(PNG(4inch, 3.3inch), p);
ERROR: UndefVarError: minheight not defined
 in realize_brute_force(::Compose.Table, ::Compose.ParentDrawContext) at /Users/jameson/.julia/v0.6/Compose/src/table.jl:246
 in drawpart(::Compose.Image{Compose.PNGBackend}, ::Compose.Table, ::Compose.IdentityTransform, ::NTuple{4,Float64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/jameson/.julia/v0.6/Compose/src/container.jl:472
 in drawpart(::Compose.Image{Compose.PNGBackend}, ::Compose.Context, ::Compose.IdentityTransform, ::NTuple{4,Float64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/jameson/.julia/v0.6/Compose/src/container.jl:590 (repeats 2 times)
 in draw(::Compose.Image{Compose.PNGBackend}, ::Compose.Context) at /Users/jameson/.julia/v0.6/Compose/src/container.jl:434
 in draw(::Compose.Image{Compose.PNGBackend}, ::Gadfly.Plot) at /Users/jameson/.julia/v0.6/Gadfly/src/Gadfly.jl:822
```

**Comment by tlnagy** [comment]
@vtjnash That's really weird, must be something that has been changed upstream.

**Comment by Mattriks** [comment]
Just updating that my original issue occurs in Julia 0.5.0 release. Gadfly plots with a  `color` aesthetic don't plot to screen when using a `PNG` backend (they will plot to file).

**Comment by tlnagy** [comment]
Paging @vtjnash again, this is a problem. Thanks for checking

**Comment by Mattriks** [comment]
I've been using Julia-0.6-pre.alpha for a while, and this issue has disappeared.  Hope it doesn't reappear in the anticipated 0.6-rc's!

**Comment by bjarthur** [comment]
if this is no longer a problem in 0.6 we should close this issue.

**Comment by Mattriks** [comment]
Ok by me. Also #936 is a duplicate of this.
