### ISSUE TITLE
Geom.line not drawn after NaNs in SVGs

### ISSUE THREAD

**Issue by mortenpi** [GiovineItalia/Gadfly.jl#903]
It seems that #566 might be back. After a point surrounded by `NaN`s/`Inf`s, the line is no longer drawn (but it only seems to affect the interactive case).

To reproduce:

``` julia
data = Float64[1.0, 2.0, NaN, 4.0, NaN, 6.0, 7.0]
plot(x = 1:length(data), y = data, Geom.line, Geom.point)
```

yields in Atom (and Jupyter)
![bug_atom](https://cloud.githubusercontent.com/assets/147757/18876734/145cd57c-84cb-11e6-86b4-d7d2cb489068.png)

The expectation is that the two last points should be connected with a line.
![bug](https://cloud.githubusercontent.com/assets/147757/18876504/4a95bdb2-84ca-11e6-9ee3-dab9d11de9d6.png)

Interestingly, when I `draw()` the plot into a file (e.g. `draw(SVG("file.svg", ..), plot)`), then the SVG output is fine. Also, drawing a PNG (and presumably the other Cairo ones) interactively (i.e. `draw(PNG(w,h), plot)`) and to a file work as well.

Gadfly and Compose are both v0.4.4, issue is present in both Julia v0.4 and v0.5.

**Comment by tlnagy** [comment]
Nice catch. Not sure what is going on here.

**Comment by bjarthur** [comment]
@mortenpi i don't used atom or jupyter so am not in a position to help.  i'd suggest debugging the problem by checking out successively older and older versions of Gadfly until you reach a version that plots this test case correctly.  then we can do a diff to see what change might have broken it.
