### ISSUE TITLE
Move Gadfly and related packages to an organization

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#910]
Since @dcjones is currently busy with other things, it would be nice to move Gadfly and related packages under an umbrella org to keep everything as a smooth operating machine. Here's a (hopefully) complete list of dependencies that *are not* currently managed by an org:

- [x] Gadfly -> now at @GiovineItalia
- [x] Compose -> now at @GiovineItalia
- [x] Fontconfig --> JuliaGraphics
- [x] Measures --> JuliaGraphics
- [x] Loess --> JuliaStats
- [ ] ~~Codecs~~*
- [ ] ~~Showoff~~ (Handled by JuliaGraphics)
- [x] Hexagons

Now, as always, one of the hardest questions is what to name this new Org. We have several excellent, competing plotting libraries. It would nice to name it in such a way that it doesn't conflict with these. @shashi @tkelman @Mattriks, @rsrock what do you all think?

\* The dependency on Codecs appears to be vestigial and all tests pass when I removed it and grepping through the package gave no indication of calls to any of its exported functions.

**Comment by tkelman** [comment]
Showoff was redirected to JuliaGraphics. That can be merged with the original if needed (will need some care, but doable).

**Comment by tlnagy** [comment]
We can scratch Showoff then since JuliaGraphics is handling it, commit-wise they are identical except the JuliaGraphics fork has a couple fixes.

**Comment by lobingera** [comment]
Does all packages need to be in the same org?

**Comment by tlnagy** [comment]
Not necessarily. Fontconfig could get moved to be in JuliaGraphics with Cairo, for example.

**Comment by lobingera** [comment]
That's what i thought, also. Loess might find counterparts in optimization or statistics...

**Comment by dcjones** [comment]
In case I haven't said so publicly, I'm all for moving Gadfly and related packages to an organization. I'd like to make an organization specifically for Compose and Gadfly. Those packages are very specific approaches that feel like a bad fit for a very broad organization like JuliaGraphics. I'm fine with other packages that @tlnagy listed being split up to JuliaGraphics or elsewhere though.

**Comment by tlnagy** [comment]
Thanks for the input @dcjones. I updated the OP with where I think packages should be moved. The remaining ones: Gadfly, Compose, and Hexagons should probably go under their own organization. Breaking tradition with most other Julia orgs which are named Julia* to sound official. We could use Gadfly as the organization name, i.e. dcjones/Gadfly.jl would get moved to Gadfly/Gadfly.jl. Thoughts? @ViralBShah @JeffBezanson @tkelman

**Comment by tlnagy** [comment]
It looks like Gadfly is already taken as an organization name. Any other suggestions?

**Comment by aviks** [comment]
I was about to say that `Gadfly/Gadfly.jl` is the best option, when I saw @tlnagy's comment above. Unfortunate.  But in general, I its a good to move Gadfly and Compose to their own org, together. 

GadflyCharts/GadflyGraphics ??

**Comment by dcjones** [comment]
The "Gadfly" account hasn't had any activity in over four years. It's maybe a long shot, but I contacted support to see if I could take possession.

**Comment by tlnagy** [comment]
Yeah, I saw that. We probably have a pretty strong argument. @dcjones could you do that? It would be nice to have the Gadfly/Gadfly.jl domain :)

**Comment by Keno** [comment]
GitHub will definitely clear up unused names. That's how I got mine ;).

**Comment by ViralBShah** [comment]
How about `JuliaGG`?

**Comment by ViralBShah** [comment]
@keno did you not use to be loladiro? Wow that was so long ago.

**Comment by Keno** [comment]
I did (until about two years ago). Some of my packages in .julia still use that as their remotes.

**Comment by dcjones** [comment]
I've created an organization to house Compose and Gadfly. As to cede no ground on the weird name precedent it's called @GiovineItalia (Gadfly was named arbitrarily after a novel called *The Gadfly* in which the protagonist publishes subversive pamphlets under the name The Gadfly as part of the Giovine Italia revolutionary organisation).

Let me know if there are links I need to update, or people who need to be added or promoted.

**Comment by ararslan** [comment]
If Loess is going to move to JuliaStats, let me know if there's anything I can do to help out on the JuliaStats end.

**Comment by StefanKarpinski** [comment]
IMO, JuliaGraphics seems like a more sensible place for Gadfly, for what it's worth. Or maybe a JuliaPlots umbrella org for various plotting packages.

**Comment by tlnagy** [comment]
I was originally against using a name like JuliaPlots as an org name because that would be implying favorites among the many great competing plotting packages in Julia.

**Comment by aviks** [comment]
I think the size of the plotting ecosystem, and the diversity of design (and thus userbase) makes it worth it to have multiple orgs in this area.

**Comment by ararslan** [comment]
@dcjones I've invited you to JuliaStats so that you can transfer ownership of Loess.jl if you'd like.

**Comment by dcjones** [comment]
Thanks @ararslan. Loess is now in JuliaStats, Measures and Fontconfig in JuliaGraphics, and Hexagons in GiovineItalia.

**Comment by tlnagy** [comment]
All done! 🎉

**Comment by ararslan** [comment]
Thank you @dcjones and all of the fantastic maintainers for your immeasurable contributions to the Julia community!

**Comment by tkelman** [comment]
Someone will need to re-enable CI services
