### ISSUE TITLE
Swapping color and shape for binary variables is not isomorphic

### ISSUE THREAD

**Issue by tpospisi** [GiovineItalia/Gadfly.jl#918]
I've run into a plotting error in which choosing my aesthetics changes which points are distinguished.  I have two binary variables (color and shape).  When I use the following code:

`plot(df, x = "x", y = "y", color = "color", shape = "shape")`

I get this figure which is correct (it agrees with constraints I know hold):

![correct](https://cloud.githubusercontent.com/assets/8901856/19371547/0a4b7764-9182-11e6-97e2-d0cb9c276aa6.png)

However, when I use this code:

`plot(df, x = "x", y = "y", shape = "color", color = "shape")`

I get this figure which is not correct:

![incorrect](https://cloud.githubusercontent.com/assets/8901856/19371551/0daef78c-9182-11e6-8b68-fee98b91af0c.png)

The difference is most obvious at the farthest right point.  In the correct graph it's a red circle like the rest of the upper cluster.  In the incorrect graph it's red and square while the upper cluster is blue and square.

This should not be the case.  The two graphs should be isomorphic since points which share the same characteristics in the first graph should share the same characteristics in the second.

Data to reproduce here: [example-data.txt](https://github.com/GiovineItalia/Gadfly.jl/files/528425/example-data.txt)

**Comment by Mattriks** [comment]
This is a bit confusing.  Why did you not do:
```julia
plot(df, x="x", y="y", shape="shape", color="color") 
```
in the second line of code above?

**Comment by tpospisi** [comment]
The naming of the variables is somewhat confusing.  What I've called "color" is class labels and "shape" indicates support vectors for an SVM solution.

I had initially wanted to have the second mapping: `plot(df, x="x", y="y", shape="support", color="class")` but as mentioned above, this doesn't make the correct figure.  On a whim I then decided to try the first mapping `plot(df, x="x", y="y", color="support", shape="class")` which does make the correct figure.

**Comment by tlnagy** [comment]
Could you create a minimal example? It would help us diagnose the issue here because `color` and `shape` should be isomorphic.

**Comment by tpospisi** [comment]
Here's a minimal example
```
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 0, 0, 0, 0, 0, 0, 0]

a = [0, 0, 0, 0, 1, 1, 1, 1]
b = [1, 0, 1, 0, 1, 0, 1, 0]

plot(x = x, y = y, shape = a, color = b)
plot(x = x, y = y, shape = b, color = a)
```

The graphs aren't isomorphic: look at the second and fourth points.  More troubling, neither gets the color pattern correct.  The shapes are correct in both.

The first figure is 
![shape-a-color-b](https://cloud.githubusercontent.com/assets/8901856/19413462/b14265a8-92fb-11e6-942c-23836363b5a1.png)

Points 5:8 are the wrong colors.

The second figure is
![color-a-shape-b](https://cloud.githubusercontent.com/assets/8901856/19413470/dc7b8f06-92fb-11e6-8822-d7d72f9a812a.png)

Points 2 and 6 are the wrong colors.

**Comment by tlnagy** [comment]
That's bad. It must've been a bug introduced when the shape code got merged.

**Comment by bjarthur** [comment]
this issue will be fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/991 once merged
