### ISSUE TITLE
Gadfly precompilation is very slow

### ISSUE THREAD

**Issue by ExpandingMan** [GiovineItalia/Gadfly.jl#919]
I know there was a different issue a while back where `using Gadfly` would take a long time, but I haven't seen anything else related to this.

I've long noticed that any code which uses gadfly (i.e. any simple plotting, whatever) takes a very long time to compile relative to pretty much anything else.  (It does however, run nice and fast.)  I'm assuming this is well known, but I was wondering what's causing this, and whether there is any intention to fix it.  Thanks all.

**Comment by tlnagy** [comment]
Gadfly depends on a lot of Julia code so it takes a while to precompile everything. I do believe that it could be sped up, but until we have conditional modules, we are always going to be at the mercy of all the packages that we depend on. That said, I'm sure there are things that we could do better too. I don't know if anyone has profiled Gadfly and seen where we spend the bulk of our time during precompilation.

**Comment by tlnagy** [comment]
Closed in favor of #921
