### ISSUE TITLE
PNG, SVG backends create plots with checkerboard background, labels and title don't scale

### ISSUE THREAD

**Issue by dwschulze** [GiovineItalia/Gadfly.jl#924]
The PNG and SVG backends create plots that with a checkerboard background that makes the data almost impossible to see.  The title and axis labels don't scale.  This makes png and svg plots unusable.

**Comment by lobingera** [comment]
I think you see this as artifact of a transparent Background. What Viewer do you use on which Plattform?

**Comment by tlnagy** [comment]
See https://github.com/GiovineItalia/Gadfly.jl/issues/534#issuecomment-71927696 for how to force a white background.

**Comment by tlnagy** [comment]
Please re-open this if we didn't fix your problem.
