### ISSUE TITLE
join JuliaGraphics?

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#926]
since ShowOff and Immerse are both in JuliaGraphics, would it make sense to move Gadfly there too?  some discussion [here](https://groups.google.com/forum/#!topic/julia-users/Qx5CDrbFQPA).

**Comment by Hydrotoast** [comment]
I am also wondering what this `GiovineItalia` organization is and when this repository was moved. `JuliaGraphics` seems like a more appropriate organization to be a part of.

**Comment by vchuravy** [comment]
See the discussion in https://github.com/GiovineItalia/Gadfly.jl/issues/910
The original author dcjones, decided that Gadfly and Compose should not belong to JuliaGraphics or JuliaPlots and I think we should honour that decision.
