### ISSUE TITLE
pango crash trying to print a string with "<" in it

### ISSUE THREAD

**Issue by protogeezer** [GiovineItalia/Gadfly.jl#927]
It seems like this shouldn't crash.

(1) can pango be turned off when I just want to put a string on a plot? (the documentation describes a programmatic escape mechanism - in the C/C++ api.
(2) there seems to be no documentation anywhere that explains how to type Pango acceptable markup. 

------
(process:19033): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 16: '=' is not a valid character following a '<' character; it may not begin an element name
Error showing value of type Gadfly.Plot:
ERROR: Could not parse pango markup.
 in pango_to_svg(::String) at /Users/sjbespa/.julia/v0.5/Compose/src/pango.jl:374
 in draw(::Compose.SVG, ::Compose.TextPrimitive{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Compose.Rotation{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}}, ::Int64) at /Users/sjbespa/.julia/v0.5/Compose/src/svg.jl:935
 in draw(::Compose.SVG, ::Compose.Form{Compose.TextPrimitive{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Compose.Rotation{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/svg.jl:781
 in drawpart(::Compose.SVG, ::Compose.Context, ::Compose.IdentityTransform, ::Compose.UnitBox{Int64,Int64,Int64,Int64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:558
 in drawpart(::Compose.SVG, ::Compose.Context, ::Compose.IdentityTransform, ::Compose.UnitBox{Int64,Int64,Int64,Int64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:590 (repeats 3 times)
 in drawpart(::Compose.SVG, ::Compose.AdhocContainerPromise, ::Compose.IdentityTransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:477
 in drawpart(::Compose.SVG, ::Compose.Context, ::Compose.IdentityTransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:590 (repeats 2 times)
 in drawpart(::Compose.SVG, ::Compose.Table, ::Compose.IdentityTransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:477
 in drawpart(::Compose.SVG, ::Compose.Context, ::Compose.IdentityTransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:590 (repeats 2 times)
 in draw(::Compose.SVG, ::Compose.Context) at /Users/sjbespa/.julia/v0.5/Compose/src/container.jl:434
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/html")}, ::Gadfly.Plot) at /Users/sjbespa/.julia/v0.5/Gadfly/src/Gadfly.jl:1082
 in macro expansion at ./multimedia.jl:143 [inlined]
 in display(::Gadfly.Plot) at /Users/sjbespa/.julia/v0.5/Gadfly/src/Gadfly.jl:1034
 in hookless(::Media.##7#8{Gadfly.Plot}) at /Users/sjbespa/.julia/v0.5/Media/src/compat.jl:14
 in render(::Media.NoDisplay, ::Gadfly.Plot) at /Users/sjbespa/.julia/v0.5/Media/src/compat.jl:27
 in display(::Media.DisplayHook, ::Gadfly.Plot) at /Users/sjbespa/.julia/v0.5/Media/src/compat.jl:9
 in macro expansion at ./multimedia.jl:143 [inlined]
 in display(::Gadfly.Plot) at /Users/sjbespa/.julia/v0.5/Gadfly/src/Gadfly.jl:1038
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at /usr/local/lib/julia/sys.dylib:?
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
 in _start() at ./client.jl:360
 in _start() at /usr/local/lib/julia/sys.dylib:?

**Comment by lobingera** [comment]
As the calls to pango are hard coded, we have to live with pango markup. Unfortunately the gnome developer pages are currently down, so i can't attach a proper link. But there is documentation in pango.
If you want to see an example, i'm contributing a pango text sample with:
https://github.com/lobingera/Cairo.jl/blob/6419d6bbbc070bc2ca6f6eac1906d259f0997771/samples/sample_pango_text.jl

**Comment by lobingera** [comment]
https://developer.gnome.org/pango/1.40/PangoMarkupFormat.html

**Comment by protogeezer** [comment]
Andreas:

Thanks for the example. Between the example and this StackExchange thread:
http://stackoverflow.com/questions/36880531/does-gadfly-support-latex-in-plot-titles-and-labels
I was able to figure out how to get the small equations into my labels.

It appears that HTML/GML some text entities don't work with pango. For example &gt and &equal. Using the latex features in the REPL to sidestep the text entities is the way to go for the time being.

Stephen
