### ISSUE TITLE
Adding color for legend causes bars to be all positive

### ISSUE THREAD

**Issue by sspaenig** [GiovineItalia/Gadfly.jl#928]
Hi,

`v = DataFrame(x = [1,2,3], y = [0.5,-0.7,1.2], label = ["a","b","c"])`
`plot(v , x=:x, y=:y, Geom.bar, Theme(bar_spacing = 2mm), Guide.title("geneX"), Guide.ylabel("fold change"), Guide.xlabel("technique"), color = :label)`
produces the following plot:

![a](https://cloud.githubusercontent.com/assets/8007694/20063818/d9f8ae5c-a508-11e6-889d-bc0e50aeb1e7.png)

(the snd bar should be negativ)

`#  without 'color = :label'`
`plot(v , x=:x, y=:y, Geom.bar, Theme(bar_spacing = 2mm), Guide.title("geneX"), Guide.ylabel("fold change"), Guide.xlabel("technique"))` 

![a](https://cloud.githubusercontent.com/assets/8007694/20064053/a3f16af0-a509-11e6-887b-763a39aa9187.png)

Best regards,

Sebastian

**Comment by tlnagy** [comment]
This definitely looks like a bug introduced by the color assignment code.

**Comment by bjarthur** [comment]
oi, it's even worse now as all the bars are negative.  i'll look into this.  in the meantime, the hack is to use `Geom.bar(position=:dodge)`.

**Comment by bjarthur** [comment]
please checkout https://github.com/GiovineItalia/Gadfly.jl/pull/1030 and let me know if it doesn't fix this for you.  thanks.
