### ISSUE TITLE
Preparing for v0.6

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#930]
What needs to be updated to get Gadfly working on Julia v0.6

## Packages that need updates

- [x] Update Colors stack (https://github.com/JuliaGraphics/Colors.jl/pull/275, https://github.com/JuliaGraphics/ColorTypes.jl/pull/73, etc)
- [x] Update Compose.jl (https://github.com/GiovineItalia/Compose.jl/pull/240)
- [x] Update Lazy.jl (https://github.com/MikeInnes/Lazy.jl/pull/55)
- [ ] Update Gadfly proper (https://github.com/GiovineItalia/Gadfly.jl/pull/973)
- [x] Update Showoff.jl (https://github.com/JuliaGraphics/Showoff.jl/pull/1)
- [x] Update Measures.jl (https://github.com/JuliaGraphics/Measures.jl/pull/12)
- [x] Update Hexagons.jl 
- [x] Update RData.jl (fixed in https://github.com/JuliaStats/RData.jl/releases/tag/v0.1.0)

## Packages that need to be tagged

- [ ] Compose.jl
- [ ] Gadfly.jl
- [x] Hexagons.jl
- [x] Showoff.jl
- [x] Measures.jl
- [x] Loess.jl

**Comment by tlnagy** [comment]
Recent builds are completely broken now on master so this is high priority for the v0.6 release.

**Comment by tlnagy** [comment]
Actually, the current breakage looks to be caused by https://github.com/JuliaStats/DataArrays.jl/issues/226.

**Comment by bjarthur** [comment]
should do Measure.jl as well

**Comment by bjarthur** [comment]
it's time to do Gadfly proper.  i'm anxious to see if the time-to-first plot will improve with julia 0.6.  does anyone want to take a stab at it?  or shall i??

**Comment by lobingera** [comment]
Please do. (just for the record: there are too many issues out there with reports on v0.6 compiler/precompiler performance, that i'd expect it's even slower...)

**Comment by tlnagy** [comment]
Please go ahead. I'll be happy to review the PR! I appreciate your help
on this.

**Comment by bjarthur** [comment]
maybe tag Loess too?

**Comment by tlnagy** [comment]
Loess is tagged and I'm waiting for a merge: https://github.com/JuliaLang/METADATA.jl/pull/8804

**Comment by bjarthur** [comment]
closed by https://github.com/GiovineItalia/Gadfly.jl/pull/973
