### ISSUE TITLE
Estimating Center of Contours

### ISSUE THREAD

**Issue by Sparks679** [GiovineItalia/Gadfly.jl#931]
Greetings,

I am new to programming and github so I apologize if I am asking dumb questions.

I have one question for which I could not find an answer on gadflyjl.org:

I was wondering if there was a way to estimate (and mark) the center of a given contour when using Geom.contour.

Thank you in advance!

**Comment by Sparks679** [comment]
The issue has been resolved

**Comment by tlnagy** [comment]
Can you detail how you solved it so other people can also learn? thanks!
