### ISSUE TITLE
Plot appears to hang when plotting certain vectors (case 2)

### ISSUE THREAD

**Issue by gustafsson** [GiovineItalia/Gadfly.jl#932]
The symptoms are very similar to #550. But this isn't a regression failure. The example shown in #550 works today but I found another couple of vectors that currently hangs Gadfly.

Examples
```
plot(x=[1,2], y=[10.0,  10.0000000000001])  # works
plot(x=[1,2], y=[100.0, 100.000000000001])  # works
plot(x=[1,2], y=[1000.0,1000.00000000001])  # works

plot(x=[1,2], y=[10.0,  10.00000000000001]) # hangs
plot(x=[1,2], y=[100.0, 100.0000000000001]) # hangs
plot(x=[1,2], y=[1000.0,1000.000000000001]) # hangs
```

**Comment by tlnagy** [comment]
Interesting. Can you still see on the master branch?

**Comment by gustafsson** [comment]
Yes

**Comment by tlnagy** [comment]
It looks like Gadfly is getting stuck optimizing the ticks in these two while loops: https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/ticks.jl#L92-L106.
