### ISSUE TITLE
About boxplot

### ISSUE THREAD

**Issue by suman12029** [GiovineItalia/Gadfly.jl#938]
I think the graphics should be pleasant to view and they should well represent the data. Boxplot with gadfly would look great **if it would** have looked the way the boxplots are in **seaborn**(http://seaborn.pydata.org/generated/seaborn.boxplot.html) and **ggplot2** (https://plot.ly/ggplot2/box-plots/).

Hope to see the change in next version.

Best regards,

**Comment by aviks** [comment]
You'll have to be more specific about what you see as the differences and/or drawbacks. I'm not sure what needs doing here.

**Comment by tlnagy** [comment]
I agree with @aviks here. Closing this issue for now, feel free to re-open it if you have specifics in mind.

**Comment by suman12029** [comment]
I mean the median is represented in the box is incomplete.
![capture](https://cloud.githubusercontent.com/assets/8075886/21101813/124bac22-c0a3-11e6-9e0e-c425f80e169a.PNG)
The line representing the median doesn't run through the whole width of box and also default plot as compared to the seaborn package is less aesthetically pleasing.

Regards,
