### ISSUE TITLE
How can I plot a complex function in a general form?

### ISSUE THREAD

**Issue by xiaohk** [GiovineItalia/Gadfly.jl#944]
To plot a function, it seems Gadfly requires to write a real Julia function. I got a function like :
![image](https://cloud.githubusercontent.com/assets/15007159/21700303/6fed978a-d365-11e6-8093-a16f70ec201e.png)
It is pretty hard to convert it to a deterministic Julia function. I am wondering how can I plot it?

**Comment by Mattriks** [comment]
Does this example help (using [`Geom.contour`](http://gadflyjl.org/stable/lib/geoms/geom_contour.html#Geom.contour-1))? If not, please be clearer about what variables you are trying to plot.
```julia
f{T<:Float64}(x::T, y::T, a::Vector{T}) =  dot(a,[x^2, x*y, y^2])
a = [1.0, 2.0, 3.0]
p = plot((x,y)->f(x,y,a), -3.0, 3.0, -3.0, 3.0, Geom.contour)
```
![issue944a](https://cloud.githubusercontent.com/assets/18226881/21701615/c658d8d8-d3fa-11e6-8741-1e8139522d31.png)

**Comment by xiaohk** [comment]
Thanks @Mattriks, this is exactly what I am looking for! Could you please explain the argument `levels` to me?

Here is my code:

```julia
function decision(x1::Float64, x2::Float64, a::Array{Float64})
    dot(a, [1, x1^1*x2^0, x1^0*x2^1, x1^2*x2^0, x1^1*x2^1, x1^0*x2^2, 
            x1^3*x2^0, x1^2*x2^1, x1^1*x2^2, x1^0*x2^3, x1^4*x2^0, x1^3*x2^1,
            x1^2*x2^2, x1^1*x2^3, x1^0*x2^4, x1^5*x2^0, x1^4*x2^1, x1^3*x2^2,
            x1^2*x2^3, x1^1*x2^4, x1^0*x2^5, x1^6*x2^0, x1^5*x2^1, x1^4*x2^2, 
            x1^3*x2^3, x1^2*x2^4, x1^1*x2^5, x1^0*x2^6])
end

para = [-0.209007,-0.059501,-0.0308134,-0.194027,0.0325069,-0.177004,-0.0307239,
 0.043416,0.045251,-0.0897999,-0.115825,0.0782094,0.0232646,0.0758353,
 -0.15003,-0.0249863,0.0687696,0.0742381,0.060514,0.0702325,-0.10597,
 -0.0691998,0.086185,0.0623718,0.0912742,0.0558282,0.0861354,-0.136093]

p = plot((x1,x2) -> decision(x1, x2, mini_Θ), -1.0, 1.5, -1.0, 1.5, Geom.contour(levels = [0.0]))
```
![image](https://cloud.githubusercontent.com/assets/15007159/21726314/dc6073d2-d401-11e6-8bbf-bb65129ecf6e.png)

I only want to plot the contour where f(x,y) = 0. How can I do that please?

**Comment by Mattriks** [comment]
I investigated this, and it seems `levels` works better if arguments `x,y,z` are defined explicitly: 
```Julia
coord = Coord.cartesian(xmin=-1.0, xmax=1.5, ymin=-1.0, ymax=1.5)

p = plot(z = (x1,x2) -> decision(x1, x2, para), coord,
    x = linspace(-1.0, 1.5, 100), 
    y = linspace(-1.0, 1.5, 100),
# Try uncommenting the next line :)
#   layer(Geom.contour, Theme(line_style=[0.2mm,1mm])),
    layer(Geom.contour(levels=[0.0]), Theme(line_width=2pt)),
    Scale.color_continuous(minvalue=-6, maxvalue=2)
)

```

**Comment by xiaohk** [comment]
@Mattriks Thank you so much!!
