### ISSUE TITLE
Plot functions with y bounds

### ISSUE THREAD

**Issue by dns2utf8** [GiovineItalia/Gadfly.jl#949]
I would like to plot (lambda) functions inside a box, but the scalar options do not work:

```
plot([sin, cos], -.5, .5) # x bounds

plot([sin, cos], [ -.5 .5 ; -1 1 ]) # proposal for x and y bounds
```

Is there a way to set the y bounds as well?

**Comment by Mattriks** [comment]
It seems that Gadfly expects functions to be followed by the function input bounds, and in this case `x` is the function input (`y` is the function output). The y-range can be set using [`Coord.cartesian`](http://gadflyjl.org/stable/lib/coords/coord_cartesian.html#Coord.cartesian-1):
```Julia
coord = Coord.cartesian(ymin=-1.0, ymax=1.0)
p = plot([sin,cos], -0.5, 0.5, coord )

```

**Comment by dns2utf8** [comment]
Ah, very cool. Thank you 👍

**Comment by tlnagy** [comment]
Thanks @Mattriks!
