### ISSUE TITLE
PNG resolution

### ISSUE THREAD

**Issue by jotwin** [GiovineItalia/Gadfly.jl#966]
I'm making scatter plots with > 50k points. Its pretty slow to plot and makes somewhat large PDF files. I tried making PNG files, but its not high resolution enough for a publication. I can set the png size in pt, but then the scale of objects changes.

Is there a way to set resolution or dpi for the PNG backend?

**Comment by tlnagy** [comment]
PNG takes a `dpi` keyword:

```julia
julia> p = plot(x=rand(10), y=rand(10), Geom.point)

julia> draw(PNG("test.png", 10cm, 10cm, dpi=300), p)
```

**Comment by tlnagy** [comment]
Please open a new issue if this didn't resolve your problem.

**Comment by jerlich** [comment]
Shouldn't the options appear when a user write:
`?PNG`

**Comment by bjarthur** [comment]
more documentation would help, agreed.  care to submit a PR?  docstring would go [here](https://github.com/GiovineItalia/Compose.jl/blob/master/src/cairo_backends.jl#L186), and the relevant code is just above.

**Comment by Mattriks** [comment]
A `@doc` macro to cover the Cairo backends (PNG, PDF, PS) would work here. Also `SVG` needs a docstring.

**Comment by jerlich** [comment]
The multiple dispatch aspect of these functions is making the documentation a little tricky for me. If `PNG` (or PDF/PS) is called with a string (e.g a filename) there are limited arguments, but if I am reading the code correctly, if `PNG` is called as `PNG(surface::CairoSurface, ctx::CairoContext, out::IO` then there are far more options. Is it alright if I stick with documenting the probably commonly used `PNG(filename...)` versions?

**Comment by bjarthur** [comment]
the method with `CairoSurface` is just used internally.   so yes, just doc `filename`.  thanks in advance!
