### ISSUE TITLE
Geom.violin selects incorrect range for continuous variables

### ISSUE THREAD

**Issue by CorySimon** [GiovineItalia/Gadfly.jl#968]
![z_violin](https://cloud.githubusercontent.com/assets/4196261/24176750/34128460-0e5b-11e7-8760-a99aa355fe3d.png)

When I save using:
```
draw(PNG("z_violin.png", 5inch, 4inch, dpi=300), z_plot)
```

**Comment by tlnagy** [comment]
Yeah, this is non-ideal. A work-around for now is to use `Coord.cartesian(xmin=-0.5, xmax=1.5)`. It seems as though Gadfly isn't taking the width of the violin into account when figuring out the scaling.

**Comment by tlnagy** [comment]
I can reproduce this on Gadfly master

```julia
using Gadfly
using Distributions
using DataFrames

srand(123)
data = vcat(rand(Beta(2,5), 1000), 1-rand(Beta(2,5), 1000))
group = vcat(fill(0, 1000), fill(1, 1000))

df = DataFrame(data=data, group=group)

p = plot(df, x=:group, y=:data, Geom.violin)
draw(PNG("issue968.png", 10cm, 8cm, dpi=300), p)
```

![image](https://user-images.githubusercontent.com/1661487/40446197-4544ca08-5e83-11e8-87fc-9f2989d0716a.png)

**Comment by tlnagy** [comment]
It looks like an issue with the continuous x variable because if you use categorical variables:

```julia
srand(123)
group = vcat(fill("one", 1000), fill("two", 1000))
data = vcat(rand(Beta(2,5), 1000), 1-rand(Beta(2,5), 1000))
df = DataFrame(data=data, group=group)

p = plot(df, x=:group, y=:data, Geom.violin)
```

![image](https://user-images.githubusercontent.com/1661487/40446820-5be2e338-5e85-11e8-9175-4ea9cb2e7e35.png)

**Comment by tlnagy** [comment]
@Mattriks if you have a chance, can I get your help with this?

I tried adding the following here: https://github.com/GiovineItalia/Gadfly.jl/blob/d31554bba68194793e1c6e5afbda57111433d1c5/src/statistics.jl#L1521

```julia
# Fix for issue 968
if typeof(scales[:x]) <: Scale.ContinuousScale
    scales[:x] = Scale.x_discrete()
end
```

but scales are applied prior to statistics. I'm thinking that I might just need to through an error if they supply a continuous statistic and tell the user to use a categorical statistic.

**Comment by Mattriks** [comment]
I think making `Geom.violin` work properly with a continuous `x` scale, requires rewriting both `Stat.violin` and the render function for `Geom.violin`.  Low priority atm because of the 2 easy work arounds above (use `Coord.cartesian`  or a discrete `x` variable).

**Comment by tlnagy** [comment]
I can't think of a situation were one of the axes is not categorical for a violinplot so we should enforce that at least one of the axes is discrete. You have bin along one of the axes to form the violin.
