### ISSUE TITLE
How to get labels on the points?

### ISSUE THREAD

**Issue by jkleiser** [GiovineItalia/Gadfly.jl#972]
In the second Brain-Body plot shown at http://gadflyjl.org/stable/tutorial.html, there are labels (Owl monkey, Galago, ...) shown on each point. How is this achieved?
For me it would be much better to have labels on the points, instead of having a legend group on the right mapping colors to labels.

**Comment by Mattriks** [comment]
Did you try running the example code:
````Julia
using RDatasets, DataFrames, Gadfly
mammals = dataset("MASS", "mammals")

p=plot(mammals, x=:Body, y=:Brain, label=:Mammal,
         Geom.point, Geom.label, Scale.x_log10, Scale.y_log10)
````
See also the `Gadfly` [documentation](http://gadflyjl.org/stable/lib/geometries.html): note `Geom.label` and the aesthetic `label=:Mammal`

**Comment by Timmmm** [comment]
Future people trying to find the documentation in a sea of outdated links... It's something like this:

One-time installation:

```
using Pkg;
Pkg.add("Gadfly");
Pkg.add("DataFrames");
```

In your script:

```
using Gadfly;
using DataFrames;

df = DataFrame(age = [1, 2, 3], weight = [3, 4, 5], names = ["dave", "john", "mary"]);
plot(df, x="age", y="weight", label="names", Geom.point, Geom.label);
```

Check the date because I'm sure this will change in a few months...

**Comment by bjarthur** [comment]
docs on how to use arrays:  http://gadflyjl.org/latest/tutorial/#Arrays-1

happy to fix links if you tell me which ones are outdated.

**Comment by Timmmm** [comment]
That's weird, I could have sworn I tried something like that and it didn't work, but I just tried again and it does. :-S

Btw off-topic but I think it would also be worth explaining the `:Foo` syntax on that page, because both of these work and it's not clear what the difference is:

```
df = DataFrame(age = [1, 2, 3], weight = [3, 4, 5], names = ["dave", "john", "mary"]);
plot(df, x="age", y="weight", label="names", Geom.point, Geom.label)
plot(df, x=:age, y=:weight, label=:names, Geom.point, Geom.label)
```
