### ISSUE TITLE
Colors and Legend with Gadfly - how can I control them?

### ISSUE THREAD

**Issue by PeterJacko** [GiovineItalia/Gadfly.jl#974]
I would like to ask you if you have any advice... as I can't sort out one issue when creating plots with Gadfly in Julia v0.5.

I need to plot matrices, which have discrete values (from 0 to 127), so that each value is plotted with one colour. See the attached examples. 

I create them with the following line:

plot( x = jjj - 1 , y = iii - 1 , color = iiijjjvalues , Scale.color_discrete , Guide.xticks( ticks = collect( 0 : 5 : number_of_observations_arm_2 ) ) , Guide.yticks( ticks = collect( 0 : 5 : number_of_observations_arm_1 ) ) , Guide.xlabel( "# successes on arm 1 (out of $number_of_observations_arm_2)" ) , Guide.ylabel( "# successes on arm 0 (out of $number_of_observations_arm_1)" ) , Guide.colorkey( "Consecutive \n failures" ) , Coord.cartesian( yflip = true , fixed = true ) , Geom.point, Theme( panel_fill = nothing , highlight_width = 0pt , default_point_size = my_point_size , plot_padding = 5pt , major_label_font_size = 11pt , minor_label_font_size = 9pt ) ) ;

You can see in the legend that the same sequence of colours appears in the two plots: blue, gold, pink, green, violet, red, grey, etc. These colours appear in the plot in this order if you follow the first column from top to bottom, then then second column, etc.

However the legend then looks weird, because it would be natural to have the colours ordered by the values they correspond to (0, 1, 2, 3, 4, etc.). Moreover, as the colour ordering prevails, the same values are plotted in different colours in these two plots, which is not very helpful - I need to include many figures like this and I would prefer if I only needed one legend, the same for all of them.

I would also like to replace label 127 by $ \infty $ in the legend.

I wonder whether you would have a suggestion for a quick fix or where I could get some help with it. Basically, I need to get control of how the colours are assigned to values and how they appear in the legend.

Thanks a lot!

Peter.

Plot1:
<img width="414" alt="plot1" src="https://cloud.githubusercontent.com/assets/26435939/24907853/cc013fc2-1eb5-11e7-85cb-cb898c73b137.png">
Plot2:
<img width="415" alt="plot2" src="https://cloud.githubusercontent.com/assets/26435939/24907860/d68077ba-1eb5-11e7-82ad-69635d80556c.png">

**Comment by Mattriks** [comment]
Here is an example:
```Julia
# In the next line, the number is the number of colors
palette = Scale.color_discrete().f(5)
# Type palette, and dump(palette) to see what's in palette

y = 5:-1:1
D = DataFrame(x=ones(5), y=y, yc=string.(y))
theme = Theme(default_point_size=10pt)
pa = plot(D, x=:x, y=:y, color=:yc, theme )
pb = plot(D, x=:x, y=:y, color=:yc, theme, Scale.color_discrete(palette, levels=["1","2","3","4","5"]))
```
![issue974](https://cloud.githubusercontent.com/assets/18226881/24925242/f8b7b6b0-1f3a-11e7-8b33-3bb4f7d1b4d4.png)
 See also [Scale.color_discrete](http://gadflyjl.org/stable/lib/scales/scale_color_discrete_manual.html). It also has an `order` argument, but you can achieve the same by mixing up `levels` e.g. `levels=["1","2","3","5","4"]`.

**Comment by Mattriks** [comment]
and to replace with "∞"
```Julia
D[D[:yc].=="5",:yc] = "∞"
pb = plot(D, x=:x, y=:y, color=:yc, theme, Scale.color_discrete(palette, levels=["1","2","3","4","∞"]))
```

**Comment by aviks** [comment]
@PeterJacko did this solve your issue? In general, it is easier to ask for help on our discourse forums, rather than on github issues https://discourse.julialang.org/c/domain/viz

**Comment by Mattriks** [comment]
Also useful to check if the user did ask on discourse!?:
https://discourse.julialang.org/t/color-and-legend-with-gadfly-how-can-i-control-them/3168

**Comment by bjarthur** [comment]
@Mattriks that discourse topic was started by the OP here
@PeterJacko please close this issue if your question is resolved

**Comment by PeterJacko** [comment]
@aviks @Mattriks @bjarthur Thanks for poking me!

Your answer wasn't exactly what I wanted, but it showed me the way. I wanted a fully automatic way, in which I would not need to manually adjust "levels" nor anything else.

Below is the solution I am happy with:
First, I have manually created a palette which is distinguishable even if printed in black & white, as "distinguishable_colors" wan't such. I have two variants, one for a paper (i.e. good looking on white background), and one for slides (i.e. good looking on my preferred dark blue background).

PJ_palette_paper = [ colorant"rgb(   0 ,   0 ,   0 )" colorant"rgb( 204 ,  96 ,  96 )" colorant"rgb(   0 , 113 ,   0 )" colorant"rgb( 141 , 141 , 204 )" colorant"rgb(  87 ,  87 ,  87 )" colorant"rgb( 204 , 144 , 204 )" colorant"rgb( 121 , 121 ,   0 )" colorant"rgb( 153 , 204 , 204 )"                   colorant"rgb(  46 ,  72 ,  46 )" colorant"rgb( 204 , 122 ,  96 )" colorant"rgb(   0 , 139 ,   0 )" colorant"rgb( 141 , 167 , 204 )" colorant"rgb(  87 , 113 ,  87 )" colorant"rgb( 204 , 170 , 204 )" colorant"rgb( 121 , 147 ,   0 )" colorant"rgb( 153 , 230 , 204 )"                   colorant"rgb(  46 ,  46 ,  72 )" colorant"rgb( 204 ,  96 , 122 )" colorant"rgb(   0 , 113 ,  26 )" colorant"rgb( 141 , 141 , 230 )" colorant"rgb(  87 ,  87 , 113 )" colorant"rgb( 204 , 144 , 230 )" colorant"rgb( 121 , 121 ,  26 )" colorant"rgb( 153 , 204 , 230 )"                   colorant"rgb(  46 ,  72 ,  72 )" colorant"rgb( 204 , 122 , 122 )" colorant"rgb(   0 , 139 ,  26 )" colorant"rgb( 141 , 167 , 230 )" colorant"rgb(  87 , 113 , 113 )" colorant"rgb( 204 , 170 , 230 )" colorant"rgb( 121 , 147 ,  26 )" colorant"rgb( 153 , 230 , 230 )"                   colorant"rgb(  72 ,  46 ,  46 )" colorant"rgb( 230 ,  96 ,  96 )" colorant"rgb(  26 , 113 ,   0 )" colorant"rgb( 167 , 141 , 204 )" colorant"rgb( 113 ,  87 ,  87 )" colorant"rgb( 230 , 144 , 204 )" colorant"rgb( 147 , 121 ,   0 )" colorant"rgb( 179 , 204 , 204 )"                   colorant"rgb(  72 ,  72 ,  46 )" colorant"rgb( 230 , 122 ,  96 )" colorant"rgb(  26 , 139 ,   0 )" colorant"rgb( 167 , 167 , 204 )" colorant"rgb( 113 , 113 ,  87 )" colorant"rgb( 230 , 170 , 204 )" colorant"rgb( 147 , 147 ,   0 )" colorant"rgb( 179 , 230 , 204 )"                   colorant"rgb(  72 ,  46 ,  72 )" colorant"rgb( 230 ,  96 , 122 )" colorant"rgb(  26 , 113 ,  26 )" colorant"rgb( 167 , 141 , 230 )" colorant"rgb( 113 ,  87 , 113 )" colorant"rgb( 230 , 144 , 230 )" colorant"rgb( 147 , 121 ,  26 )" colorant"rgb( 179 , 204 , 230 )"                   colorant"rgb(  72 ,  72 ,  72 )" colorant"rgb( 230 , 122 , 122 )" colorant"rgb(  26 , 139 ,  26 )" colorant"rgb( 167 , 167 , 230 )" colorant"rgb( 113 , 113 , 113 )" colorant"rgb( 230 , 170 , 230 )" colorant"rgb( 147 , 147 ,  26 )" colorant"rgb( 179 , 230 , 230 )"                   colorant"rgb(  71 ,  97 ,  71 )" colorant"rgb( 229 , 147 , 121 )" colorant"rgb(  25 , 164 ,  25 )" colorant"rgb( 166 , 192 , 229 )" colorant"rgb( 112 , 138 , 112 )" colorant"rgb( 229 , 195 , 229 )" colorant"rgb( 146 , 172 ,  25 )" colorant"rgb( 178 , 255 , 229 )"                   colorant"rgb(  71 ,  71 ,  97 )" colorant"rgb( 229 , 121 , 147 )" colorant"rgb(  25 , 138 ,  51 )" colorant"rgb( 166 , 166 , 255 )" colorant"rgb( 112 , 112 , 138 )" colorant"rgb( 229 , 169 , 229 )" colorant"rgb( 146 , 146 ,  51 )" colorant"rgb( 178 , 229 , 255 )"                   colorant"rgb(  71 ,  97 ,  97 )" colorant"rgb( 229 , 147 , 147 )" colorant"rgb(  25 , 164 ,  51 )" colorant"rgb( 166 , 192 , 255 )" colorant"rgb( 112 , 138 , 138 )" colorant"rgb( 229 , 195 , 255 )" colorant"rgb( 146 , 172 ,  51 )" colorant"rgb( 178 , 255 , 255 )"                   colorant"rgb(  97 ,  71 ,  71 )" colorant"rgb( 255 , 121 , 121 )" colorant"rgb(  51 , 138 ,  25 )" colorant"rgb( 192 , 166 , 229 )" colorant"rgb( 138 , 112 , 112 )" colorant"rgb( 255 , 169 , 229 )" colorant"rgb( 172 , 146 ,  25 )" colorant"rgb( 204 , 229 , 229 )"                   colorant"rgb(  97 ,  97 ,  71 )" colorant"rgb( 255 , 147 , 121 )" colorant"rgb(  51 , 164 ,  25 )" colorant"rgb( 192 , 192 , 229 )" colorant"rgb( 138 , 138 , 112 )" colorant"rgb( 255 , 195 , 229 )" colorant"rgb( 172 , 172 ,  25 )" colorant"rgb( 204 , 255 , 229 )"                   colorant"rgb(  97 ,  71 ,  97 )" colorant"rgb( 255 , 121 , 147 )" colorant"rgb(  51 , 138 ,  51 )" colorant"rgb( 192 , 166 , 255 )" colorant"rgb( 138 , 112 , 138 )" colorant"rgb( 255 , 169 , 255 )" colorant"rgb( 172 , 146 ,  51 )" colorant"rgb( 204 , 229 , 255 )"                   colorant"rgb(  97 ,  97 ,  97 )" colorant"rgb( 255 , 147 , 147 )" colorant"rgb(  51 , 164 ,  51 )" colorant"rgb( 192 , 192 , 255 )" colorant"rgb( 138 , 138 , 138 )" colorant"rgb( 255 , 195 , 255 )" colorant"rgb( 172 , 172 ,  51 )" colorant"rgb( 204 , 255 , 255 )"                   colorant"rgb( 148 ,  97 ,  97 )" colorant"rgb( 255 , 173 , 147 )" colorant"rgb( 102 , 164 ,  51 )" colorant"rgb( 243 , 192 , 255 )" colorant"rgb( 189 , 138 , 138 )" colorant"rgb( 255 , 221 , 255 )" colorant"rgb( 223 , 172 ,  51 )" colorant"rgb( 255 , 255 , 255 )" ]

PJ_palette_slides = [ colorant"rgb( 255 , 255 , 237 )" colorant"rgb( 204 ,  96 ,  96 )" colorant"rgb(   0 , 113 ,   0 )" colorant"rgb( 141 , 141 , 204 )" colorant"rgb(  87 ,  87 ,  87 )" colorant"rgb( 204 , 144 , 204 )" colorant"rgb( 121 , 121 ,   0 )" colorant"rgb( 153 , 204 , 204 )"                   colorant"rgb(  46 ,  72 ,  46 )" colorant"rgb( 204 , 122 ,  96 )" colorant"rgb(   0 , 139 ,   0 )" colorant"rgb( 141 , 167 , 204 )" colorant"rgb(  87 , 113 ,  87 )" colorant"rgb( 204 , 170 , 204 )" colorant"rgb( 121 , 147 ,   0 )" colorant"rgb( 153 , 230 , 204 )"                   colorant"rgb(  46 ,  46 ,  72 )" colorant"rgb( 204 ,  96 , 122 )" colorant"rgb(   0 , 113 ,  26 )" colorant"rgb( 141 , 141 , 230 )" colorant"rgb(  87 ,  87 , 113 )" colorant"rgb( 204 , 144 , 230 )" colorant"rgb( 121 , 121 ,  26 )" colorant"rgb( 153 , 204 , 230 )"                   colorant"rgb(  46 ,  72 ,  72 )" colorant"rgb( 204 , 122 , 122 )" colorant"rgb(   0 , 139 ,  26 )" colorant"rgb( 141 , 167 , 230 )" colorant"rgb(  87 , 113 , 113 )" colorant"rgb( 204 , 170 , 230 )" colorant"rgb( 121 , 147 ,  26 )" colorant"rgb( 153 , 230 , 230 )"                   colorant"rgb(  72 ,  46 ,  46 )" colorant"rgb( 230 ,  96 ,  96 )" colorant"rgb(  26 , 113 ,   0 )" colorant"rgb( 167 , 141 , 204 )" colorant"rgb( 113 ,  87 ,  87 )" colorant"rgb( 230 , 144 , 204 )" colorant"rgb( 147 , 121 ,   0 )" colorant"rgb( 179 , 204 , 204 )"                   colorant"rgb(  72 ,  72 ,  46 )" colorant"rgb( 230 , 122 ,  96 )" colorant"rgb(  26 , 139 ,   0 )" colorant"rgb( 167 , 167 , 204 )" colorant"rgb( 113 , 113 ,  87 )" colorant"rgb( 230 , 170 , 204 )" colorant"rgb( 147 , 147 ,   0 )" colorant"rgb( 179 , 230 , 204 )"                   colorant"rgb(  72 ,  46 ,  72 )" colorant"rgb( 230 ,  96 , 122 )" colorant"rgb(  26 , 113 ,  26 )" colorant"rgb( 167 , 141 , 230 )" colorant"rgb( 113 ,  87 , 113 )" colorant"rgb( 230 , 144 , 230 )" colorant"rgb( 147 , 121 ,  26 )" colorant"rgb( 179 , 204 , 230 )"                   colorant"rgb(  72 ,  72 ,  72 )" colorant"rgb( 230 , 122 , 122 )" colorant"rgb(  26 , 139 ,  26 )" colorant"rgb( 167 , 167 , 230 )" colorant"rgb( 113 , 113 , 113 )" colorant"rgb( 230 , 170 , 230 )" colorant"rgb( 147 , 147 ,  26 )" colorant"rgb( 179 , 230 , 230 )"                   colorant"rgb(  71 ,  97 ,  71 )" colorant"rgb( 229 , 147 , 121 )" colorant"rgb(  25 , 164 ,  25 )" colorant"rgb( 166 , 192 , 229 )" colorant"rgb( 112 , 138 , 112 )" colorant"rgb( 229 , 195 , 229 )" colorant"rgb( 146 , 172 ,  25 )" colorant"rgb( 178 , 255 , 229 )"                   colorant"rgb(  71 ,  71 ,  97 )" colorant"rgb( 229 , 121 , 147 )" colorant"rgb(  25 , 138 ,  51 )" colorant"rgb( 166 , 166 , 255 )" colorant"rgb( 112 , 112 , 138 )" colorant"rgb( 229 , 169 , 229 )" colorant"rgb( 146 , 146 ,  51 )" colorant"rgb( 178 , 229 , 255 )"                   colorant"rgb(  71 ,  97 ,  97 )" colorant"rgb( 229 , 147 , 147 )" colorant"rgb(  25 , 164 ,  51 )" colorant"rgb( 166 , 192 , 255 )" colorant"rgb( 112 , 138 , 138 )" colorant"rgb( 229 , 195 , 255 )" colorant"rgb( 146 , 172 ,  51 )" colorant"rgb( 178 , 255 , 255 )"                   colorant"rgb(  97 ,  71 ,  71 )" colorant"rgb( 255 , 121 , 121 )" colorant"rgb(  51 , 138 ,  25 )" colorant"rgb( 192 , 166 , 229 )" colorant"rgb( 138 , 112 , 112 )" colorant"rgb( 255 , 169 , 229 )" colorant"rgb( 172 , 146 ,  25 )" colorant"rgb( 204 , 229 , 229 )"                   colorant"rgb(  97 ,  97 ,  71 )" colorant"rgb( 255 , 147 , 121 )" colorant"rgb(  51 , 164 ,  25 )" colorant"rgb( 192 , 192 , 229 )" colorant"rgb( 138 , 138 , 112 )" colorant"rgb( 255 , 195 , 229 )" colorant"rgb( 172 , 172 ,  25 )" colorant"rgb( 204 , 255 , 229 )"                   colorant"rgb(  97 ,  71 ,  97 )" colorant"rgb( 255 , 121 , 147 )" colorant"rgb(  51 , 138 ,  51 )" colorant"rgb( 192 , 166 , 255 )" colorant"rgb( 138 , 112 , 138 )" colorant"rgb( 255 , 169 , 255 )" colorant"rgb( 172 , 146 ,  51 )" colorant"rgb( 204 , 229 , 255 )"                   colorant"rgb(  97 ,  97 ,  97 )" colorant"rgb( 255 , 147 , 147 )" colorant"rgb(  51 , 164 ,  51 )" colorant"rgb( 192 , 192 , 255 )" colorant"rgb( 138 , 138 , 138 )" colorant"rgb( 255 , 195 , 255 )" colorant"rgb( 172 , 172 ,  51 )" colorant"rgb( 204 , 255 , 255 )"                   colorant"rgb( 148 ,  97 ,  97 )" colorant"rgb( 255 , 173 , 147 )" colorant"rgb( 102 , 164 ,  51 )" colorant"rgb( 243 , 192 , 255 )" colorant"rgb( 189 , 138 , 138 )" colorant"rgb( 255 , 221 , 255 )" colorant"rgb( 223 , 172 ,  51 )" colorant"rgb( 255 , 255 , 255 )" ]

I have found also a suitable automatic point size: 

my_point_size = 100pt / number_of_observations_arm_1

Then I created the plot as follows:

plot( x = jjj - 1 , y = iii - 1 , color = iiijjjvalues , Scale.color_discrete_manual( PJ_palette_paper... , order = sortperm( unique( iiijjjvalues ) ) ) , Guide.xticks( ticks = collect( 0 : 10 : number_of_observations_arm_1 ) ) , Guide.yticks( ticks = collect( 0 : 10 : number_of_observations_arm_1 ) ) , Guide.xlabel( "# failures on arm 0" ) , Guide.ylabel( "# successes on arm 0" ) , Guide.colorkey( "" ) , Coord.cartesian( yflip = true , fixed = true ) , Geom.point , Theme( colorkey_swatch_shape = :circle , highlight_width = 0pt , default_point_size = my_point_size , plot_padding = 5pt , panel_fill = nothing , major_label_font_size = 11pt , minor_label_font_size = 9pt , key_title_font_size = 11pt , key_label_font_size = 9pt ) )

plot( x = jjj - 1 , y = iii - 1 , color = iiijjjvalues , Scale.color_discrete_manual( PJ_palette_slides... , order = sortperm( unique( iiijjjvalues ) ) ) , Guide.xticks( ticks = collect( 0 : 10 : number_of_observations_arm_1 ) ) , Guide.yticks( ticks = collect( 0 : 10 : number_of_observations_arm_1 ) ) , Guide.xlabel( "# failures on arm 0" ) , Guide.ylabel( "# successes on arm 0" ) , Guide.colorkey( "" ) , Coord.cartesian( yflip = true , fixed = true ) , Geom.point , Theme( colorkey_swatch_shape = :circle , highlight_width = 0pt , default_point_size = my_point_size , plot_padding = 5pt , panel_fill = nothing , background_color = colorant"rgb( 15 , 15 , 80 )" , major_label_font_size = 15pt , minor_label_font_size = 12pt , key_title_font_size = 15pt , key_label_font_size = 12pt , grid_color = colorant"rgb( 127 , 127 , 84 )" , major_label_color = colorant"rgb( 255 , 255 , 168 )" , minor_label_color = colorant"rgb( 255 , 255 , 168 )" , key_title_color = colorant"rgb( 255 , 255 , 168 )" , key_label_color = colorant"rgb( 255 , 255 , 168 )" ) )

You can see that I am using "order" with sorted iiijjjvalues.

![failures_60-30](https://user-images.githubusercontent.com/26435939/28261833-ca9c7880-6ad8-11e7-9117-22b79e34fd8c.png)

![failures_60-30](https://user-images.githubusercontent.com/26435939/28261862-e17ea19a-6ad8-11e7-9679-251f6e7eb627.png)

Note that there is an issue in the legend - a weird (almost vertical) line. It shows on all the plots I have generated...

**Comment by Mattriks** [comment]
I think the weird line issue was fixed by GiovineItalia/Compose.jl#296. If you see it again, please reopen as a new issue.
