### ISSUE TITLE
Error with Geom.smooth when using datatype Datetime for x values

### ISSUE THREAD

**Issue by trohwer** [GiovineItalia/Gadfly.jl#975]
Hello,

the above situation yields the following trace:

ERROR: MethodError: no method matching predict(::Loess.LoessModel{Float64}, ::Array{DateTime,1})
Closest candidates are:
  predict{T<:AbstractFloat}(::Loess.LoessModel{T<:AbstractFloat}, !Matched::T<:AbstractFloat) at /home/tr/.julia/v0.5/Loess/src/Loess.jl:129
  predict{T<:AbstractFloat}(::Loess.LoessModel{T<:AbstractFloat}, !Matched::AbstractArray{T<:AbstractFloat,1}) at /home/tr/.julia/v0.5/Loess/src/Loess.jl:134
  predict{T<:AbstractFloat}(::Loess.LoessModel{T<:AbstractFloat}, !Matched::AbstractArray{T<:AbstractFloat,2}) at /home/tr/.julia/v0.5/Loess/src/Loess.jl:167
 in apply_statistic(::Gadfly.Stat.SmoothStatistic, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /home/tr/.julia/v0.5/Gadfly/src/statistics.jl:1222
 in apply_statistics(::Array{Gadfly.StatisticElement,1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /home/tr/.julia/v0.5/Gadfly/src/statistics.jl:38
 in render_prepare(::Gadfly.Plot) at /home/tr/.julia/v0.5/Gadfly/src/Gadfly.jl:760
 in render(::Gadfly.Plot) at /home/tr/.julia/v0.5/Gadfly/src/Gadfly.jl:819
 in draw(::Compose.Image{Compose.CairoBackend}, ::Gadfly.Plot) at /home/tr/.julia/v0.5/Gadfly/src/Gadfly.jl:934

The reason is, that in statistics.jl around line 1222 the vector aes.x is passed unconverted to Loess.predict.
Changing the code (for the loess case) to

        aes.x = collect((x_min + nudge):((x_max - x_min) / num_steps):(x_max - nudge))

        if stat.method == :loess
            aes.y = Loess.predict(loess(xs, ys, span=stat.smoothing), convert(Vector{Float64}, aes.x))

,i.e. converting aes.x before passing to predict, fixes the problem for me.
There are some other places, where similar adaptations need to be done for other cases.

**Comment by tlnagy** [comment]
Can you give the code that threw this error so we can reproduce?

**Comment by trohwer** [comment]
This is a simplified example to reproduce it:

using Gadfly
using Cairo

myplot=plot(x=[Dates.DateTime(2017,4,1)+Dates.Day(i) for i=1:10],y=[i for i=1:10],Geom.point,Geom.smooth)
draw(PDF("test.pdf", 4inch, 3inch), myplot)

**Comment by Mattriks** [comment]
Here is some test code. In comparison with #978 and #980, this code aims to do the following:

* Make `Stat.smooth` work with `Date` and `DateTime` objects
* enable both smoothing methods i.e. `method=:lm` and `method=:loess`
* provide examples that work
```Julia
module Stat

using Loess, Gadfly, Colors, DataArrays

immutable SmoothStatistic2 <: Gadfly.StatisticElement
    method::Symbol
    smoothing::Float64

    function SmoothStatistic2(; method::Symbol=:loess, smoothing::Float64=0.75)
        new(method, smoothing)
    end
end


const smooth2 = SmoothStatistic2


function Gadfly.input_aesthetics(::SmoothStatistic2)
    return [:x, :y]
end


function Gadfly.output_aesthetics(::SmoothStatistic2)
    return [:x, :y]
end


function Gadfly.Stat.apply_statistic(stat::SmoothStatistic2,
                         scales::Dict{Symbol, Gadfly.ScaleElement},
                         coord::Gadfly.CoordinateElement,
                         aes::Gadfly.Aesthetics)

    Gadfly.assert_aesthetics_defined("Stat.smooth", aes, :x, :y)
    Gadfly.assert_aesthetics_equal_length("Stat.smooth", aes, :x, :y)

    if !(stat.method in [:loess,:lm])
        error("The only Stat.smooth methods currently supported are loess and lm.")
    end

    num_steps = 750

    if aes.color === nothing
        x_min, x_max = minimum(aes.x), maximum(aes.x)

        if x_min == x_max
            error("Stat.smooth requires more than one distinct x value")
        end

        local xs, ys, xsp

        try
            xs = convert(Vector{Float64}, aes.x)
            ys = convert(Vector{Float64}, aes.y)
        catch e
            error("Stat.loess and Stat.lm require that x and y be bound to arrays of plain numbers.")
        end

        # loess can't predict points <x_min or >x_max. Make sure that doesn't
        # happen through a floating point fluke
        nudge = 1e-5 * (x_max - x_min)
        
        # For a Date, dx might be 0 days, so correct
        dx = (x_max-x_min)*(1/num_steps)
        if isa(aes.x[1], Date)
            dx = max(dx, Dates.Day(1))
        end
        
        aes.x = collect((x_min + nudge):dx:(x_max - nudge))
        xsp = convert(Vector{Float64}, aes.x)
        
        if stat.method == :loess
            aes.y = Loess.predict(loess(xs, ys, span=stat.smoothing), xsp)
        elseif stat.method == :lm
            lmcoeff = linreg(xs,ys)
            aes.y = lmcoeff[2].*xsp .+ lmcoeff[1]
        end
    else
        groups = Dict()
        aes_color = aes.color === nothing ? [nothing] : aes.color
        for (x, y, c) in zip(aes.x, aes.y, cycle(aes_color))
            if !haskey(groups, c)
                groups[c] = (Float64[], Float64[])
            end

            try
                push!(groups[c][1], x)
                push!(groups[c][2], y)
            catch
                error("Stat.loess and Stat.lm require that x and y be bound to arrays of plain numbers.")
            end
        end

        aes.x = Array{eltype(aes.x)}(length(groups) * num_steps)
        aes.y = Array{eltype(aes.y)}(length(groups) * num_steps)
        colors = Array{RGB{Float32}}(length(groups) * num_steps)

        for (i, (c, (xs, ys))) in enumerate(groups)
            x_min, x_max = minimum(xs), maximum(xs)
            if x_min == x_max
                error("Stat.smooth requires more than one distinct x value")
            end
            nudge = 1e-5 * (x_max - x_min)
            steps = collect((x_min + nudge):((x_max - x_min) / num_steps):(x_max - nudge))

            if stat.method == :loess
                smoothys = Loess.predict(loess(xs, ys, span=stat.smoothing), steps)
            elseif stat.method == :lm
                lmcoeff = linreg(xs,ys)
                smoothys = lmcoeff[2].*steps .+ lmcoeff[1]
            end

            for (j, (x, y)) in enumerate(zip(steps, smoothys))
                aes.x[(i - 1) * num_steps + j] = x
                aes.y[(i - 1) * num_steps + j] = y
                colors[(i - 1) * num_steps + j] = c
            end
        end
        aes.color = PooledDataArray(colors)
    end
end

end

```

For this code to work, the change in #979 needs to be enabled. 
Here are the examples:  
Example 1:
```Julia
# Example 1: Without color groups
# This example works with x=:t1 and x=:t2,
# and you can use method=:lm or method=:loess in Stat.smooth2

i = Dates.Day.(1:50)
D = DataFrame(t1 = Date(2017,1,4)+i, t2=DateTime(2017,1,4)+i, y= [1:50;].+randn(50))
# t1 = Dates.value.(t)

# Try replacing x=:t1 with x=:t2
# and un/comment the lines below  
p=plot(D, x=:t1, y=:y, Geom.point, Geom.line, 
    Stat.smooth2(smoothing=0.2),
#    Stat.smooth2(method=:lm)
    )
```
![i975a](https://cloud.githubusercontent.com/assets/18226881/25039459/01da0ab4-2147-11e7-9811-6ad4548a1242.png)

Example 2:
```Julia
# Example 2: with color groups
# This example works with x=:t2, but not yet with x=:t1
# You can use method=:lm or method=:loess in Stat.smooth2

t1 = Date("2001-01-15"):Dates.Month(1):Date("2016-12-31")
t2 = DateTime("2001-01-15"):Dates.Month(1):DateTime("2016-12-31")
t = convert(Vector{Float64}, t1) 
n = length(t)
D = DataFrame(t1=t1, t2=t2, cycle = 5*sin(t*2π/365.25)+randn(n), trend = 0.1*[1.0:n;].+2*randn(n))
Dl = melt(D,[:t1,:t2])

p = plot(Dl,
    x=:t2, y=:value, color=:variable, Geom.point, Geom.line, 
    Stat.smooth2(smoothing=0.05),
#    Stat.smooth2(method=:lm),
    Theme(default_point_size=1.8pt, key_position=:none),
    Guide.xlabel("Years")
    )
```
![i975b](https://cloud.githubusercontent.com/assets/18226881/25039209/d5d08ad4-2145-11e7-9202-d78db5447924.png)

The next step is to make the second example work when `x=:t1`. Then I can submit a new PR (updating Gadfly.Stat.smooth).
