### ISSUE TITLE
Error in Logic for Histogram with density=true

### ISSUE THREAD

**Issue by trohwer** [GiovineItalia/Gadfly.jl#976]
I think, the scaling in density histogram is wrong; or at least, it does not align
with what Geom.density is doing. E.g. look at the code in statistics.jl:

if stat.density
            x_min = Gadfly.concrete_minimum(values)
            span = x_max - x_min
            binwidth = span / d
            bincounts = bincounts ./ sum(bincounts) * binwidth
        end

It should be / binwidth, not * binwidth. The integral over the density should yield 1, i.e.
sum bincount(i)*binwidth(i) should be 1, which is true, if * binwith is replaced by /binwidth
but not in most cases with this logic.

If I change the * to /, then the plot aligns with the Geom.density.

**Comment by Mattriks** [comment]
This was already noted in #822, but it looks like a PR wasn't submitted.

**Comment by trohwer** [comment]
Ok, I missed finding that bug report. I only checked, if the error was present in trunk.

**Comment by tlnagy** [comment]
Closed in favor of #822. We're hard at work getting the Gadfly stack onto Julia v0.6, but we would be happy to review a PR if you want to submit one based on the solution in that thread.
